### ISSUE TITLE
wrong Fullscreen render resolution

### ISSUE THREAD

**Issue by halop** [sm64pc/sm64pc#106]
Hi, I have compiled the master branch for Windows.
In window mode, the render resolution matches the window size. But when I switch to fullscreen mode with CTRL+Enter, the internal resolution is only 1536x864. I have discoverd this in the ReShade statistics. How do I get the full 1920x1080?
My desktop resolution is 1920x1080.

**Comment by Filipianosol** [comment]
> How do I get the full 1920x1080?
Right click on the exe and go to Properties -> Compatibility -> click Change high DPI settings -> check mark Override high DPI scaling behavior, leave it on Application and hit apply. This should fix your problem.

**Comment by coltongit** [comment]
@halop did @Filipianosol 's instructions fix your problem? I'd like to confirm before this can be closed.

**Comment by halop** [comment]
thanks, with this setting it renders in 1920x1080.
