### ISSUE TITLE
Koopa's pants have incorrect colors

### ISSUE THREAD

**Issue by Mastergatto** [sm64pc/sm64pc#117]
It's the same bug that all HLE graphic plugins have, at least until GlideN64 fixed that: https://github.com/gonetz/GLideN64/commit/c8cbafff71a81bee5112aaafe6e21d6648ff8125

SM64PC:
![koopa](https://user-images.githubusercontent.com/1028191/82095098-a27a3900-96fe-11ea-8df2-12d3ed008d7e.png)

Angrylion RDP (how it should look on N64):
![angrylion](https://user-images.githubusercontent.com/19976035/79403181-286a5f00-7f5c-11ea-99b6-3d8b0c24e9f5.png)

GlideN64 LLE (how it should look on SM64PC if fixed):
![gliden64](https://user-images.githubusercontent.com/19976035/79403175-24d6d800-7f5c-11ea-90c9-e4009430b5ff.png)

**Comment by urherenow** [comment]
I already saw a pull request with a fix, several hours ago, didn’t I? Before this issue was created.

**Comment by Mastergatto** [comment]
Lmao sorry, when I checked before there wasn't any PR, and I took some time to document this issue, I didn't quickly reported it. Anyways, thanks for the fix.

**Comment by uncletrunks** [comment]
#114 doesn't resolve to what's described here. Still need someone to take a look at this, might be an issue with the rendering.

**Comment by coltongit** [comment]
> 
> 
> #114 doesn't build to what's in that screenshot. Still need someone to take a look at this, might be an issue with the rendering.

#114 fixes what was originally a bug showcased even here. This was a bug in the N64 version as well, even on console.

**Comment by coltongit** [comment]
#128 fixes this once and for all by having both this fix and the burn smoke texture fix on a compile-time build flag.

**Comment by HeavenVolkoff** [comment]
Hello, @IvanDSM I don't think the original bug report by @Mastergatto was fixed. Although the incorrect light source reference in Koopa's model was resolved in @coltongit 's pull request. The problem reported here still occurs when building master with `TEXTURE_FIX=0`, as that is a bug in the renderer that I addressed in #126.

**Comment by coltongit** [comment]
> 
> 
> Hello, @IvanDSM I don't think the original bug report by @Mastergatto was fixed. Although the incorrect light source reference in Koopa's model was resolved in @coltongit 's pull request. The problem reported here still occurs when building master with `TEXTURE_FIX=0`, as that is a bug in the renderer that I addressed in #126.

#126 has been merged. Should be fixed now
