### ISSUE TITLE
Analog input cannot be disabled via config menu.

### ISSUE THREAD

**Issue by aFoxNamedMorris** [sm64pc/sm64pc#119]
**Description:**
After compiling with `BETTERCAMERA=1`, attempting to toggle analog camera off via the analog configuration menu does not restore the original camera behavior. 

**To Reproduce:**
1. Compile with `BETTERCAMERA=1`.
2. Run the game.
3. Enter any stage.
4. Pause the game.
5. Press the R button.
6. Disable analog camera.
7. Press R again to apply change.
8. Resume the game.
9. Attempt to move the camera.

**Expected behavior:**
When analog camera is disabled, the game should behave as it does on the N64, with C-button-style camera control.

**Desktop:**
 - OS: Manjaro Linux

**Comment by uncletrunks** [comment]
The difference between analog being set to off and analog being set to on is whether camera rotation works at a fixed speed or at a speed proportional to how far you've turned the analog stick. Right now this is working as intended, but this may be changed in the future. For the moment, build without the BETTERCAMERA flag if you don't want the camera changes.

**Comment by aFoxNamedMorris** [comment]
@uncletrunks Thank you for the clarification!
