### ISSUE TITLE
Build fail, missing msvcrt

### ISSUE THREAD

**Issue by goldug** [sm64pc/sm64pc#12]
I'm trying to build the testing branch with mingw64, but it error's out with

> /msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmsvcrt

**To Reproduce**
make -j8 TARGET_N64=0

 - OS: Windows 10

Working fine with Master branch (though Master branch has a couple of bugs atm).

**Comment by PuruShill** [comment]
A simple Google search for msvcrt would instantly tell you that's Microsoft Visual C++ Redistributable (instead of waiting 4 hours for no guarantee of an answer). Try downloading it and try again.
