### ISSUE TITLE
Texture filtering feature request

### ISSUE THREAD

**Issue by MissLav** [sm64pc/sm64pc#124]
add an option into the R options menu for GL_Nearest
![unknown](https://user-images.githubusercontent.com/51702517/82113616-0dd30380-971d-11ea-9871-09cc4f68e7d8.png)

**Comment by fgsfdsfgs** [comment]
Yes, that is planned. This is also mentioned in issue #97.

**Comment by MissLav** [comment]
> Yes, that is planned. This is also mentioned in issue #97.

danke sorry about that

**Comment by fgsfdsfgs** [comment]
Runtime texture filtering switch was added in 9ae444d. Don't forget to build with `EXT_OPTIONS_MENU=` and/or `BETTERCAMERA=1` to get the menu in.

**Comment by MissLav** [comment]
> EXT_OPTIONS_MENU=1
seems to be missing in the current make file
i can make my own based on the better cam option
![image](https://user-images.githubusercontent.com/51702517/82125303-a9d72c00-976a-11ea-846c-2f66d79790fd.png)

**Comment by fgsfdsfgs** [comment]
Oh yeah, that's in testing. If a specific commit isn't in master right now, the menu might not build without `-DBETTERCAMERA`. Hold on a sec.

**Comment by MissLav** [comment]
yea i just ran into that issue 
it doesnt currently pass build if it doesnt have bettercam

**Comment by fgsfdsfgs** [comment]
Should work now probably.

**Comment by MissLav** [comment]
danke
quick question do yall have a discord for this project?

**Comment by fgsfdsfgs** [comment]
Contact `Pathétique#3159` for more information about that.
