### ISSUE TITLE
Fixing the Smoke Bug

### ISSUE THREAD

**Issue by natepley** [sm64pc/sm64pc#125]
There's a bug in the original game that makes smoke render as garbage pixels.  Described here:
https://www.romhacking.net/hacks/5008/

It would be cool to see this fixed in the PC version of the game.

**Comment by fgsfdsfgs** [comment]
Might already be fixed in #112.

**Comment by natepley** [comment]
Nice!  I guess I'll close this issue, then!

**Comment by coltongit** [comment]
@natepley PR #128 will make this and other texture fixes available via setting `TEXTURE_FIX=1` during build.
