### ISSUE TITLE
lglew32 and lasound Missing

### ISSUE THREAD

**Issue by ecumber** [sm64pc/sm64pc#13]
I'm compiling on Ubuntu 18.04 on WSL and using mingw to make a windows build. During the main g++ compile part, it exits with these errors:

/usr/bin/ld: cannot find -lglew32
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libSDL2.a(SDL_dynapi.o): In function `SDL_InitDynamicAPI':
(.text+0x2282): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status
Makefile:892: recipe for target 'build/us_pc/sm64.us.f3dex2e.exe' failed
make: *** [build/us_pc/sm64.us.f3dex2e.exe] Error 1

Not sure if it is a WSL problem or the repository itself. Both libraries are installed.

**Comment by ecumber** [comment]
Both libraries are installed

**Comment by Jan200101** [comment]
you are using a linux toolchain to compile for Windows
That in itself is not possibly
Install msys2 on your windows system or the mingw toolchain on wsl
