### ISSUE TITLE
Some texture rendering breaks after reloading areas

### ISSUE THREAD

**Issue by Frolie** [sm64pc/sm64pc#149]
**Describe the bug**
After a map reloads by exiting and entering an area some textures may fail to map to objects and just rotate around with the camera.

**To Reproduce**
Easiest steps to reproduce the behavior:
1. Go to tiny huge island and enter from the left painting
2. Go to the huge version of the island through the nearby piranha plant pipe
3. Go back to tiny island through the same pipe
4. Step on the button just behind the pipe to load the boxes that make a path to the nearby island
5. At least one or two of the boxes should have the broken rendering

**Expected behavior**
Textures to map to objects and not rotate with camera
**Screenshots**
SS of this happening to the shack after the ccm slide:
![image](https://user-images.githubusercontent.com/26035047/82137685-23a10100-97cf-11ea-8303-6355f07d392d.png)
![image](https://user-images.githubusercontent.com/26035047/82137736-767ab880-97cf-11ea-8c94-7c7db2d9ac42.png)
SS of the THI example:
![image](https://user-images.githubusercontent.com/26035047/82137867-9d85ba00-97d0-11ea-951b-f37062a954a2.png)

**Desktop:**
 - OS: Windows 10

**Additional context**
This bug happens with and without better camera and no drawing distance build options

**Comment by HeavenVolkoff** [comment]
A fix for this is already in nightly.
https://github.com/sm64pc/sm64pc/commit/bc5942d189b048269f421f3c691fcf9fecece643

Could you test, to make sure it's working in all the areas you reported?

**Comment by Frolie** [comment]
Sure just give me a bit to build and test.

**Comment by Frolie** [comment]
After about 25 tests on THI with a better camera and no draw distance nightly build I was unable to reproduce the glitch so it seems to be fixed!

**Comment by uncletrunks** [comment]
Yeah we're pretty sure that it was me failing to reset the flag for this functionality (it's a new feature) on graph node object de-allocation. We knew about the shack bug but the THI one was new. Good to see that it's (ostensibly) fixed in both places.
