### ISSUE TITLE
Problem with autoreconf

### ISSUE THREAD

**Issue by ecumber** [sm64pc/sm64pc#16]
When running autoreconf for libaudiofile on MSYS2, I get this:

$ autoreconf -i
main::scan_file() called too early to check prototype at /usr/bin/aclocal-1.11 line 644.
previous directory /n/sm64x86/sm64pc/tools/audiofile-0.3.6 changed before entering /tmp/ar9xgYG4/am4t6ctrlf, expected dev=3768524088 ino=2251799814104932, actual dev=114811888 ino=7854401721473527134, aborting. at /usr/share/autoconf/Autom4te/General.pm line 196.
END failed--call queue aborted.
aclocal-1.11: /usr/bin/autom4te failed with exit status: 255
autoreconf: aclocal failed with exit status: 255
previous directory /n/sm64x86/sm64pc/tools/audiofile-0.3.6 changed before entering /tmp/ar9xgYG4, expected dev=3768524088 ino=2814749767526242, actual dev=114811888 ino=7854401721473527134, aborting. at /usr/share/autoconf/Autom4te/General.pm line 196.
END failed--call queue aborted.

Any ideas on what this is?

**Comment by urherenow** [comment]
you're using python 3.x instead of 2.7, more than likely. Install Python 2.7 and make sure /Python27 and /Python27/scripts is in your path (remove 3.x from your path for now)

**Comment by vrmiguel** [comment]
Any updates, @ecumber ?

**Comment by ecumber** [comment]
@urherenow I clean installed on a Windows 7 virtual machine and updated it because I had an install of msys2 from earlier that was causing issues and I didn't want to remove it. I was able to get around the autoreconf problem by compiling the original library and copying that to the lib folder instead.

**Comment by coltongit** [comment]
In which case, could we consider this issue fixed, @ecumber?

**Comment by ecumber** [comment]
I guess so.

**Comment by coltongit** [comment]
Alright, then. I'll have someone close this issue ASAP as the issue's been fixed.
