### ISSUE TITLE
After the new --configfile CLI option (I think) and using reshade, it can't read the configfile

### ISSUE THREAD

**Issue by porcino** [sm64pc/sm64pc#172]
When I use reshade, it doesn't read sm64config.txt, instead it creates something like 

"sm64config.txtRE=x86"
"sm64config.txtMSC"
"sm64config.txtCHITECTURE=x86"
"sm64config.txtESSOR_ARCHITECTURE¼‚ZAxû"
"sm64config.txtESSOR_ARCHITECTUREŠä–d{ö" 

It seems to depend on the length of the executable's name

 - OS: w7 x64

**Comment by vrmiguel** [comment]
Please try it again after building it with the https://github.com/sm64pc/sm64pc/commit/ba04643b61f480b06f0953233b88b29075e72518 commit on nightly and tell me if anything's different.

**Comment by porcino** [comment]
It works perfect now!
