### ISSUE TITLE
The game freezes in pirate bay  

### ISSUE THREAD

**Issue by uper333** [sm64pc/sm64pc#173]
Describe the bug
The game crashea in course 3 (pirate bay), I have managed to complete the first star without problems, but afterwards it does not matter what I try to crashed me shortly after entering the second star, either climbing diving whatever
El juego crashea en course 3 (bahia de los piratas, he conseguido completar la primera estrella sin problemas, pero despues da igual lo que intente que me crashea al poco de entrar a por la segunda estrella, ya sea escalando buceando lo que sea

To Reproduce
Go to course 3 (pirate's bay) after getting the first star and do whatever it takes, sooner or later crashea
Ir a course 3 (bahia de los piratas) despues de conseguir la primera estrella y hacer lo que sea, tarde o temprano crashea

Desktop

OS: windows 10
Version: compiled with BETTERCAMERA=1 NODRAWINGDISTANCE=1

**Comment by uper333** [comment]
Save
[sm64_save_file.zip](https://github.com/sm64pc/sm64pc/files/4641680/sm64_save_file.zip)

**Comment by coltongit** [comment]
Related to issues #159, #113, and #90

**Comment by Leon422** [comment]
It's a known issue with NODRAWINGDISTANCE. Better to compile the game without it for now for these stages. Will probably get fixed tonight tho, since @coltongit is a genius, so be on the lookout for commits :)

Es un fallo conocido con NODRAWINGDISTANCE. Mejor compila el juego sin eso por ahora para esos niveles. Pero seguramente lo arreglen esta noche igualmente porque @coltongit es un genio, así que estate atento a los cambios que van a hacer al código en breve :)

**Comment by uper333** [comment]
> It's a known issue with NODRAWINGDISTANCE. Better to compile the game without it for now for these stages. Will probably get fixed tonight tho, since @coltongit is a genius, so be on the lookout for commits :)
> 
> Es un fallo conocido con NODRAWINGDISTANCE. Mejor compila el juego sin eso por ahora para esos niveles. Pero seguramente lo arreglen esta noche igualmente porque @coltongit es un genio, así que estate atento a los cambios que van a hacer al código en breve :)

Thanks, the thing is that I had seen it in another post but it has not worked for me, but I think something is wrong with me, because I have tried to compile it without NODRAWINGDISTANCE and it is still activated, it has also happened to me with the BETTERCAMERA option, I have tried to compile it without that option because it was giving me problems on one level but it still worked.
I have tried these two lines:
PATH = / mingw32 / bin: / mingw64 / bin: $ PATH make BETTERCAMERA = 1 (without NODRAWINGDISTANCE = 1 to see if this works for pirate bay)
and with this one to leave the normal camera
PATH = / mingw32 / bin: / mingw64 / bin: $ PATH make NODRAWINGDISTANCE = 1 (without BETTERCAMERA = 1 so it wouldn't give me a level) but in both cases they were still activated

Gracias, la cosa es que lo habia visto en otro post pero no me ha funcionado, pero creo que algo me pasa, por que he probado a compilarlo sin NODRAWINGDISTANCE y sigue activada, tambien me ha pasado con la opcion de BETTERCAMERA, he intentado compilarlo sin esa opcion por que me estaba dando problemas en un nivel pero aun asi seguia funcionando.
He probado con estas dos lineas:
PATH=/mingw32/bin:/mingw64/bin:$PATH make BETTERCAMERA=1   (sin NODRAWINGDISTANCE=1 para ver si asi me funcionaba bahia de piratas)
y con esta otra para dejar la camara normal
PATH=/mingw32/bin:/mingw64/bin:$PATH make NODRAWINGDISTANCE=1  (sin BETTERCAMERA=1 para que no me diese problemas un nivel) pero en ambos casos seguian activadas

**Comment by Zoltar007** [comment]
@uper333 if you delete the `build` folder, you will be able to compile it without the `NODRAWINGDISTANCE` option.

**Comment by uper333** [comment]
> @ uper333 si elimina la `build`carpeta, podrá compilarla sin la `NODRAWINGDISTANCE`opción.

perfect, so if it works

**Comment by coltongit** [comment]
@uper333 a fix just went out to nightly. Please test there abd see if your issue still occurs.

**Comment by uper333** [comment]
> @uper333 a fix just went out to nightly. Please test there abd see if your issue still occurs.
I have tried a level and now it does not crash, but when I turn to the left it does not rotate, well it rotates a little but it does not have a stop, if I turn to the right it rotates well, it rotates continuously

He probado un nivel y ahora no crashea, pero la camara cuando giro a la izquierda no gira, bueno gira un poco pero no tiene un tope, si giro a la derecha gira bien, gira continuamente

**Comment by uper333** [comment]
> @uper333 a fix just went out to nightly. Please test there abd see if your issue still occurs.

I have passed the whole world without crashes, but now the camera when I turn to the left does not rotate, well it rotates a little but it has a stop, if I turn to the right it rotates well, it rotates continuously

**Comment by Plynthus** [comment]
I made a build somewhere between the draw distance fix and https://github.com/sm64pc/sm64pc/commit/4e7ce3ffbaffe55a4780e4ae9f7a4225c0eebeb4
Updating Bettercamera (also fixes cannons).
On that one the camera works great.

But now I made a build with the latest(with the bettercamera update) nightly and have the same problem as uper333.
Works normally with the mouse, but not with Xbox One controller when analogue camera is enabled.

So it shouldn't have anything to do with the draw distance fix.

**Comment by coltongit** [comment]
So the Bettercamera update causes another issue at the same time. Looks like I'll have to revert the update as it broke the camera.
Cannon fix is staying in though

**Comment by coltongit** [comment]
Everyone check PR #246 as it has a hotfix for the camera. Please test with the changes in it and see if your issues disappear.

**Comment by Plynthus** [comment]
> Everyone check PR #246 as it has a hotfix for the camera. Please test with the changes in it and see if your issues disappear.

In this one? https://github.com/sm64pc/sm64pc/commit/4e7ce3ffbaffe55a4780e4ae9f7a4225c0eebeb4

I don't see the changes. It says that vrmiguel committed 14 hours ago.
I'm new here. Is hotfix something that doesn't show up the same way.

I did download it again and make a new build. But it still had the same problem.

**Comment by Plynthus** [comment]
The analog camera works great with the changes. 
Also you meant PR #245.

Thanks a lot!

**Comment by coltongit** [comment]
> The analog camera works great with the changes. 
> Also you meant PR #245.
> 
> Thanks a lot!

You're welcome. It's been pushed to latest nightly.

**Comment by fgsfdsfgs** [comment]
I'm assuming this doesn't happen anymore on the latest nightly. Closing for now.
