### ISSUE TITLE
make clean breaks source code

### ISSUE THREAD

**Issue by superbonaci** [sm64pc/sm64pc#174]
````
make clean
rm -f -r build
````
````
gmake OSX_BUILD=1 
make: Nothing to be done for `all'.
cpp-9 -P -DVERSION_US -DNON_MATCHING -DAVOID_UB -DOSX_BUILD -I . -o build/us_pc/level_rules.mk levels/level_rules.mk
gmake: cpp-9: No such file or directory
Makefile.split:152: build/us_pc/level_rules.mk: No such file or directory
gmake: *** [Makefile.split:151: build/us_pc/level_rules.mk] Error 127
````

https://github.com/sm64pc/sm64pc/issues/26#issuecomment-629912394_

**Comment by coltongit** [comment]
try running a `make distclean` then retrying the build

**Comment by superbonaci** [comment]
Finally fixed with `make clean && gmake OSX_BUILD=1`.  Probably would be a good idea to mention the need of cleaning before each build on wiki or build guide. I wouldn't have realized it myself.

**Comment by coltongit** [comment]
I'd say this issue (as well as issue #26) are fixed. Go ahead and close these.
