### ISSUE TITLE
Switch Pro Controller support seems broken on Windows

### ISSUE THREAD

**Issue by Leon422** [sm64pc/sm64pc#183]
**Describe the bug**
When using a Switch Pro Controller on sm64pc under Windows, the left stick drifts down-right. This doesn't happen on Dolphin or on Steam.

**To Reproduce**
1. Use a Switch Pro Controller on Windows

**Expected behavior**
Mario stops moving when you stop moving the stick

**Screenshots**
https://cdn.discordapp.com/attachments/709244787626213496/712027876601626624/Super_Mario_64_PC_port_OpenGL_2020-05-18_20-44-22.mp4

Works fine on Dolphin as you can see here:
https://cdn.discordapp.com/attachments/709244787626213496/712030077793206382/2020-05-18_20-53-04.mp4

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Pingas

**Comment by vrmiguel** [comment]
As I have previously told you, this is an issue with how the controller is being calibrated, not the game. Fix it on Windows' Control Panel.
