### ISSUE TITLE
Moonjump doesn't work?

### ISSUE THREAD

**Issue by doctahoo** [sm64pc/sm64pc#185]
Hi,

I'm trying to use moonjump with L and nothing happens (just stomp). Am I missing something here?

**Comment by Leon422** [comment]
You have to map the "L Trigger" in the options. When the game says to have to press a button it's refering to the original N64 button, which is mapped to whatever button you want in whatever gamepad you're using. By default I think L is mapped to clicking the left stick, but you can change it to whatever you want.

Also, make sure to also turn on "Enable Cheats" as otherwise the cheats won't do anything. And keep in mind that you have to be in the air for the Moonjump to work (you can't start the moonjump while standing on the floor)

**Comment by Leon422** [comment]
Please confirm it's working so the issue can be closed.

**Comment by doctahoo** [comment]
I have assigned the moonjump to the same key for jumping (A) and now I can jump as usual (simple key press) or take a moonjump (long key press). So yes, I can confirm that it works, thank you!

By the way, I can start a moonjump directly from the floor. :-)

**Comment by Leon422** [comment]
> 
> 
> I have assigned the moonjump to the same key for jumping (A in my controller) and now I can jump as usual (simple key press) or take a moonjump (long key press). So yes, I can confirm that it works, thank you!
> 
> By the way, I can start a moonjump directly from the floor. :-)

Well, of course it does, because you set "A" to the same button so that's how Mario is getting off the floor ;) if you had set L to a different button then it wouldn't work like that. 

And I'm glad it worked!

**Comment by doctahoo** [comment]
Yes, you're right. Silly me.

By the way, any chance to get iron Mario, flying cap Mario, and so on in the cheats sometime in the near future?

Thank you for the cheats!

**Comment by Leon422** [comment]
> 
> 
> Yes, you're right. Silly me.
> 
> By the way, any chance to get iron cap Mario, flying cap Mario, and so on in the cheats sometime in the near future?
> 
> Thank you for the cheats!

I'll probably PR these cheats in the near future yes

**Comment by doctahoo** [comment]
Great! Please do so whenever you can add them.

And thanks for you work again.

**Comment by Throw-away64** [comment]
> You have to bind the "L Trigger" in the options. When the game says to have to press a button it's refering to the original N64 button, which is mapped to whatever button you want in whatever gamepad you're using. By default I think L is mapped to clicking the left stick, but you can change it to whatever you want.
> 
> Also, make sure to also turn on "Enable Cheats" as otherwise the cheats won't do anything. And keep in mind that you have to be in the air for the Moonjump to work (you can't start the moonjump while standing on the floor)

Yeah, Moonjump still don't work.

I've tried everything to get moonjump to work and it's not doing it.

I've swapping the desktop "left-shift" bind to the Left Bumper on my controller, setting both Left Bumper and Left Trigger to the "L" bind, Out right removing the "left-shift" bind so it only reads the Left Bumper for L inputs. I even tried setting "L" to "A" like the last guy who had this problem to get it psuedo-working but that didn't work either. I have combed through each and every single menu and I cannot for the life of me find a "Enable Cheats" tick box. (Unless this is referring to Turning cheats on in the " Mods and Game Modes" section but, that would seem... obvious? You couldn't access any the cheats if it wasn't turned on, so... meh. I got nothing.
