### ISSUE TITLE
(Question) Is it possible to Remap the Char values and change one char by other on the game?

### ISSUE THREAD

**Issue by MrVtR** [sm64pc/sm64pc#195]
Hello,I tried to search on the Discord group,but I didn't find anything about it.

I'm working on an translation of SM64 port for PC and Switch to Brazilian Portuguese. On the texts,we have some Special Characters that the US people doesn't have,like Á,É,Í,Ó,Ú for exemple.

I notice that the root of the sm64 folder have an "Charmap.txt" with an Table of all the Characters on US/EU/JP version and some EU chars are exately the chars I need. This file have some function on Makefile I think, because it's listed on there,but no idea what it do.

Is it possible to remap this "charmap.txt" or other file that might that contains the information of which char has its code?

For better illustration:
The '0' number have an 0x00 hexcode and the 'A' letter have an 0x0A hexcode,it's possible to change that and when I type 'A',the system display '0' on the game?
If it's possible,I can do the same with the "EU ROM Symbols" and add these chars to the US port?

**Comment by coltongit** [comment]
A PR is in the works that will add this feature to the game complete with proper symbols, special chars, and whatnot.
#60
