### ISSUE TITLE
Cannot Configure Stick Controls (besides keyboard)

### ISSUE THREAD

**Issue by enigma9o7** [sm64pc/sm64pc#198]
Tested with previous binary release and built from git master and nightly today (ubuntu 18), all have the same behavior.

My cheap usb snes-style controller is recognized, but no matter what I assing for stick controls, Mario will only move from keyboard.   I would like to set it my dpad for movement.   

I can set my dpad for the camera, but that's not so much needed, especially when enabling mouse.   As a sanity check I tried setting buttons to movement, thinking as a workaround I could use the controller upside-down.  Nope, nothing.

Also note in the UI, seems the third column of controls is not saved.

**Comment by fgsfdsfgs** [comment]
Yeah, the stick binds don't actually work for controllers. Gotta implement that.

**Comment by enigma9o7** [comment]
I'll look forward to it.  The only way I can figure out to move with my controller right now is by doing backflips, and I can't get very far that way :)
