### ISSUE TITLE
Audio Crackles

### ISSUE THREAD

**Issue by enigma9o7** [sm64pc/sm64pc#199]
I built from today's git source under Ubuntu 18, and now when I play, the audio crackles.

This does not happen with a pre-built binary I obtained earlier.

**Comment by vrmiguel** [comment]
That was a v-sync-related problem that is now believed to be fixed. Try rebuilding from the latest source on either master or nightly, and check which value `vsync` has on the config. file.

**Comment by enigma9o7** [comment]
vsync 1, built  from master.  I'll try now from nightly.
