### ISSUE TITLE
Unable to compile testing branch on Ubuntu

### ISSUE THREAD

**Issue by sheepo99** [sm64pc/sm64pc#2]
Getting the following errors when attempting to compile:
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libGL.so when searching for -lGL
/usr/bin/ld: cannot find -lGL
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libSDL2.so when searching for -lSDL2
/usr/bin/ld: skipping incompatible //usr/lib/x86_64-linux-gnu/libSDL2.a when searching for -lSDL2

Both of these libs are installed, and I also tried ln -s to not avail

Running Ubuntu 18.04 x86_64 Linux 4.15.0-99-generic

**Comment by sheepo99** [comment]
I'm reopening this issue, because this seems to present specifically in the testing branch. The master is compiling fine, but the testing is giving me the error messages above.

**Comment by vrmiguel** [comment]
It ignored your x86_64-linux-gnu/libGL.so file so it's probably looking for the 32 bit libraries.
Do you have libsd2-dev:i386 and libglew-dev:i386 installed?

**Comment by sheepo99** [comment]
No, but why is this branch not building for 64bit then?

**Comment by sheepo99** [comment]
I do have libsd2-dev:i386 installed though.

**Comment by Jan200101** [comment]
you cannot install libsdl2-dev:i386 and libsdl2-dev:amd64 at the same time I checked
the same might be true for libglrew-dev

**Comment by sheepo99** [comment]
Yeah, this seems to be problem alright. Why is this build only compiling with 32bit libs though?

**Comment by vrmiguel** [comment]
Well, depends on which flags you're using and what libraries you've got installed. Running `make -TARGET_BITS=32 -TARGET_ARCH=native` with the correct libraries installed fails?

**Comment by sheepo99** [comment]
Yeah that fixes it, thanks! perhaps adding these instructions to the readme in the future?
