### ISSUE TITLE
Wiki guide for setting up MSYS2 runs into "Unrecognized archive format" Errors

### ISSUE THREAD

**Issue by kolt54321** [sm64pc/sm64pc#203]
**Describe the bug**
Initial installing of MSYS2 went fine. But for updating MSYS2 using:

    pacman -Syuu

Runs into the following error:

    :: Proceed with installation? [Y/n] y
    (8/8) checking keys in keyring                                                          
    [############################################] 100%
    (8/8) checking package integrity                                                
    [############################################] 100%
    (8/8) loading package files                                                     
    [############################################] 100%
    error: could not open file /var/cache/pacman/pkg/msys2-runtime-3.1.4-1-x86_64.pkg.tar.zst:  
    Unrecognized archive format
    error: failed to commit transaction (cannot open package file)
    Errors occurred, no packages were upgraded.

**To Reproduce**

Following [guide here](https://github.com/orlp/dev-on-windows/wiki/Installing-GCC--&-MSYS2) linked in the wiki, and error occurs on step 4. 

**Expected behavior**
The update to occur

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Hoping to get this up and running! Thanks for the wiki, hoping we can fix this.

I've tried following solutions online, including [this one](https://forum.manjaro.org/t/pacman-error-unrecognized-archive-format/121517/2) here, but am having trouble running the final command on a windows machine. I've also tried removing the file, but rather than corrupt I think it may be an issue with zst files not being natively supported. But I'm still new with this stuff.

**Comment by zerocloude** [comment]
1. Have you tried completely reinstalling MSYS2?
2. After completing step 2, there were no problems with closing MSYS2 shell?

**Comment by kolt54321** [comment]
Thanks for the quick response @zerocloude ! I've tried reinstalling and noticed the error actually occurs on step two (good insight there). The error is below:

$ pacman -Syuu
:: Synchronizing package databases...
 mingw32                  462.4 KiB   932K/s 00:00 [#####################] 100%
 mingw32.sig              119.0   B  0.00B/s 00:00 [#####################] 100%
 mingw64                  465.0 KiB  3.01M/s 00:00 [#####################] 100%
 mingw64.sig              119.0   B  0.00B/s 00:00 [#####################] 100%
 msys                     183.3 KiB  3.03M/s 00:00 [#####################] 100%
 msys.sig                 119.0   B  0.00B/s 00:00 [#####################] 100%
:: Starting core system upgrade...
warning: terminate other MSYS2 programs before proceeding
resolving dependencies...
looking for conflicting packages...

Packages (8) bash-4.4.023-2  filesystem-2020.02-2  libzstd-1.4.4-2
             mintty-1~3.1.4-1  msys2-runtime-3.1.4-1  pacman-5.2.1-6
             pacman-mirrors-20200329-1  zstd-1.4.4-2

Total Download Size:   16.96 MiB
Total Installed Size:  65.76 MiB
Net Upgrade Size:       9.48 MiB

    :: Proceed with installation? [Y/n] y
    :: Retrieving packages...
     msys2-runtime-3.1.4...     3.0 MiB  2.13M/s 00:01 [#####################] 100%
     bash-4.4.023-2-x86_64   1934.3 KiB  3.22M/s 00:01 [#####################] 100%
     filesystem-2020.02-...    44.9 KiB  5.49M/s 00:00 [#####################] 100%
     mintty-1~3.1.4-1-x86_64  668.9 KiB  1922K/s 00:00 [#####################] 100%
     pacman-mirrors-2020...    20.3 KiB  3.30M/s 00:00 [#####################] 100%
     libzstd-1.4.4-2-x86_64   259.0 KiB  2.84M/s 00:00 [#####################] 100%
     zstd-1.4.4-2-x86_64      304.7 KiB  3.13M/s 00:00 [#####################] 100%
     pacman-5.2.1-6-x86_64     10.8 MiB  2.21M/s 00:05 [#####################] 100%
    (8/8) checking keys in keyring                     [#####################] 100%
    (8/8) checking package integrity                   [#####################] 100%
    (8/8) loading package files                        [#####################] 100%
    error: could not open file /var/cache/pacman/pkg/msys2-runtime-3.1.4-1-x86_64.pk                               
    g.tar.zst: Unrecognized archive format
    error: failed to commit transaction (cannot open package file)
    Errors occurred, no packages were upgraded.

**Comment by fgsfdsfgs** [comment]
Something's definitely wrong on your end. I've never seen that happen before.

**Comment by zerocloude** [comment]
I installed MSYS2 on my laptop (C drive) and my work PC (D drive). In both cases, in the second step, the MSYS2 shell asked me to close it, no errors occured. So, yes, try installing it on an another drive.

**Comment by kolt54321** [comment]
I'm not the only one...

https://github.com/msys2/MSYS2-packages/issues/1960

**Comment by kolt54321** [comment]
Using the installer on [msys2.org](https://www.msys2.org/) solved the issue.
