### ISSUE TITLE
No "L" N64 trigger button defined in Controller_SDL (Updated)

### ISSUE THREAD

**Issue by Hyenadae** [sm64pc/sm64pc#21]
**Describe the bug**
There's no L button defined for SDL Controller input, or any way to cleanly map it to modern controllers (more than 2 shoulder buttons)

**Expected behavior**
Have the L Trigger assigned and passed to the virtual N64 controller

I have seen references to other SDL controllers on github, it may be possible to define
a Left/Right "Trigger" (back pair of shoulders) to match XBox + Playstation controller layouts. 

Gamecube will only have RightTrigger if created of course.

**Screenshots**
N/A

**Additional context**
Puppycam / Newcam mods have L+R actions, Mario 64 doesn't use L for anything, but the controller still has it.

**Comment by Hyenadae** [comment]
Pull request added. Keyboard only but sdl_controller.c can be patched to remap actual controllers.

**Comment by y0shin** [comment]
Merged, but leaving issue open until actual controller defines are done.

**Comment by vrmiguel** [comment]
This [commit](https://github.com/sm64pc/sm64pc/commit/76783f2ab01f29ca4eee9de251a90dc088ad0f55) should fix that.
