### ISSUE TITLE
[Feature request] Settings, submenu cheats in pause menu

### ISSUE THREAD

**Issue by Tikilou** [sm64pc/sm64pc#212]
I've been working on cheat support too when i've seen the commit about it. I was choosing a different way, wich activated cheats only when i've unpaused. (+1 up, +1 health, Mario caps, special triple jump enabled...), already shared with the dev of cheats support already pushed.
Unfortunatly i'm not so good with C, so i'm asking about a new entrie in pause menu (like the entrie "exit game") with submenu for cheats.

It could be like that :

-Continue
-Exit course
-Exit Game
-Settings => Cheats
-Set Camera Angle With R

In cheat submenu :
-Enable cheats : Yes/No
-Enable moon jump (Press Z) : Yes/No
-Enable wing cap (infinite when activated) : Yes/No
-Enable high triple jump with wing cap : Yes/No
-Enable metal cap (infinite when activated) : Yes/No
-Enable vanish cap (infinite when activated) : Yes/No
-Enable special tripe jump : Yes/No
-Enable invincibility : Yes/No
-Infinite lives : Yes/No
-Disable collision (Ennemy/walls invisible or not) : Yes/No
-Freeze IA : Yes/No
-Hard mode (Half life/Oxygen/Disable recovery with water) : Yes/No
-Enable super jump : Yes/No
if yes :
+Set super jump : low/middle/high
-Super speed : low/middle/high
if yes :
-Set super speed : low/middle/high

All of that could be saved directly in sm64config.txt

**Comment by Leon422** [comment]
There is already a submenu for cheats in the pause menu. However, it was recently changed so that you have to open the game with the --cheats CLI in order to see them. If you're on Windows, create a shortcut to the game, right click it, properties, and add --cheats to the end of the shortcut destination.

**Comment by Tikilou** [comment]
> There is already a submenu for cheats in the pause menu. However, it was recently changed so that you have to open the game with the --cheats CLI in order to see them. If you're on Windows, create a shortcut to the game, right click it, properties, and add --cheats to the end of the shortcut destination.

I missed that, thank you ! :)
I'm on Linux. ;-)

**Comment by Tikilou** [comment]
This on nightly ? I've compiled and launched game with --cheats in CLI, and there is no setting about cheats... No exit game option too.

**Comment by Leon422** [comment]
> 
> 
> This on nightly ? I've compiled and launched game with --cheats in CLI, and there is no setting about cheats... No exit game option too.

Are you compiling the game with `BETTERCAMERA=1`? If not, you need to either compile the game with `BETTERCAMERA=1`, or with `EXT_OPTIONS_MENU=1` to see the options menu.

**Comment by Tikilou** [comment]
> > This on nightly ? I've compiled and launched game with --cheats in CLI, and there is no setting about cheats... No exit game option too.
> 
> Are you compiling the game with `BETTERCAMERA=1`? If not, you need to either compile the game with `BETTERCAMERA=1`, or with `EXT_OPTIONS_MENU=1` to see the options menu.

Yes i am. i've tested Only with BETTERCAMERA=1 only with EXT_OPTIONS_MENU=1, or both, and launched game with or without --cheats in CLI.
Still nothing about exit game or submenu cheats.
![Capture d’écran de 2020-05-19 18-20-20](https://user-images.githubusercontent.com/5641661/82351911-85df4900-99fd-11ea-9b61-7c2f4ee360ab.png)

**Comment by Leon422** [comment]
...

![imagen](https://user-images.githubusercontent.com/15913880/82352118-71974e00-99f5-11ea-91a3-89095a965a08.png)

**Comment by coltongit** [comment]
Press the R button to go to the options first @Tikilou

**Comment by Tikilou** [comment]
Ooh, okay, sorry about that !
Just a last question about cheat; do you have any idea how to apply "-- cheat" argument with the webgl build launched in browsers ?

**Comment by Leon422** [comment]
> 
> 
> Ooh, okay, sorry about that !
> Just a last question about cheat; do you have any idea how to apply "-- cheat" argument with the webgl build launched in browsers ?

It doesn't really matter anymore. A change was pushed to nightly which allows you to unlock the cheats simply by pressing the L button (as in the N64 L button, check your bindings) three times while in the options menu. You'll hear a sound. Then you get out of the options menu, get back in, and you'll see the cheats menu. 

Update to the latest nightly and you'll get this feature.

**Comment by Tikilou** [comment]
It's great !!! Thanks you ! =)
