### ISSUE TITLE
Altering the Makefile - bash: tabledesign_CFLAGS: command not found

### ISSUE THREAD

**Issue by kolt54321** [sm64pc/sm64pc#215]
**Describe the bug**
Trying to compile on Windows, altering the makefile with the command listed in the wiki results in a not recognized error

**To Reproduce**

I am in the `tools` folder, running the below

`tabledesign_CFLAGS := -Wno-uninitialized -laudiofile -lstdc++`

It results in:

`bash: tabledesign_CFLAGS: command not found`

**Desktop (please complete the following information):**
 - OS: Windows 10

Thanks!

**Comment by coltongit** [comment]
What compiler are you using?

**Comment by kolt54321** [comment]
I'm on MSYS2, following the wiki guide.

**Comment by coltongit** [comment]
did you make sure you ran `pacman -Syuu` first?

**Comment by kolt54321** [comment]
Yep! No upgrades available.

**Comment by coltongit** [comment]
Do you have a full buildlog of what happens when you try to compile using these particular CFLAGS?

**Comment by kolt54321** [comment]
Hey @coltongit - I'm not sure what you mean (very new to compiling unfortunately). Is there a specific command I can use to get you the buildlog? I haven't run the final two `make` commands - I'm up to [here](https://imgur.com/a/4uXcwD3). Everything up till that point ran smoothly.

**Comment by coltongit** [comment]
use the same make command you ran before, but at the end use `&> buildlog.txt`

**Comment by coltongit** [comment]
Does the latest nightly fix your issue? I integrated the makefile change into the source itself.

**Comment by kolt54321** [comment]
[Here's the log](https://pastebin.com/X03hgkRK) - looks like it's hitting an error actually.

**Comment by coltongit** [comment]
Try running `make -C tools clean` then rerun the make command you're using. That might fix your issue.

**Comment by kolt54321** [comment]
Is there a specific directory I should run that in? Running it in the audiofile-0.3.6 folder outputs the following

 `$ make -C tools clean
make: *** tools: No such file or directory.  Stop.`

**Comment by coltongit** [comment]
run it in the root sm64pc folder

**Comment by kolt54321** [comment]
The clean seemed to run okay, but it hasnt fixed the issue unfortunately. I'm still setting it up for the nightly build.

`TestUser@DESKTOP MSYS /c/Users/TestUser/Downloads/sm64pc-1
$ make -C tools clean
make: Entering directory '/c/Users/TestUser/Downloads/sm64pc-1/tools'
rm -f n64graphics n64graphics_ci mio0 n64cksum textconv patch_libultra_math iplfontutil aifc_decode aiff_extract_codebook vadpcm_enc tabledesign extract_data_for_mio skyconv
make: LeTestUserng directory '/c/Users/TestUser/Downloads/sm64pc-1/tools'

TestUser@DESKTOP MSYS /c/Users/TestUser/Downloads/sm64pc-1
$ cd ./tools/

TestUser@DESKTOP MSYS /c/Users/TestUser/Downloads/sm64pc-1/tools
$ tabledesign_CFLAGS := -Wno-uninitialized -laudiofile -lstdc++
bash: tabledesign_CFLAGS: command not found`

**Comment by coltongit** [comment]
```
TestUser@DESKTOP MSYS /c/Users/TestUser/Downloads/sm64pc-1/tools
$ tabledesign_CFLAGS := -Wno-uninitialized -laudiofile -lstdc++
bash: tabledesign_CFLAGS: command not found
```
you aren't supposed to run it like that

**Comment by kolt54321** [comment]
@coltongit - sorry, so how should I run it? I'm just running the command from the wiki. 

Is there another piece I'm not aware of?

**Comment by coltongit** [comment]
> 
> 
> @coltongit - sorry, so how should I run it? I'm just running the command from the wiki.
> 
> Is there another piece I'm not aware of?

Use `vim`, `nano`, or similar to edit the Makefile if you aren't running nightly. If you are, then you're already OK, as the change was done for you. cd back to the root sm64pc folder and run the final make command in the wiki

**Comment by kolt54321** [comment]
Now I see - sorry, complete oversight, now I understand. I've ran the nightly and unfortunately hitting an error there, but if it keeps happening that should be a separate post. I'll close this one.

**Comment by coltongit** [comment]
@kolt54321 A fix should be in nightly now. Make sure you update your copy of nightly and retry the build.

**Comment by kolt54321** [comment]
Thanks! I managed to get it working with the main build, no worries.
