### ISSUE TITLE
How to remap controls?

### ISSUE THREAD

**Issue by kolt54321** [sm64pc/sm64pc#224]
There is two ways to map controls - one, though the config file, and the second through the submenu by pressing **R** in the pause menu. 

However, controls seem to be represented in 4 letter/number combinations. For example, here is a key mapping:

`0026 1000 1103 `

How can we find out which keyboard keys translate to which numbers?

**Comment by enigma9o7** [comment]
https://pastebin.com/Y6dad3Zy

sdl2.h

**Comment by kolt54321** [comment]
@enigma9o7 - I have that paste bookmarked, but it seems like the new controls are in a different format. Instead of just two-digit numbers, now there's three four-digit numbers for each key.

**Comment by enigma9o7** [comment]
You can assign three keycodes to each function.  Although the 2nd and 3rd rows are flakey.  

So for example to map a controller, you leave the keyboard commands in the first column and just edit the middle.   Four digits codes are controllers, keyboard has the first 255 or 512 or something...

**Comment by kolt54321** [comment]
Oh thank you! Didn't realize that the codes had a leading two zeros.

I'm guessing the key mappings for a controller is still in discussion, based on your post [here](https://github.com/sm64pc/sm64pc/issues/198)? The pastebin link seems to have only keyboard codes.

**Comment by kolt54321** [comment]
@enigma9o7 Unfortunately, the first set of values don't seem to bind. Tried setting **a** to the key **j** and the keys are all over the place.

**Comment by fgsfdsfgs** [comment]
These are not equivalent to the SDL scancodes. These are hex numbers for virtual keys.
Codes ranging from `1000` to `10ff` are gamepad buttons, `1100`-`11ff` are mouse buttons.
Keyboard keys range from `0000` to `0fff` and directly correspond to [DirectInput scancodes](https://gist.github.com/tracend/912308). Don't ask. Gotta remove that translation table sometime.
Thus, J would be `0024`, LeftShift would be `002a`.

**Comment by kolt54321** [comment]
Thanks @fgsfdsfgs . I'm guessing 0x24 = 0024? I noticed that the game converted it.

**Comment by fgsfdsfgs** [comment]
Yes. `0x` is just a prefix to indicate hexadecimals in C. It is not used in the config files.

**Comment by enigma9o7** [comment]
And as to my stick issue you linked, if you have a controller with a stick I think it does work.   But I have snes style controller, no stick, and yeah can't yet assign dpad to stick controls :(

**Comment by kmltdr** [comment]
So here are default values (at least for c18e70f44eaf628f5795002c29166bbfc4835238):

| N64 Controller | Keyboard    | sm64config.txt |
|----------------|-------------|----------------|
| A              | L           | 0026           |
| B              | , (comma)   | 0033           |
| Start          | Space       | 0039           |
| L              | . (period)  | 0034           |
| R              | Right shift | 0036           |
| Z              | K           | 0025           |
| C up           | Up arrow    | 0148           |
| C down         | Down arrow  | 0150           |
| C left         | Left arrow  | 014b           |
| C right        | Right arrow | 014d           |
| Stick up       | W           | 0011           |
| Stick down     | S           | 001f           |
| Stick left     | A           | 001e           |
| Stick right    | D           | 0020           |
                                                
Why codes for arrow keys are not equal to DirectInput scan codes for arrow keys?
```
#define DIK_UP              0xC8    /* UpArrow on arrow keypad */
#define DIK_LEFT            0xCB    /* LeftArrow on arrow keypad */
#define DIK_RIGHT           0xCD    /* RightArrow on arrow keypad */
#define DIK_DOWN            0xD0    /* DownArrow on arrow keypad */
```

**Comment by fgsfdsfgs** [comment]
Good question to which I have no answer. For some reason `0x100` is added to the SDL scancode value in gfx_sdl2 instead of converting it to the dxinput scancode.

**Comment by AaronMT** [comment]
Would anyone happen to have an sm64config of an Xbox One controller config (compiled the project on Mac)?

**Comment by superbonaci** [comment]
@AaronMT could you test for me the app [Key Codes](https://apps.apple.com/us/app/key-codes/id414568915?mt=12) and report if you can see Xbox One controller key codes as you press them?
If displayed set them on sm64config and test.

**Comment by AaronMT** [comment]
> @AaronMT could you test for me the app [Key Codes](https://apps.apple.com/us/app/key-codes/id414568915?mt=12) and report if you can see Xbox One controller key codes as you press them?
> If displayed set them on sm64config and test.

Both DS4 and Xbox One Controller (Wired) are non visible in this app unfortunately

**Comment by superbonaci** [comment]
> Both DS4 and Xbox One Controller (Wired) are non visible in this app unfortunately

Maybe security related? Could you try this:
[pynput keyboard listener does not detect keys on Mac OS X](https://stackoverflow.com/questions/53088995/pynput-keyboard-listener-does-not-detect-keys-on-mac-os-x)

**Comment by fgsfdsfgs** [comment]
The gamepad buttons currently are 1:1 with [SDL gamepad buttons](https://github.com/SDL-mirror/SDL/blob/master/include/SDL_gamecontroller.h#L349).  The enum goes -1 for INVALID, 0 for A, 1 for B, etc, so 1100 for A, 1101 for B...

**Comment by superbonaci** [comment]
@AaronMT did that work?

**Comment by AaronMT** [comment]
I might be setting the values wrong. What are the second and third values defined here?
Swapping from: 
 ```key_a 0026 1000 1103 ```
To: 
 ```key_a 0010 1000 1103 ```

**Comment by enigma9o7** [comment]
Have you tried recording your nes style controller in the games UI?

I have snes style, and the games UI recognizes everything except right shoulder.  That website you linked confirms its not my controller tho as it recognizes it as button 5.   Plus in my experience it doesn't always save what you put in the file or record with UI...

**Comment by AaronMT** [comment]
> Have you tried recording your nes style controller in the game's UI?
> 
> I have snes style, and the game's UI recognizes everything except right shoulder. That website you linked confirms its not my controller tho as it recognizes it as button 5. Plus in my experience it doesn't always save what you put in the file or record with UI...

No key events are being detected from the gamepads (on the MacOS build) from within the running application.

**Comment by AaronMT** [comment]
Pairing the DS4 via Bluetooth and not USB does seem to work (build: c18e70 on Catalina 10.15.4). Figure it's a MacOS compatibility thing after-all.

**Comment by superbonaci** [comment]
Probably there are no usb drivers for DS4 for acOS. For Windows there's `DS4Windows`, if you could try of works that way (on Windows) you could report.

**Comment by Tiagoquix** [comment]
Here's my set of remapped controls for keyboard + mouse:

```
key_a 0039 ffff ffff 
key_b ffff ffff 1101 
key_start 001c ffff ffff 
key_l 0010 ffff ffff 
key_r 0012 ffff ffff 
key_z ffff ffff 1103 
key_cup 0148 ffff ffff 
key_cdown 0150 ffff ffff 
key_cleft 014b ffff ffff 
key_cright 014d ffff ffff 
key_stickup 0011 ffff ffff 
key_stickdown 001f ffff ffff 
key_stickleft 001e ffff ffff 
key_stickright 0020 ffff ffff 
```

Here's a comprehensible list:

N64 Controller | Action(s) | Keyboard | Gamepad | Mouse | sm64config.txt | Notes
:-: | :-: | :-: | :-: | :-: | :-: | :-:
A | Jump/advance text | Space | | | `key_a 0039 ffff ffff`
B | Punch | | | Left mouse button | `key_b ffff ffff 1101`
Start | Press "Start"/pause menu | Enter (main keyboard) | | | `key_start 001c ffff ffff`
L | Centralize camera | Q | | | `key_l 0010 ffff ffff`
R | Switch camera modes | E | | | `key_r 0012 ffff ffff`
Z | Duck/crouch | | | Right mouse button | `key_z ffff ffff 1103`
C up | Zoom in/look around | Up arrow | | | `key_cup 0148 ffff ffff` | Doesn't work with Better Camera (Free Camera) enabled.
C down | Zoom out | Down arrow | | | `key_cdown 0150 ffff ffff` | Doesn't work with Better Camera (Free Camera) enabled.
C left | Rotate/center camera | Left arrow | | | `key_cleft 014b ffff ffff` | Doesn't work with Better Camera (Free Camera) enabled.
C right | Rotate/center camera | Right arrow | | | `key_cright 014d ffff ffff` | Doesn't work with Better Camera (Free Camera) enabled.
Stick up | Movement | W | | | `key_stickup 0011 ffff ffff`
Stick down | Movement | S | | | `key_stickdown 001f ffff ffff`
Stick left | Movement | A | | | `key_stickleft 001e ffff ffff`
Stick right | Movement | D | | | `key_stickright 0020 ffff ffff`

Notes:
1101 = left mouse button
1102 = middle mouse button (pressing "scroll")
1103 = right mouse button

Actions list taken from https://strategywiki.org/wiki/Super_Mario_64/Controls + personal experience.

**Comment by djvs** [comment]
For what it's worth, Tiago's controls above would make a much better default.

**Comment by djvs** [comment]
```
0001	ESC
0002	1
0003	2
0004	3
0005	4
0006	5
0007	6
0008	7
0009	8
000a	9
000b	0
000c	-
000d	=
000e	bs
000f	Tab
0010	Q
0011	W
0012	E
0013	R
0014	T
0015	Y
0016	U
0017	I
0018	O
0019	P
001a	[
001b	]
001c	Enter
001d	CTRL
001e	A
001f	S
0020	D
0021	F
0022	G
0023	H
0024	J
0025	K
0026	L
0027	;
0028	'
0029	`
002a	LShift
002b	Backslash
002c	Z
002d	X
002e	C
002f	V
0030	B
0031	N
0032	M
0033	,
0034	.
0035	/
0036	RShift
0037	PrtSc
0038	Alt
0039	Space
003a	Caps
003b	F1
003c	F2
003d	F3
003e	F4
003f	F5
0040	F6
0041	F7
0042	F8
0043	F9
0044	F10
0045	Num
0046	Scroll
0047	Home (7)
0048	Up (8)
0049	PgUp (9)
004a	-
004b	Left (4)
004c	Center (5)
004d	Right (6)
004e	+
004f	End (1)
0050	Down (2)
0051	PgDn (3)
0052	Ins
0053	Del
// from direct input docs...
0056	OEM_102    /* <> or \| on RT 102-key keyboard (Non-U.S.) */
0057	F11
0058	F12
0064	F13    /*                     (NEC PC98) */
0065	F14    /*                     (NEC PC98) */
0066	F15    /*                     (NEC PC98) */
0070	KANA    /* (Japanese keyboard)            */
0073	ABNT_C1    /* /? on Brazilian keyboard */
0079	CONVERT    /* (Japanese keyboard)            */
007B	NOCONVERT    /* (Japanese keyboard)            */
007D	YEN    /* (Japanese keyboard)            */
007E	ABNT_C2    /* Numpad . on Brazilian keyboard */
008D	NUMPADEQUALS    /* = on numeric keypad (NEC PC98) */
0090	PREVTRACK    /* Previous Track (DIK_CIRCUMFLEX on Japanese keyboard) */
0091	AT    /*                     (NEC PC98) */
0092	COLON    /*                     (NEC PC98) */
0093	UNDERLINE    /*                     (NEC PC98) */
0094	KANJI    /* (Japanese keyboard)            */
0095	STOP    /*                     (NEC PC98) */
0096	AX    /*                     (Japan AX) */
0097	UNLABELED    /*                        (J3100) */
0099	NEXTTRACK    /* Next Track */
009C	NUMPADENTER    /* Enter on numeric keypad */
009D	RCONTROL
00A0	MUTE    /* Mute */
00A1	CALCULATOR    /* Calculator */
00A2	PLAYPAUSE    /* Play / Pause */
00A4	MEDIASTOP    /* Media Stop */
00AE	VOLUMEDOWN    /* Volume - */
00B0	VOLUMEUP    /* Volume + */
00B2	WEBHOME    /* Web home */
00B3	NUMPADCOMMA    /* , on numeric keypad (NEC PC98) */
00B5	DIVIDE    /* / on numeric keypad */
00B7	SYSRQ
00B8	RMENU    /* right Alt */
00C5	PAUSE    /* Pause */
00C7	HOME    /* Home on arrow keypad */
00C8	UP    /* UpArrow on arrow keypad */
00C9	PRIOR    /* PgUp on arrow keypad */
00CB	LEFT    /* LeftArrow on arrow keypad */
00CD	RIGHT    /* RightArrow on arrow keypad */
00CF	END    /* End on arrow keypad */
00D0	DOWN    /* DownArrow on arrow keypad */
00D1	NEXT    /* PgDn on arrow keypad */
00D2	INSERT    /* Insert on arrow keypad */
00D3	DELETE    /* Delete on arrow keypad */
00DB	LWIN    /* Left Windows key */
00DC	RWIN    /* Right Windows key */
00DD	APPS    /* AppMenu key */
00DE	POWER    /* System Power */
00DF	SLEEP    /* System Sleep */
00E3	WAKE    /* System Wake */
00E5	WEBSEARCH    /* Web Search */
00E6	WEBFAVORITES    /* Web Favorites */
00E7	WEBREFRESH    /* Web Refresh */
00E8	WEBSTOP    /* Web Stop */
00E9	WEBFORWARD    /* Web Forward */
00EA	WEBBACK    /* Web Back */
00EB	MYCOMPUTER    /* My Computer */
00EC	MAIL    /* Mail */
00ED	MEDIASELECT    /* Media Select */
```

and...

```
1101 = left mouse button
1102 = middle mouse button (pressing "scroll")
1103 = right mouse button
```

To try to get all this written in one place.

**Comment by Rex000** [comment]
Where/how do you get the codes for arrow keys? I couldn't find any chart for it. I'm talking about these:

Up = 0148
Down = 0150
Left = 014b
Right = 014d
