### ISSUE TITLE
[Feature request] Resolution selection

### ISSUE THREAD

**Issue by parkerlreed** [sm64pc/sm64pc#225]
**Describe the bug**

On systems using KMS/DRM via SDL2, the resolution doesn't match native. Both full screen and "windowed" are both the default resolution. 

Having a way to set the resolution after going fullscreen (or a config option for fullscreen resolution) would be great. 

**Desktop (please complete the following information):**
 - OS: Arch (both x86_64 and armv7)

**Comment by parkerlreed** [comment]
tty is 1080p

![IMG_20200519_201542](https://user-images.githubusercontent.com/841440/82390809-b4652000-9a0d-11ea-997d-1baf2bcc0a01.jpg)

Game renders at default res 

![IMG_20200519_201609](https://user-images.githubusercontent.com/841440/82390855-d3fc4880-9a0d-11ea-95fe-40940c050bd6.jpg)

**Comment by BailShamber** [comment]
Just pointers for your use case, might help, might not help at all:
using Mir kiosk or Cage wayland compositor with "env SDL_VIDEODRIVER=wayland" might give you what you want with nearly as minimal overhead as DRM.

**Comment by parkerlreed** [comment]
Yeah, I've tried some of the Wayland bits. Works fine (and just as well as bare DRM) but I like to see what all I can run from just the tty.

https://www.reddit.com/r/linux_gaming/comments/av6kcc/documenting_programsgames_that_work_with_the/

I'm more of that I can rather than I should :D

**Comment by newperson1746** [comment]
I wrote some very barebones code to allow passing x and yres through the command line. it's not complicated at all, but i wrote it against the original leaked sm64pc zip. How should I go about submitting it here? It does what you would like:
![Screenshot from 2020-05-31 14-41-24](https://user-images.githubusercontent.com/19787725/83360128-e1d69580-a34c-11ea-8b3b-d68897b9e965.png)

**Comment by parkerlreed** [comment]
I mean it uses GLX through SDL2, yes.

**Comment by parkerlreed** [comment]
Also if you are just modifying the SDL_CreateWindow, that doesn't seem to be enough. 

I hard coded 0, 0, 1920, 1080 and the canvas is properly 1080p but the content is still small.

**Comment by parkerlreed** [comment]
Oh I just realized resolution was added to the config file now (I'm in master)

Testing now

**Comment by parkerlreed** [comment]
Yeah this was added at some point and works great

![IMG_20200531_230411](https://user-images.githubusercontent.com/841440/83372388-22f19880-a393-11ea-986d-7059c37cb5c1.jpg)

**Comment by coltongit** [comment]
Yeah. Nightly's more stable overall than master is atm due to extra bugfixes

**Comment by parkerlreed** [comment]
I meant there was something from nightly merged into master. What commit added the resolution to the config?

**Comment by coltongit** [comment]
idk exactly off the top of my head, but it's been there for a while now

**Comment by parkerlreed** [comment]
Aha thanks.

**Comment by parkerlreed** [comment]
A little over a week now https://github.com/sm64pc/sm64pc/commit/2e8a821fa3c48df20223312df815d4d41b34b1c9#diff-7e10e891b2fd0d70b1f919ee0809149f

**Comment by coltongit** [comment]
You're welcome. Glad it's working for you now
