### ISSUE TITLE
Bug Course 9 Dire, Docks Dire - Star 3

### ISSUE THREAD

**Issue by uper333** [sm64pc/sm64pc#227]
**Describe the bug**
Platforms have to appear to climb them to collect the red coins and they do not appear
Tienen que aparecer unas plataformas para escalar por ellas para recojer las monedas rojas y no aparecen

**To Reproduce**
Go to course 9 star 3
Ir al nivel 9 estrella 3

**Expected behavior**
Let the platforms appear
Que aparezcan las plataformas
https://www.youtube.com/embed/-KPWGGNbwco?start=69

**Screenshots**
https://ibb.co/MDQqsPN

**Desktop (please complete the following information):**
 - OS: windows 10
 Version: compiled with BETTERCAMERA=1 NODRAWINGDISTANCE=1

**Comment by HeavenVolkoff** [comment]
You have to beat Bowser in the Fire Sea, at least once, for the sub to be replaced by the poles. That's how the game logic was coded originally, not a bug.

Source: https://www.mariowiki.com/Pole-Jumping_for_Red_Coins

**Comment by uper333** [comment]
> You have to beat Bowser in the Fire Sea, at least once, for the sub to be replaced by the poles. That's how the game logic was coded originally, not a bug.
> 
> Source: https://www.mariowiki.com/Pole-Jumping_for_Red_Coins

right, I didn't know it worked like that
