### ISSUE TITLE
Nightly build fails after added MingW macros

### ISSUE THREAD

**Issue by dernett** [sm64pc/sm64pc#230]
After commit 0c03280516d4a45f6ce3fb08765d9cd5ff7d9441 the build fails with this error message:
```
In file included from src/audio/data.h:4,
                 from src/audio/data.c:4:
src/audio/internal.h:275:22: error: unknown type name 'ssize_t'
  275 |     /*0x13C, 0x144*/ ssize_t bankDmaRemaining;
      |                      ^~~~~~~
make: *** [Makefile:832: build/us_pc/src/audio/data.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/audio/effects.h:4,
                 from src/audio/effects.c:4:
src/audio/internal.h:275:22: error: unknown type name 'ssize_t'
  275 |     /*0x13C, 0x144*/ ssize_t bankDmaRemaining;
      |                      ^~~~~~~
In file included from src/audio/effects.c:5:
src/audio/load.h:49:67: error: unknown type name 'ssize_t'; did you mean 'size_t'?
   49 | void audio_dma_partial_copy_async(uintptr_t *devAddr, u8 **vAddr, ssize_t *remaining, OSMesgQueue *queue, OSIoMesg *mesg);
      |                                                                   ^~~~~~~
      |                                                                   size_t
make: *** [Makefile:832: build/us_pc/src/audio/effects.o] Error 1
```
System: Linux 64-bit
Compiler: gcc 10.1.0

**Comment by coltongit** [comment]
What Linux flavor are you running exactly?

**Comment by dernett** [comment]
@coltongit Arch Linux

**Comment by Zoltar007** [comment]
@coltongit this also breaks the "OSX_BUILD" option: https://github.com/sm64pc/sm64pc/commit/0c03280516d4a45f6ce3fb08765d9cd5ff7d9441#commitcomment-39306050

**Comment by Tarnadas** [comment]
Same error for me on CentOS 8

**Comment by coltongit** [comment]
I'm working on a fix for this issue as I speak. Just have to make sure everything builds properly still with my fix first.

**Comment by Zoltar007** [comment]
@coltongit Let me know if you need someone to test building for MacOs.

**Comment by coltongit** [comment]
> @coltongit Let me know if you need someone to test building for MacOS.

I might just take you up on that offer. I'll let you know as soon as the PR goes up.

**Comment by fgsfdsfgs** [comment]
In `include/PR/ultratypes.h`, try adding `#include <sys/types.h>` on line 31 and tell me if that fixes it or not.

**Comment by Tarnadas** [comment]
Not sure whether you already found a fix @coltongit , but the suggestion from @fgsfdsfgs almost worked for me except there was another undefined value, which I had to move.
Maybe @Zoltar007 you can try building this on MacOS

**Comment by Zoltar007** [comment]
> Not sure whether you already found a fix @coltongit , but the suggestion from @fgsfdsfgs almost worked for me except there was another undefined value, which I had to move.
> Maybe @Zoltar007 you can try building this on MacOS

Trying now.

**Comment by fgsfdsfgs** [comment]
I had a slightly different fix for this going, but I'll just commit it over yours.

**Comment by coltongit** [comment]
Looks like your fix was much simpler than mine. I'll switch to yours, then

**Comment by Zoltar007** [comment]
I'm not sure if edits send updates, but I've compiled https://github.com/sm64pc/sm64pc/commit/2714708ca916f5e40166407b4a8824248ff2a20c successfully on MacOS.

**Comment by dernett** [comment]
Latest commit fixed the issue for me, so closing this.
