### ISSUE TITLE
Error saving lives  

### ISSUE THREAD

**Issue by uper333** [sm64pc/sm64pc#237]
**Describe the bug**
There is an error when saving the lives you have left, it does not matter how I quit the game and the number of lives I have that when I reopen the game I always have 4 lives
Hay un error al guardar las vidas que te quedan, da igual com salga del juego y la cantidad de vidas que tenga que cuando vuelvo a abrir el juego siempre tengo 4 vidas 

**To Reproduce**
No matter what I do, whenever I leave the game and go back in, I have 4 lives
Da igual lo que haga que siempre que salgo del juego y vuelvo a entrar tengo 4 vidas

**Expected behavior**
Keep the amount of real lives I had left before I left the game
Que guarde la cantidad de vidas reales que me quedaban antes de salir del juego

 - OS: Windows 10
Version: compiled with BETTERCAMERA=1 NODRAWINGDISTANCE=1

**Comment by GateGuy** [comment]
Is it supposed to save lives? The original game always reset you to 4 (actually 5 since 0 counts as a life).

**Comment by uper333** [comment]
> ¿Se supone que salvará vidas? El juego original siempre te reinicia a 4 (en realidad 5, ya que 0 cuenta como una vida).

I did not play the original I did not know, because what is more curious that it is so
thanks
