### ISSUE TITLE
The in-game pause menu crashes when built using Japanese ROM

### ISSUE THREAD

**Issue by yksoft1** [sm64pc/sm64pc#241]
I'm building with nightly head https://github.com/sm64pc/sm64pc/commit/4e7ce3ffbaffe55a4780e4ae9f7a4225c0eebeb4 .

BTW, is there nobody besides me tested the Japanese ROM at all? The font is always incorrect from the  first "leaked" sm64pc source code when built with Japanese ROM.

**Comment by fgsfdsfgs** [comment]
I haven't actually ever tested it. I'll try to figure out what's going on.

**Comment by fgsfdsfgs** [comment]
@yksoft1 Fixes for that and garbled text were just pushed to nightly, try and see if the issue still persists.

**Comment by yksoft1** [comment]
I think commit aaf6eab and 686ea5b had fixed this. Thanks!
