### ISSUE TITLE
Jumbled text European version

### ISSUE THREAD

**Issue by currall** [sm64pc/sm64pc#246]
On the European version most text is random characters, including the pc options menu, signs and speaking to in-game characters (e.g. toads, pink bombs etc.)

This only happens when compiled with the European version (I don't speak Japanese so it may happen there aswell)
![Screenshot (110)](https://user-images.githubusercontent.com/29579820/82590372-80b50200-9b95-11ea-93b8-d8919898fdff.png)
![Screenshot (111)](https://user-images.githubusercontent.com/29579820/82590377-827ec580-9b95-11ea-8cb0-e10ab3d5ba06.png)
![Screenshot (112)](https://user-images.githubusercontent.com/29579820/82590380-83175c00-9b95-11ea-8a40-7eeb152955b6.png)
![Screenshot (109)](https://user-images.githubusercontent.com/29579820/82590381-83aff280-9b95-11ea-9010-2b65184fd861.png)

**Comment by fgsfdsfgs** [comment]
@currall A fix for this has just been pushed to nightly. Try it out and see if the issue persists.

**Comment by currall** [comment]
> @currall A fix for this has just been pushed to nightly. Try it out and see if the issue persists.

yeah, latest nightly fixed the text.
