### ISSUE TITLE
Vulkan support?

### ISSUE THREAD

**Issue by wantija** [sm64pc/sm64pc#25]
Title, any chance for a Vulkan renderer?

**Comment by vrmiguel** [comment]
Unfortunately there's no work in progress for that yet.

**Comment by Titaniumtown** [comment]
Would be cool, I know this project is not even near to that point yet, but it would be neat.

**Comment by urherenow** [comment]
Since emulation is more or less out of the picture, this has no speed issues whatsoever, so what would the benefits be? Would it allow graphics drivers to take over things like FSAA and such?

**Comment by citrus3301** [comment]
> Title, any chance for a Vulkan renderer?

why would we need that though? there is no emulation slowdown, its an old ass game, vulkan would do nothing except make this inaccessible for more platforms like web, keeping it strictly opengl would not hurt performance at all and makes it more accessible
