### ISSUE TITLE
Why we disable optimization only for US and JP ROM editions?

### ISSUE THREAD

**Issue by yksoft1** [sm64pc/sm64pc#250]
From Makefile:
```
ifeq ($(VERSION),eu)
  OPT_FLAGS := -O2
else
ifeq ($(VERSION),sh)
  OPT_FLAGS := -O2
else
  OPT_FLAGS := -g
endif
endif
```

I think the original intent of this must be that "Disable optimization for unstable European and Shindo version of the ROM". But the implementation is the opposite.

**Comment by fgsfdsfgs** [comment]
Nah, thos

**Comment by selurvedu** [comment]
> I think the original intent of this must be that "Disable optimization for unstable European and Shindo version of the ROM". But the implementation is the opposite.

Te supposed reason for disabled optimisation is well explained here: https://youtu.be/NKlbE2eROC0?t=222

**Comment by yksoft1** [comment]
> Nah, this is because the decompilation produces matching ROMs if the optimization flags are set like that. Of course there's little reason to do it on PC, aside from the "unstable" thing.

I tried to use -O2 on us build. The produced executable crashes upon enter any stage.
I think it could be the real reason why they disabled optimization.

**Comment by coltongit** [comment]
O2 works perfectly fine in the original N64 US release @yksoft1

**Comment by fgsfdsfgs** [comment]
Works on my machine.

**Comment by yksoft1** [comment]
Seems there is some commit in nightly that fixed something.
