### ISSUE TITLE
[Feature request]: The ability to compile rom hacks

### ISSUE THREAD

**Issue by Gl4dius** [sm64pc/sm64pc#254]
Hi,

I just came up with this idea while playing the vanilla game a bit: What if I use a rom hack of Super Mario 64 (such as Star Road or Super Mario 74) as the baserom instead of the vanilla game? Sadly, and I guess unsurprisingly, the build process didn't work. If you guys are able to implement that in the future, that would be a godsend to me.

**Comment by fgsfdsfgs** [comment]
That would require you to port any custom code, text, models and levels the romhack might have to SM64PC first and then change/add assets in `assets.json`.
While loading custom resources such as graphics, sounds, text and even levels and models might be possible to do at runtime, you can't just load code from the ROM.

**Comment by Patjwmiller** [comment]
I was just typing all of what fgsfdsfgs said. Elaborating on what was said though, you might just have to hope that romhack creators do the pc port along with their actual rom.

**Comment by fgsfdsfgs** [comment]
Keep in mind that while sounds and graphics are extracted and converted automatically, pretty much everything else had at least some degree of manual work done to it by the original n64decomp team, so we don't have a tool that can just magically decompile a ROM, extract levels and models and automatically find all the addresses for assets and whatnot, so right now this would indeed require someone (presumably the author of the hack) to convert it manually.

**Comment by Gl4dius** [comment]
Alright, that all makes sense to me. Thanks for the help!
