### ISSUE TITLE
It does work on WSL

### ISSUE THREAD

**Issue by kterhorst** [sm64pc/sm64pc#258]
In the wiki I read:

> Do not attempt to use this guide to compile Windows binaries under WSL or Linux. It will not work.

Just to let you know, using the guide to produce _Windows_ binaries will fail indeed but it is possible to run it on WSL (1 in my case). I used the Pengwin WSL distro and the X410 X-Server and it ran flawlessly. [No product placement; I think free products should do the trick as well].

**Comment by IvanDSM** [comment]
Well, the warning is about building *Windows* binaries so it still stands.
