### ISSUE TITLE
Please allow assigning non-keyboard keycodes for stick controls...

### ISSUE THREAD

**Issue by enigma9o7** [sm64pc/sm64pc#260]
I know, I already reported this, this is bad behavior or something.  Maybe I'll get banned from reporting issues on github, I dunno the rules.  But it's annoying me.  On my main PC, I can't even play with my gamepad.

I just successfully installed this on my kids ancient pc, and the controller worked automatically.    Just like my main PC, a basic snes style controller connected via USB, although I guess it's special cuz its 8bitdo, and I only have some generic Mafiiti.

What I thought was weird was when I went to look at the controller settings in game or the cfg file, it didnt even have it assigned for stick besides the keyboard.  Somehow it magically works without being assigned.

That's not fair.

My controller works fine, in sdl2 games like supertux, in web-based testers someone else linked elsewhere, it works, why can't I play this game on my laptop with cheap controller!

**Comment by IvanDSM** [comment]
Did you use the same build on both computers?

**Comment by enigma9o7** [comment]
Yes.  Same build.   We haven't had any new commits in past day or two. Although my kids pc, as I mentioned, is ancient, 32bit and had to use gl1.

I bet that controller would work fine on this PC. Haven't tried.  Just post online to annoy ppl.

**Comment by IvanDSM** [comment]
Wait, you didn't use the same controller on both computers?

**Comment by enigma9o7** [comment]
No.  I didn't use the same mouse or keyboard either.  Amazingly enough, every computer in my household has its own input devices.

**Comment by IvanDSM** [comment]
Although I appreciate that I've given you some inspiration (and would be looking forward to the result!), you should test your son's controller on your PC. If it has the same issue, then I think it's worth taking a look into it.

**Comment by fgsfdsfgs** [comment]
The left stick of any SDL2 compatible controller is automatically bound to the N64 stick, while the right stick is bound to the C buttons. The stick binds in the config or menu right now are only for the keyboard.

**Comment by enigma9o7** [comment]
Yeah it just doesn't work right on all controllers that don't have a stick.  Both controllers I mentioned are SNES style - meaning dpad only, no stick - with the same: 4 buttons +select/start and shoulders, both work on other SDL2 games just fine.  But smpc64 automatically assigned the 8bitdo d-pad to stick controls without anything in the .cfg file, whereas the mafiti nope, nothing from dpad, and assigning it manually to stick doesn't work.   (I can assign it to the camera, as mentioned in my previous issue which is the same as this one.)

**Comment by enigma9o7** [comment]
So a recent nightly fix makes it no longer revert optimizations.  That is one step better.

But still want to be able to assign stick controls.  Even on my 8bitdo that assigns movement to dpad automatically, I just had an idea to try playing by making the dpad the camera movement and making one of my spare buttons as stick up, and using it like a gas pedal, with analog camera enabled.  But can't do that cuz still can't customize!

**Comment by fgsfdsfgs** [comment]
Check 8b386a2175dfa0f625d46056157ec94430198ec5, might be working now.

**Comment by enigma9o7** [comment]
Excellent!  Works for me!
