### ISSUE TITLE
Add Fedora compilation to wiki.

### ISSUE THREAD

**Issue by LucasPB710** [sm64pc/sm64pc#262]
Please, add ```sudo dnf install make gcc python3 audiofile-devel glew-devel SDL2-devel```  to the wiki. 

It would be great and easier for Fedora users to install the dependencies.

**Comment by zerocloude** [comment]
@LucasPB710, with this list of dependencies Fedora users can build both 32-bit and 64-bit executables?

**Comment by LucasPB710** [comment]
> @LucasPB710, with this list of dependencies Fedora users can build both 32-bit and 64-bit executables?

For 64-bit yes, but for 32-bits i guess they can use:
```
sudo dnf install python3.i686 audiofile-devel.i686 glew-devel.i686 SDL2-devel.i686
```

**Comment by enigma9o7** [comment]
The most other useful thing to add to linux wiki, in general, is all the possible build switches.  Without digging into comments and commits and discord etc I would have not realized the possibilities like 
BETTERCAMERA=1 NODRAWINGDISTANCE=1 TEXTURE_FIX=1 which most people want to apply, and LEGACY_GL=1 for those on old hardware without opengl2.

**Comment by enigma9o7** [comment]
Those 32bit vs 64bit is only for if you want to build 32-bit on 64-bit anyway, and as most people aren't packaging it for others, that's really not important.  I build on 32-bit ubuntu using the 64-bit instructions, cuz ubuntu knows if yer runing 32-bit to get 32-bit packages.  The only need for that is if you're running 64-bit and want 32-bit packages to make a 32-bit binary from 64-bit system, which is not the normal case.

**Comment by LucasPB710** [comment]
> The most other useful thing to add to linux wiki, in general, is all the possible build switches.  Without digging into comments and commits and discord etc I would have not realized the possibilities like 
> BETTERCAMERA=1 NODRAWINGDISTANCE=1 TEXTURE_FIX=1 which most people want to apply, and LEGACY_GL=1 for those on old hardware without opengl2.

That's true, it would be great if they add these options to the wiki too.

**Comment by vrmiguel** [comment]
@LucasPB710 @enigma9o7 

Done! Thanks for the suggestions.
