### ISSUE TITLE
Can't compile nightly in Windows

### ISSUE THREAD

**Issue by MagitekArmor** [sm64pc/sm64pc#265]
I can compile the master branch using the tutorial, and even the nightly a couple days before, but now I get this error:

sdk-tools/tabledesign/tabledesign.c:5:10: fatal error: audiofile.h: No such file or directory

**Comment by Sunoo** [comment]
Copy the files from /tools/include to /include and it should compile for you.

**Comment by fgsfdsfgs** [comment]
I accidentally deleted `-Iinclude` from the `CFLAGS` in `tools/Makefile`. If you add it back in, it should work.

**Comment by MagitekArmor** [comment]
@fgsfdsfgs That worked, thanks!

**Comment by fgsfdsfgs** [comment]
Try now, I pushed that change in f8139cce.
