### ISSUE TITLE
(Question) Is the liner filter like the 3-point filter of N64?

### ISSUE THREAD

**Issue by MagitekArmor** [sm64pc/sm64pc#266]
N64 has a different filter:
. Bilinear:
![4wwtS6o](https://user-images.githubusercontent.com/65924409/82844845-727a2500-9eb8-11ea-9481-9735141d0cf8.png)

.3-Point:
![6z3L7Rh](https://user-images.githubusercontent.com/65924409/82844862-83c33180-9eb8-11ea-9ffe-868da598fd66.png)

http://filthypants.blogspot.com/2014/12/n64-3-point-texture-filtering-in.html
http://www.emutalk.net/threads/54215-emulating-nintendo-64-3-sample-bilinear-filtering-using-shaders

So, is it already implemented or there are any plans to?

**Comment by fgsfdsfgs** [comment]
Currently it's toggleable between nearest and linear. There are plans to add three-point as well, I have a [branch](https://github.com/fgsfdsfgs/sm64pc/tree/threepoint) that has it implemented, but it's very out of date.

**Comment by KainXVIII** [comment]
Three-point and linear filter looks virtually the same (seems like its not working as intended?)

**Comment by fgsfdsfgs** [comment]
Restart the game after switching from/to three-point.

**Comment by KainXVIII** [comment]
> Restart the game after switching from/to three-point.

Now i see, thanks!
