### ISSUE TITLE
Joystick Deadzone Needed?

### ISSUE THREAD

**Issue by Sunoo** [sm64pc/sm64pc#271]
I’ve been playing with an Xbox 360 controller on Windows, and it mostly works great, but the left joystick seems to constantly be pointed very slightly down and left. I don’t encounter this with the same controller and any other game, so it seems to be specific to this. My best guess is that it needs to allow for a slight deadzone before registering an input, but doesn’t currently. Alternatively, maybe the center position is misdefined somewhere?

**Comment by fgsfdsfgs** [comment]
There's a deadzone but it's hardcoded and small. Probably should add a setting.

**Comment by coltongit** [comment]
options menu should allow for redefining the deadzone for sure

**Comment by GateGuy** [comment]
#278

**Comment by Sunoo** [comment]
Awesome, I'll have to give that a shot when I have a second.

**Comment by Sunoo** [comment]
The new setting works perfectly, thanks!

**Comment by GateGuy** [comment]
No problem!
