### ISSUE TITLE
How do you enable "Better camera"

### ISSUE THREAD

**Issue by Evanator05** [sm64pc/sm64pc#279]
I tried putting in in sm64config.txt, it did'nt do anything, I tried putting in in the launch options like you do with cheats, nothing.

**Comment by parkerlreed** [comment]
It has to be built with that. During the make step add BETTERCAMERA=1 to that line

**Comment by Evanator05** [comment]
thanks

**Comment by Evanator05** [comment]
what make one, the first second or third

**Comment by parkerlreed** [comment]
I'm not sure what instructions you are referencing. It would be on the make that takes the longest.
