### ISSUE TITLE
Bug: Title Screen has no Mario Hand Cursor

### ISSUE THREAD

**Issue by ecumber** [sm64pc/sm64pc#28]
**Describe the bug**
The title screen does not have the Mario hand cursor that appears in the original. It still works, but there is no graphic that displays where it is.

**To Reproduce**
Press A on the title screen.

**Expected behavior**
There should be a Mario hand cursor on the title screen.

**Desktop (please complete the following information):**
 - OS: Windows (x86 build)

**Screenshots**
![image](https://user-images.githubusercontent.com/14047530/81482982-a7ffec80-91ef-11ea-81a9-8ff16179d8f9.png)
![image](https://user-images.githubusercontent.com/14047530/81482983-adf5cd80-91ef-11ea-8595-54091d97b421.png)

**Comment by Patjwmiller** [comment]
It's a fullscreen only bug typically. If you alter between default window-size and fullscreen you will see.

**Comment by rainyuu** [comment]
the issue here is the fact that the cursor is offset by the aspect ratio, you can see it if you resize the game to be wider from its default 4:3 window.

**Comment by Xenthio** [comment]
forcing it back to 0, 0 every time the window is resized should work.

**Comment by Xenthio** [comment]
oh nvm its offset in the sprite. I'm not sure how much this port sticks to the original code but you still might be able to work around that by reloading the sprite or something.
