### ISSUE TITLE
baserom.eu.z64 has the wrong has !

### ISSUE THREAD

**Issue by RafterFD** [sm64pc/sm64pc#282]
I modified the "makefile" to be able to use the EU version but, when I introduce the "make" command in /sm64pc this happen

![image](https://user-images.githubusercontent.com/61575514/83342049-134d5380-a2b0-11ea-809b-c734b247f4ba.png)

 It doesn't work either if I change again the "makefile" and use the US version

I have to download the roms in other page ??

**Comment by fgsfdsfgs** [comment]
Please refrain from posting links to copyrighted shit on this public repo.
Have you considered that perhaps the ROM you got is wrong and not the hash? Because I got a ROM that works just fine.

**Comment by RafterFD** [comment]
Oh, sorry for the link, it was only to show where I had got the rom xD
I'll try to get the ROM on another page and see if it works

**Comment by RafterFD** [comment]
Well... I didn't find the EU rom :'v But the US version works very good! Thanks < 3

**Comment by berarma** [comment]
There are different hashes because some dumps have reversed byte order. Some dumps use big-endian while others use little-endian 16bit words.

It's easy switching from one dump format to the other with the following command available on GNU/Linux:
`objcopy -I binary -O binary --reverse-bytes=2 baserom.eu.z64`

**Comment by rawr51919** [comment]
> There are different hashes because some dumps have reversed byte order. Some dumps use big-endian while others use little-endian 16bit words.
> 
> It's easy switching from one dump format to the other with the following command available on GNU/Linux:
> `objcopy -I binary -O binary --reverse-bytes=2 baserom.eu.z64`

Wonder if this can be integrated into the makefile, to allow for little-endian z64 ROM usage
