### ISSUE TITLE
(Question) New save file/config location?

### ISSUE THREAD

**Issue by GateGuy** [sm64pc/sm64pc#291]
It looks like the save and config file locations aren't kept with the executable anymore. Where are they now?

**Comment by parkerlreed** [comment]
https://github.com/sm64pc/sm64pc/commit/1873f7aba57513d6ea5cb2577e827be2cd4b4397

**Comment by GateGuy** [comment]
Thanks. For anyone using Windows who wants to know, try `C:\Users\YOURNAME\AppData\Roaming\sm64pc`

**Comment by jordy-u** [comment]
For Linux (Ubuntu at least) it's in:
`/home/<user>/.local/share/sm64pc`
It was not obvious from the mentioned commit, IMO.

**Comment by fgsfdsfgs** [comment]
Yeah, that's because at the time I didn't know where exactly SDL would put that.
