### ISSUE TITLE
Crash when launching the game through a batch file with EXTERNAL_DATA enabled

### ISSUE THREAD

**Issue by Bitl** [sm64pc/sm64pc#294]
When launching the game using the "EXTERNAL_DATA" compiler switch using a batch file, the game will crash immediately on launch.

here's the batch file in question:
``@echo off
start sm64.us.f3dex2e.exe --configfile "sm64config.txt" --datapath "%CD%/data" --savepath "%CD%/saves" --cheats
exit``

All the "res" data is in the same directory.

**Comment by fgsfdsfgs** [comment]
`--datapath` has to point to the `res` folder. So if you got the `res` folder *inside* `data`, it would be `"%CD%/data/res`.
If you don't, then that's concerning. Please run it from the MSYS terminal and tell me what it prints out upon crashing.

**Comment by Bitl** [comment]
AH, it all works now. Thanks!
