### ISSUE TITLE
No audio for EU version (macOS build)

### ISSUE THREAD

**Issue by WeedyWeedSmoker** [sm64pc/sm64pc#296]
**Describe the bug**
There is no audio after compiling the macOS version with the EU ROM (md5 45676429ef6b90e65b517129b700308e)
The US version (md5 20b854b239203baf6c961b850a4a51a2) works fine with audio…

**Desktop (please complete the following information):**
 - OS: macOS 10.13 and 10.14 tested
 - Version nightly branch 88b044bd76e4e3a8370a2cb3c9a0ad26ce65017a

**Comment by WeedyWeedSmoker** [comment]
Sorry, I didn't see this is a known issue in the Wiki…

Should I close it?

**Comment by fgsfdsfgs** [comment]
Yeah, there's already an issue (#68) about this, so I'll close this one.
