### ISSUE TITLE
Switch pro controller doesn't work on Linux

### ISSUE THREAD

**Issue by bernharl** [sm64pc/sm64pc#298]
**Describe the bug**
The controller used to work via Steam, but I switched to using a standalone driver as it supports rumble for some emulators: 
https://github.com/nicman23/dkms-hid-nintendo
I'm also using this userspace driver:
https://github.com/DanielOgorchock/joycond

**To Reproduce**
Use these drivers without Steam running (Steam conflicts with them)

**Expected behavior**
Game controls out of the box like with Steam

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: Linux kernel 5.4.43-1

**Additional context**
Maybe I'm misunderstanding something and it just needs to be configured, I would appreciate any help I could get!

**Comment by parkerlreed** [comment]
Yeah you need to configure it.

https://generalarcade.com/gamepadtool/

Map your controller with that and then take the string it gives you and save it to a gamecontrollerdb.txt file in the same folder as your sm64 config and save file.

The reason it doesn't work out of the box is you are using new drivers and the controller just hasn't been submitted to upstream SDL yet.

**Comment by parkerlreed** [comment]
Any luck?

**Comment by bernharl** [comment]
Thank you for the quick reply and no, I haven't tried it yet as I am in the middle of a home exam :) 

I'll try later today and let you know how it goes!

**Comment by bernharl** [comment]
It worked wonders, thank you!
