### ISSUE TITLE
Can't build for windows on arch

### ISSUE THREAD

**Issue by j0w0** [sm64pc/sm64pc#3]
dependencies probably needed that aren't listed because while compiling it spits out this error
know what dependencies are needed? i got all the packages listed in the readme & the output seems kinda confusing (i cant find most of these packages in repositories and the ones i can find i installed & get the same output)
```
Usage: /usr/bin/sdl2-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs]
/usr/bin/ld: cannot find -lglew32
/usr/bin/ld: cannot find -lglu32
/usr/bin/ld: cannot find -lsetupapi
/usr/bin/ld: cannot find -ldinput8
/usr/bin/ld: cannot find -luser32
/usr/bin/ld: cannot find -lgdi32
/usr/bin/ld: cannot find -limm32
/usr/bin/ld: cannot find -lole32
/usr/bin/ld: cannot find -loleaut32
/usr/bin/ld: cannot find -lshell32
/usr/bin/ld: cannot find -lwinmm
/usr/bin/ld: cannot find -lversion
/usr/bin/ld: cannot find -luuid
/usr/bin/ld: cannot find -lopengl32
collect2: error: ld returned 1 exit status
```

**Comment by Jan200101** [comment]
you cannot compile for Windows using a linux toolchain
install the MinGW toolchain or setup [MXE](MXE.cc)

**Comment by j0w0** [comment]
ah i see thanks for help
