### ISSUE TITLE
No shell box in lethal lava land

### ISSUE THREAD

**Issue by mrepicgamer** [sm64pc/sm64pc#307]
**Describe the bug**
At the start of lethal lava land there should be a box there containing a green shell. In the port there isn't.
**To Reproduce**
1. Go to
lethal lava land, near where the shell box would usually be and the sign.
2. See error
no shell box to be found

**Expected behavior**
I expected there to be a shell box which when broken makes a green shell that can be ridden on.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version [latest nightly as of writing, with the 60fps,hd coin and hd mario models (though the bug is probably there without those patches)]

![bug](https://user-images.githubusercontent.com/41759402/83945315-bf87c080-a801-11ea-8586-9fb2edc54212.PNG)

If you try emulating the game the shell box will be there, too lazy to post proof.

**Comment by mrepicgamer** [comment]
oops its there in later missions

**Comment by coltongit** [comment]
Closed since this shell does in fact appear when it's supposed to. Only when mission 6 is selected does it appear.

**Comment by mrepicgamer** [comment]
Yeah I thought it was a bug sorry
