### ISSUE TITLE
Redundancy Cleanup

### ISSUE THREAD

**Issue by NobodyYouKnow01** [sm64pc/sm64pc#312]
**Describe the bug**
The directory for the entire project has duplicate folders, everywhere. Whenever cleanup is next on the list, this is where to start...

**To Reproduce**
1. Go to C:/sm64pc_nightly
2. Use the search bar and type the name of a known folder (e.g. textures, src, include)
3. Three, if not more folders appear for what you're looking for.

**Expected behavior**
Expected the entire project to be in one place. It saves space on the computer, and it makes things like replacing a texture less of a chore for someone who doesn't know which folder the game depends on, and debug less of a hassle when the pointer could literally be anywhere.

**Screenshots**
<img width="470" alt="textures_dir" src="https://user-images.githubusercontent.com/53800234/83961144-f091e080-a855-11ea-9401-2c946a02e5f9.png">
<img width="524" alt="src_dir" src="https://user-images.githubusercontent.com/53800234/83961145-f2f43a80-a855-11ea-9dcb-8652ca1dc480.png">
<img width="509" alt="levels_dir" src="https://user-images.githubusercontent.com/53800234/83961147-f5ef2b00-a855-11ea-8978-dadde774a402.png">

**Desktop**
 - OS: Windows 10 Home
 - Browser: Chrome (build is a binary though...)
 - Version (of Chrome? 83.0.4103.97) (Of Windows? 1809)

**Smartphone**
Oh, we compiled for phones? Cool! I'm not using phone currently though...

**Additional context**
na

**Comment by vrmiguel** [comment]
>  debug less of a hassle when the pointer could literally be anywhere.

What? It doesn't work like that. Aside from `src` (by itself a common folder name on computing), all of the examples you gave are duplicates created by building, that is, within the `build` folder. The project itself doesn't really have a glaring problem of folder redundancy.


The reason these duplicates exist is more of a pro than it is a con, as you're able to easily tell exactly which `.c` files generated the `.d` and `.o` files these duplicates contain, for example.


If that really grinds your gears, you can remove the executable out of there and delete the entire `build` folder.

**Comment by vrmiguel** [comment]
Closed by inactivity. Reopen if necessary.
