### ISSUE TITLE
[Feature Request] Customizable stick deadzone

### ISSUE THREAD

**Issue by NeoKat75** [sm64pc/sm64pc#318]
My Pro Controller has a *very* slight drift that doesn't have impact in other games, but causes Mario to very slowly walk in a direction in this. I think a small deadzone could fix this.

**Comment by Plynthus** [comment]
If your build is is from May 29 or later, then it should already be there:
![Screenshot (37)](https://user-images.githubusercontent.com/65557157/84175361-8ca32e00-aa88-11ea-808a-8975fc87b5f6.png)

**Comment by coltongit** [comment]
It is indeed in there. At least the latest nightly has it. Should probably move to have this be closed as this is an issue that's already been dealt with.
