### ISSUE TITLE
After the first Bowser demo, no more demos play

### ISSUE THREAD

**Issue by newperson1746** [sm64pc/sm64pc#339]
**Describe the bug**
The game should play several more demos of Mario, like the Whomp's Fortress one, after Mario's head begins to fall asleep. The game does not do this; it simply loops the sleeping animation several more times instead of fading out to the Whomp's Fortress demo. 

I suspect this may be related to the "press start to play" sound not playing and thus messing up the trigger for the next demos; if it is, please delete this issue and move the discussion of this bug to that issue.

[Video: Intended behavior on original hardware](https://www.youtube.com/watch?v=LUojnExgazM&t=95s)

**To Reproduce**
1. Compile game with US rom in proper location
2. Run compiled executable
3. Stay on the Mario head title screen, after the first Bowser demo when Mario's head starts falling asleep

**Expected behavior**
Whomp's Fortress, Dire Dire Docks, etc. demos play

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 on Wayland 
- latest nightly as of Jun 13 10:39 EDT compiled with: TEXTURE_FIX=1 NODRAWINGDISTANCE=1 VERSION=US

Is this some kind of odd bug specific to my configuration? I can't be the first one to have noticed this, right?

**Comment by fgsfdsfgs** [comment]
That did not used to happen. Right now I can confirm it though.

**Comment by newperson1746** [comment]
Hmm. I do suspect the "press start to play" sound effect not playing as the source of this issue. A lot of actions in the game code depend on the triggering of certain sound effects; a timer that starts the next demo might be one of them.

**Comment by newperson1746** [comment]
closed in favor of #342 where i grouped all the bugs together in one place
