### ISSUE TITLE
Testing Branch

### ISSUE THREAD

**Issue by bpvarsity** [sm64pc/sm64pc#34]
So I compiled the testing branch and ran the exe but I do not see the new camera features, mouse support or new menu. Did I do something wrong?

**Comment by vrmiguel** [comment]
Are you sure you cloned the testing branch? It should have "Super Mario 64 - testing" title bar.

**Comment by bpvarsity** [comment]
Yep that was my first guess that I got the wrong one but I downloaded it again and still just the normal version. I'll try again tomorrow on my other computer.

**Comment by vrmiguel** [comment]
Wait, so it does have the "Super Mario 64 - testing" title? I'm not sure I understand what you said.

**Comment by bpvarsity** [comment]
Yes it does

**Comment by vrmiguel** [comment]
Right. And your in-game menu looks like [this](
![image](https://user-images.githubusercontent.com/36349314/81491251-a1f72380-9262-11ea-9714-1a23bb257c45.png), with the "R: Options" on top right?

**Comment by bpvarsity** [comment]
I just redid it and I see the R options now. What key do I press to access it? I tried the obvious R key and many others and didn't see anything

**Comment by vrmiguel** [comment]
Right shift on keyboard or R1/R2 on controllers.

**Comment by bpvarsity** [comment]
Cool that works. Sorry about that. Compiling at too late of an hour!

**Comment by vrmiguel** [comment]
Thankfully it worked out :) 
Enjoy
