### ISSUE TITLE
Build fails on Windows (MinGW64)

### ISSUE THREAD

**Issue by SciFI101** [sm64pc/sm64pc#343]
I'm following the steps in the wiki to compile it from source, and I've run into an error

`
$ make TEXTURE_FIX=1 EXT_OPTIONS_MENU=1 DISCORDRPC=1 BETTERCAMERA=1 NODRAWINGDISTANCE=1

make: Entering directory '/c/Users/haven/Documents/Projects/Code/sm64pc/tools'
gcc -Llib -Iinclude -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  sdk-tools/tabledesign/codebook.c sdk-tools/tabledesign/estimate.c sdk-tools/tabledesign/print.c sdk-tools/tabledesign/tabledesign.c -lm -o tabledesign -Wno-uninitialized -laudiofile
C:/dev/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -laudiofile
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:54: tabledesign] Error 1
make: Leaving directory '/c/Users/haven/Documents/Projects/Code/sm64pc/tools'
Makefile:187: *** Failed to build tools.  Stop.
`

I'm compiling on and for Win10 64 bit

**Comment by fgsfdsfgs** [comment]
Are you building the master branch?

**Comment by SciFI101** [comment]
Yes sir

**Comment by fgsfdsfgs** [comment]
Well, those instructions are actually for nightly. I must have forgotten to mention that. If you want to build master for some reason, you'll have to perform an additional step of compiling libaudiofile.

**Comment by SciFI101** [comment]
oops, how would one go about doing that?

**Comment by fgsfdsfgs** [comment]
Keep in mind that master doesn't have `DISCORDRPC`.
The instructions on how to build libaudiofile were in the [previous revision](https://github.com/sm64pc/sm64pc/wiki/Compiling-on-Windows/aa7359975cac549b13a8266b55951941d3c3fa12) of the wiki page.

**Comment by SciFI101** [comment]
Thank you much, sir, that worked a treat! Maybe this'll be my entry point into the world of C/C++ development.

**Comment by fgsfdsfgs** [comment]
Alright, issue resolved then.
