### ISSUE TITLE
Cannot make on Windows 64 Bit

### ISSUE THREAD

**Issue by TheBasementNerd** [sm64pc/sm64pc#344]
make: gcc: No such file or directory
make: *** [Makefile:54: n64graphics] Error 127
Traceback (most recent call last):
  File "./extract_assets.py", line 281, in <module>
    main()
  File "./extract_assets.py", line 156, in main
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:180: *** Failed to extract assets.  Stop.

Ran all the instructions exactly as stated, for both SM64PC and MSYS2, however trying to run make in the SM64PC base folder returns this error

**Comment by fgsfdsfgs** [comment]
Did you run the MINGW64 prompt of MSYS2 or just the MSYS2 prompt? You seem to be lacking GCC in your `PATH`, which means you either skipped installing it (the `pacman` line) or you ran the wrong prompt.

**Comment by TheBasementNerd** [comment]
It was that I was running from the prompt I used to build all of MSYS2, and I hadn't opened specifically the 64bit exe that was located in C:\dev\msys64

**Comment by fgsfdsfgs** [comment]
So is it working now?

**Comment by TheBasementNerd** [comment]
Yea, its working now. Although I'm unable to run make with a certain mod, I was able to make with a mod to replace the Mario model with a high def version, so all parts are working correctly
