### ISSUE TITLE
Japanese Rom does not build on newest nightly

### ISSUE THREAD

**Issue by danielh05** [sm64pc/sm64pc#346]
When building I get this error:
src/game/options_menu.c:89:7: error: 'TEXT_OPT_MUSIC_VOLUME' undeclared here (not in a function); did you mean 'TEXT_OPT_MVOLUME'?
   89 |     { TEXT_OPT_MUSIC_VOLUME },
      |       ^~~~~~~~~~~~~~~~~~~~~
      |       TEXT_OPT_MVOLUME
src/game/options_menu.c:90:7: error: 'TEXT_OPT_SFX_VOLUME' undeclared here (not in a function); did you mean 'TEXT_OPT_MVOLUME'?
   90 |     { TEXT_OPT_SFX_VOLUME },
      |       ^~~~~~~~~~~~~~~~~~~
      |       TEXT_OPT_MVOLUME
src/game/options_menu.c:91:7: error: 'TEXT_OPT_ENV_VOLUME' undeclared here (not in a function); did you mean 'TEXT_OPT_MVOLUME'?
   91 |     { TEXT_OPT_ENV_VOLUME },
      |       ^~~~~~~~~~~~~~~~~~~
      |       TEXT_OPT_MVOLUME

**Comment by danielh05** [comment]
Only fix that I know for this currently is to modify the options menu file and just rename all of that to "TEXT_OPT_MVOLUME".

**Comment by fgsfdsfgs** [comment]
Should be fixed now.

**Comment by danielh05** [comment]
Yeah seems to work now. Closing the issue.
