### ISSUE TITLE
compiling on linux ubuntu 18.04 is broken

### ISSUE THREAD

**Issue by ArghKevin** [sm64pc/sm64pc#348]
**Describe the bug**
compiling using a US sm64 rom under vanilla build options fails consistently on ubuntu 18.04

**To Reproduce**
build the game after supplying an appropiate us sm64 rom on ubuntu 18.04, possibly other linux distros aswell

**Expected behavior**
after a large chunk of the compilation running smoothly, the following error occurs:

make: Entering directory '/home/777/gms/sm64pc/tools'
gcc -Llib -Iinclude -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  n64graphics_ci_dir/n64graphics_ci.c n64graphics_ci_dir/exoquant/exoquant.c n64graphics_ci_dir/utils.c -lm -o n64graphics_ci -O2 
gcc -Llib -Iinclude -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  n64cksum.c libmio0.c libsm64.c utils.c -lm -o n64cksum 
gcc -Llib -Iinclude -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  textconv.c utf8.c hashtable.c -lm -o textconv 
gcc -Llib -Iinclude -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  patch_libultra_math.c -lm -o patch_libultra_math 
gcc -Llib -Iinclude -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  iplfontutil.c -lm -o iplfontutil -O2 
gcc -Llib -Iinclude -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  aiff_extract_codebook.c -lm -o aiff_extract_codebook 
gcc -Llib -Iinclude -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  sdk-tools/adpcm/vadpcm_enc.c sdk-tools/adpcm/vpredictor.c sdk-tools/adpcm/quant.c sdk-tools/adpcm/util.c sdk-tools/adpcm/vencode.c -lm -o vadpcm_enc -Wno-unused-result -Wno-uninitialized -Wno-sign-compare -Wno-absolute-value
gcc -Llib -Iinclude -I . -Wall -Wextra -Wno-unused-parameter  -pedantic -std=c99 -O3 -s  sdk-tools/tabledesign/codebook.c sdk-tools/tabledesign/estimate.c sdk-tools/tabledesign/print.c sdk-tools/tabledesign/tabledesign.c -lm -o tabledesign -Wno-uninitialized -laudiofile
/usr/bin/ld: cannot find -laudiofile
collect2: error: ld returned 1 exit status
Makefile:54: recipe for target 'tabledesign' failed
make: *** [tabledesign] Error 1
make: Leaving directory '/home/777/gms/sm64pc/tools'
Makefile:187: *** Failed to build tools.  Stop.

**Screenshots**
a screenshot of my terminal during the compilation:
![Screenshot_2020-06-17_08-43-35](https://user-images.githubusercontent.com/50538286/84876406-b6ef7f80-b076-11ea-9073-68c5562cfff2.png)

**Desktop (please complete the following information):**
 - OS: ubuntu linux 18.04

**Additional context**
havn't tested this error thoroughly, only 4 times, exclusively on ubuntu 18.04

**Comment by fgsfdsfgs** [comment]
You're compiling master, right?
master requires you to have libaudiofile either installed system-wide or built manually from the source included in `tools/audiofile-0.3.6`. The build instructions in the wiki are for the nightly branch, which I should probably clarify more.
On Ubuntu you can get libaudiofile by executing `sudo apt-get install libaudiofile-dev`.

**Comment by ArghKevin** [comment]
@fgsfdsfgs that worked, thanks. the wiki doesnt clarify for which branch to do what nor does it mention that file as a dependency(i checked one of the closed issues from yesterday on this topic after i posted  this and another had the same issue). at least for now, until it isn't a dependency for the main branch, libaudiofile-dev should be one of the listed dependencies
