### ISSUE TITLE
(RPi 1/0 / Low mem issue) Building sound_data.tbl.c

### ISSUE THREAD

**Issue by Hyenadae** [sm64pc/sm64pc#35]
**Describe the bug**
Compile process of :

hexdump -v -e '1/1 "0x%X,"' build/us_pc/sound/sound_data.tbl >> build/us_pc/sound/sound_data.tbl.c
echo "};" >> build/us_pc/sound/sound_data.tbl.c

requires a LOT of memory (too much for a GPU acceleration prepared Raspbian install)
By default, CMA (VC4 GPU Memory) is set to 256MB. Compiles often need 120MB of free RAM to account for slow disk I/O and hexdump parsing.

**To Reproduce**
Install fresh Raspbian 10 on a 512MB or lower Raspberry Pi
Enable Accelerated OpenGL (KMS/FKMS) with required SM64PC Debian dependencies
Disable desktop boot to reduce RAM (auto-login command line if preferred) and then restart before

compiling with  'make TARGET_RPI=1'
Wait for sound_Data.tbl to freeze up as it uses +160-190MB  (Out of 430MB usable) RAM

**Expected behavior**
Rasberry Pis with 512MB of RAM or less and accelerated VC4-DRM + OpenGL/Mesa compile and produce a binary in a reasonable (1hr) time from start to finish

Temporary Solution:
After enabling RPi 1/0W accelerated OGL, add  

cma=128M to the end of    /boot/cmdline.txt
gpu_mem=48M  to the end of /boot/config.txt

Proposed solution:
Make sound_tbl into chunks or find a way to reduce memory and I/O during the hexdump extraction process into sound_data.tbl.c from sound_data.tbl

If SDcard I/O is too slow, RAM will be used as a buffer and also causing this issue.
It may be preferable to enforce disk syncs before this step to empty cached data to the SD before this step runs

**I can confirm that on Raspbian 10 with these fixes, SM64PC does run with graphics and no compile errors**

**Comment by TechdudeGames** [comment]
It might be worth it to make a 512 mb swap file/partition or use a cross compiler for account for the low amount of memory.

**Comment by Hyenadae** [comment]
Closed. A few days ago I created the pisetup.sh script that (when fully debugged) will allow easy adjustment for these lower memory Pis and compile the game.
