### ISSUE TITLE
Raspberry Pi - Allow / patch local SDL2 for KMSDRM (No X required)

### ISSUE THREAD

**Issue by Hyenadae** [sm64pc/sm64pc#37]
Currently, X11 is required on all Linux targets to output video. Due to the limited CPU of the earlier Raspberry Pi models, it is preferable to not have it run unless a Desktop is required (5-10% of CPU on 1GHz Pi 1).

Not likely to work on Raspberry Pi 4, but others can test and report back.

Steps to enable:
1. Fresh and fully updated Raspbian 10 or newer image
2. Install dependencies required for sm64pc compile on RPi 

3. Raspi-Config -> Adv -> OpenGL Accel -> KMS (Full)
3b (On Pis with 512MB RAM or less, set cma=128M in /boot/cmdline as root, then reboot)

4. Enable/uncomment deb-src in /etc/apt/sources.list (related files)
5. Do an apt-get update and follow sdl compile instructions from
https://stackoverflow.com/questions/57672568/sdl2-on-raspberry-pi-without-x
until you complete the 'make install' modified SDL2, section. Then, return to SM64 src directory.

7. Modify SM64 Makefile, RPi section to: 
ifeq ($(TARGET_RPI),1)
LDFLAGS := $(OPT_FLAGS) -lm **-lgbm** -lGLESv2 `$(CROSS)sdl2-config --libs` -no-pie

8. make TARGET_RPI=1   (on 512mb Pi models, please kill X11 / use raspi-config to disable Desktop boot to run compile in a safer manner)
9. Wait for compile to complete, switch to Virtual Terminal and/or kill X11
10. Execute binary in ./build/us_pc/sm64.us.xyz.arm

Note that you will not be able to currently exit Mario 64 as in-game quit is not currently implemented. I have noticed on my 1.1GHz Pi 1 that I get less stutters without X11 and using KMSDRM : GLES2

**Comment by Hyenadae** [comment]
If Raspbian actually enabled KMSDRM by default in sdl2, we wouldn't have to do all this work!
We should script, or provide scripts for max-performance on these weaker Linux machines

**Comment by vanfanel** [comment]
@Hyenadae If a KMSDRM-enabled SDL2 build is installed in your system, you dont need to pass `-lgbm`, since its SDL2 whats linked against libGBM, not sm64 itself.

Also, **YES, Raspbian should ship witth KMSDRM-enabled SDL2.**
Its infuriatingly stupid that it does not. I will ask them to do it when next stable SDL2 is released (I am making some changes to the SDL2 KMSDRM backend code at the moment).

**Comment by vrmiguel** [comment]
Well, sm64pc doesn't have a say on SDL2 or Raspbian, so I'll close this issue.

**Comment by parkerlreed** [comment]
Yeah this works fine on Arch where SDL2 has KMS/DRM enabled.

**Comment by Hyenadae** [comment]
I will be creating a script for Raspbian (10) that will automate many of the dependency installation and optional KMSDRM SDL2 compile + install to 'resolve' this

**Comment by vanfanel** [comment]
@Hyenadae that sounds very good.

**Comment by pedrodparkes** [comment]
@Hyenadae , hi, how is your progress aroun KMS/DRM install?
