### ISSUE TITLE
No way to quit & terminate process from inside game.

### ISSUE THREAD

**Issue by Hyenadae** [sm64pc/sm64pc#38]
Could be implemented as another option inside Mario 64's menu.
I've kind of seen how Mario 64 parses pause menu options / the cursor and exits levels, and now I want to puke

**Comment by Hyenadae** [comment]
Edit:  Being dumb and adding a new function on the "standard" pause screen-
    u8 textExitGame[] = { TEXT_EXIT_GAME };
and related stubs/adjustments to ./src/game/ingame_menu.c

**Comment by Hyenadae** [comment]
Implemented in some menus now, needs a cleaner exit method and eu/jp testing
https://github.com/sm64pc/sm64pc/pull/46

**Comment by vrmiguel** [comment]
This has now been implemented (by you :P) on https://github.com/sm64pc/sm64pc/commit/0ec63e46acb8f319a38449023cafde8af00e947f.
