### ISSUE TITLE
/usr/bin/ld: cannot find -lasound

### ISSUE THREAD

**Issue by chronic8000** [sm64pc/sm64pc#39]
**Describe the bug**
Compiling on Ubuntu targetting Windows x64 results in:

......
/dynlists_mario_eyebrows_mustache.o build/us_pc/src/goddard/dynlists/anim_group_1.o  -march=native -Llib -lpthread -lglew32 `sdl2-config --static-libs` -lm -lglu32 -lsetupapi -ldinput8 -luser32 -lgdi32 -limm32 -lole32 -loleaut32 -lshell32 -lwinmm -lversion -luuid -lopengl32 -no-pie -static
/usr/bin/ld: cannot find -lglew32
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libSDL2.a(SDL_dynapi.o): in function `SDL_InitDynamicAPI':
(.text+0x2552): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status
make: *** [Makefile:735: build/us_pc/sm64.us.f3dex2e.exe] Error 1

**To Reproduce**
make VERSION=us WINDOWS_BUILD=1

**Expected behavior**
Compile successfully

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu
 - Version 20.04 LTS

**Additional context**
Says it cannot find lasound but I think it's already installed with prerequisites?

**Comment by chronic8000** [comment]
Compiles for Ubuntu with same setup and works just fine so maybe needs something symlinked or I should use Windows to compile probably.

**Comment by coltongit** [comment]
> 
> 
> Compiles for Ubuntu with same setup and works just fine so maybe needs something symlinked or I should use Windows to compile probably.

Make sure you have libasound installed (or whatever that package name is) as that could be your problem right there.

**Comment by chronic8000** [comment]
Just checked it was installed so I removed it and when I re-installed I did this:

sudo apt-get install libasound-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libasound2-dev' instead of 'libasound-dev'

So seems Ubuntu is installing libasound2 instead of 1 not looked yet if it is possible to install version 1 or not.

**Comment by chronic8000** [comment]
Yeah libasound-dev is provided by libasound2-dev shared library for ALSA applications, which is installed. Thanks for the help on this though.

**Comment by coltongit** [comment]
Might need to manually install libasound-dev from the Ubuntu package site

**Comment by chronic8000** [comment]
```
or_skybox.o build/us_pc/bin/ccm_skybox.o build/us_pc/bin/water_skybox.o build/us_pc/bin/bidw_skybox.o build/us_pc/bin/bbh_skybox.o build/us_pc/bin/ssl_skybox.o build/us_pc/bin/wdw_skybox.o build/us_pc/sound/sound_data.ctl.o build/us_pc/sound/sound_data.tbl.o build/us_pc/sound/sequences.bin.o build/us_pc/sound/bank_sets.o  build/us_pc/lib/src/__osSpSetPc.o build/us_pc/lib/src/__osSpSetStatus.o build/us_pc/lib/src/NaN.o build/us_pc/lib/src/alBnkfNew.o build/us_pc/lib/src/osViTable.o build/us_pc/lib/src/__osSiCreateAccessQueue.o build/us_pc/lib/src/func_802F71A0.o build/us_pc/lib/src/osSpTaskYielded.o build/us_pc/lib/src/__osSpRawStartDma.o build/us_pc/lib/src/__osAiDeviceBusy.o build/us_pc/lib/src/ldiv.o build/us_pc/lib/src/__osSiRawReadIo.o build/us_pc/lib/src/_Litob.o build/us_pc/lib/src/osCreateMesgQueue.o build/us_pc/lib/src/__osPiCreateAccessQueue.o build/us_pc/lib/src/osViData.o build/us_pc/lib/src/__osSpDeviceBusy.o build/us_pc/lib/src/osGetThreadPri.o build/us_pc/lib/src/__osSiRawWriteIo.o build/us_pc/lib/src/guPerspectiveF.o build/us_pc/lib/src/guOrthoF.o build/us_pc/lib/src/__osGetCurrFaultedThread.o build/us_pc/lib/src/_Ldtob.o build/us_pc/lib/src/guTranslateF.o build/us_pc/lib/src/guNormalize.o build/us_pc/lib/src/unk_stack_data.o build/us_pc/lib/src/osSpTaskYield.o build/us_pc/lib/src/guScaleF.o build/us_pc/lib/src/__osSiDeviceBusy.o build/us_pc/lib/src/__osDequeueThread.o build/us_pc/lib/src/__osSpGetStatus.o build/us_pc/lib/src/guMtxF2L.o build/us_pc/lib/src/guLookAtRef.o build/us_pc/lib/src/osEPiRawStartDma.o build/us_pc/lib/src/guRotateF.o build/us_pc/lib/src/math/llmuldiv.o build/us_pc/lib/src/math/sinf.o build/us_pc/lib/src/math/llconv.o build/us_pc/lib/src/math/cosf.o build/us_pc/src/goddard/old_menu.o build/us_pc/src/goddard/particles.o build/us_pc/src/goddard/dynlist_proc.o build/us_pc/src/goddard/renderer.o build/us_pc/src/goddard/skin.o build/us_pc/src/goddard/joints.o build/us_pc/src/goddard/objects.o build/us_pc/src/goddard/draw_objects.o build/us_pc/src/goddard/debug_utils.o build/us_pc/src/goddard/gd_math.o build/us_pc/src/goddard/gd_memory.o build/us_pc/src/goddard/gd_main.o build/us_pc/src/goddard/skin_movement.o build/us_pc/src/goddard/sfx.o build/us_pc/src/goddard/shape_helper.o build/us_pc/src/goddard/dynlists/dynlist_test_cube.o build/us_pc/src/goddard/dynlists/dynlists_mario_eyes.o build/us_pc/src/goddard/dynlists/anim_mario_lips_1.o build/us_pc/src/goddard/dynlists/dynlist_mario_master.o build/us_pc/src/goddard/dynlists/dynlist_unused.o build/us_pc/src/goddard/dynlists/anim_group_2.o build/us_pc/src/goddard/dynlists/anim_mario_mustache_left.o build/us_pc/src/goddard/dynlists/dynlist_mario_face.o build/us_pc/src/goddard/dynlists/anim_mario_lips_2.o build/us_pc/src/goddard/dynlists/anim_mario_mustache_right.o build/us_pc/src/goddard/dynlists/anim_mario_eyebrows_1.o build/us_pc/src/goddard/dynlists/dynlists_mario_eyebrows_mustache.o build/us_pc/src/goddard/dynlists/anim_group_1.o  -march=native -Llib -lpthread -lglew32 `sdl2-config --static-libs` -lm -lglu32 -lsetupapi -ldinput8 -luser32 -lgdi32 -limm32 -lole32 -loleaut32 -lshell32 -lwinmm -lversion -luuid -lopengl32 -no-pie -static
/usr/bin/ld: cannot find -lglew32
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libSDL2.a(SDL_dynapi.o): in function `SDL_InitDynamicAPI':
(.text+0x2552): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: cannot find -lasound
collect2: error: ld returned 1 exit status
make: *** [Makefile:735: build/us_pc/sm64.us.f3dex2e.exe] Error 1

```

**Comment by coltongit** [comment]
I'm looking into that issue when I get the chance. Am out atm

**Comment by chronic8000** [comment]
> I'm looking into that issue when I get the chance. Am out atm

No worries thanks works fine compiled for Ubuntu anyway just wanted to get a Windows EXE.

**Comment by IvanDSM** [comment]
WINDOWS_BUILD=1 isn't for cross-compiling a Windows EXE under Ubuntu. It's for compiling a Windows executable under Windows. Check the wiki for Windows build instructions.

**Comment by coltongit** [comment]
I'm on Windows so the issue concerns me and those cross-compiling more

**Comment by chronic8000** [comment]
I will use Windows to compile for Windows then 👍
