### ISSUE TITLE
😭Dont store config and data in $HOME😭

### ISSUE THREAD

**Issue by narukeh** [sm64pc/sm64pc#43]
I made a new [ArchLinux package](https://aur.archlinux.org/packages/sm64pc-git/), and that saves the binary in `/us/bin/` . So when i run it from home (or a launcher), i get `sm64_save_file.bin` and `sm64config.txt` saved in `~/` which is very messy. (To store that in `/usr/bin/`, isn't a really good solution either). So please make it that it respects "XDG user directories", make it like like this:
`sm64config.txt` should stay in `$XDG_CONFIG_HOME` (aka `$HOME/.config` )
`sm64_save_file.bin` should stay in `$XDG_DATA_HOME` (aka `$HOME/.local/share`)

**Comment by dannyhpy** [comment]
Same thing here, it stores the file in the current directory

The workaround I used is the following
`$ (mkdir -p $XDG_DATA_HOME/sm64 && cd $XDG_DATA_HOME/sm64 && /usr/bin/sm64pc)`

Everything is executed in a subshell `()`
It creates the folder if it doesn't exist already
And launch the game

**Comment by vrmiguel** [comment]
We've had optional support for that for a while, it just hasn't been integrated into the rest of the code.
Please follow see the  [xdg_data_home_saving](https://github.com/sm64pc/sm64pc/tree/testing/enhancements/xdg_data_home_saving) enhancement.

**Comment by GizmoTheGreen** [comment]
whats gonna happen to this? afaik saving somewhere in $home is proper linux stuff, so shouldn't that be implemented?

**Comment by narukeh** [comment]
@GizmoTheGreen  i have solved it. Check out my [package](https://aur.archlinux.org/packages/sm64pc-git/)
i have renamed the binary as `/usr/bin/sm64pc.bin` and then i made a script `/usr/bin/sm64pc`
```
#!/bin/sh
set -e
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
[ -d "$XDG_DATA_HOME/sm64pc" ] || mkdir "$XDG_DATA_HOME/sm64pc"
cd "$XDG_DATA_HOME/sm64pc"
/usr/bin/sm64pc.bin
```
so i havent solved it, i've just eliminated the problem 😄
(also its $HOME and NOT _$home_)

**Comment by GizmoTheGreen** [comment]
That's a nice hack but not a nice solution for my setup, since I build daily from local copy of repo, and they need to fix it eventually to make it a real Linux app, right? (And add make install to makefile?) 

And right, capitalization matters in Linux, my bad hehe

**Comment by dannyhpy** [comment]
Hi @GizmoTheGreen, as vrmiguel said, you have to compile your own version of the game with the xdg_data_home_saving enhancement. I have tested it, it works really well

Otherwise, you should use narukeh's script on your end, it partly solves the problem

**Comment by GizmoTheGreen** [comment]
Hi, there is no such enhancement? It returns a 404 error.
It should also be the proper default behaviour in a Linux environment (not compiled with windows or osx flags)

**Comment by dannyhpy** [comment]
It has been moved to this location: https://github.com/sm64pc/sm64pc/tree/oldtesting/enhancements/xdg_data_home_saving

This is not currently the case due to Windows & OSX incompatibility I guess, not pretty sure on that
Feel free to open a pull request if you find a way to include that on the master branch that works well with other operating systems

**Comment by Jan200101** [comment]
the enhancement is now included in nightly
