### ISSUE TITLE
You know if i can use this italian fanmade translation ?

### ISSUE THREAD

**Issue by DjDiabolik** [sm64pc/sm64pc#448]
Searching info in internet i have reach this page:
https://letraduzionidirulesless.wordpress.com/super-mario-64-2/

Apparently it's a fanmade translation to applyed on US roms to play on real n64 hardware or by an emulator.

You know if it's possibly to obtain a port of sm64 for windows whit this italian translation ?

**Comment by rawr51919** [comment]
If you or someone extracts the text out of the ROM and converts it into the format sm64ex uses for ingame text, then it should be possible to use this translation, yes. It may require some special characters to use, however. Other repos have the special characters you'd need for this.
