### ISSUE TITLE
Disable BETTERCAMERA by default?

### ISSUE THREAD

**Issue by dannyhpy** [sm64pc/sm64pc#45]
After testing a few minutes, it doesn't feel comfortable to use.

Most of the time, the camera is stuck in a wall when you enter a new room.
It also breaks the auto camera movement (force you to move the camera permanently yourself)

It's only my opinion but I feel like it should be disabled in the Makefile.
I don't know if other people are ok with the Better camera feature?

**Comment by dannyhpy** [comment]
And I feel like the game should stay as it is. I mean, without any major modification

**Comment by vrmiguel** [comment]
Yeah, we'll do that. 


Unrelated to current issue but please check my latest comment on https://github.com/sm64pc/sm64pc/issues/44.
