### ISSUE TITLE
Add Support For Apple Silicon

### ISSUE THREAD

**Issue by BrentRosen** [sm64pc/sm64pc#452]
The current setup does not work with Apple Silicon, Please make it work with it

**Comment by fgsfdsfgs** [comment]
I don't have one so someone else will have to figure that out. Could you clarify what you mean by "doesn't work"?

**Comment by BrentRosen** [comment]
For example, I tried to use a tool such as sm64linux to build it on my m1 mac and it doesnt seem to compile at all and it has a bunch of errors. I am gayluigi on the sm64 port discord server, and if you look in #help desk general, you will see the problems that I encountered
