### ISSUE TITLE
SDL 1 breaks preferences directory path due to lack of SDL_GetPrefPath (a SDL2.0.1+ feature)

### ISSUE THREAD

**Issue by alex-free** [sm64pc/sm64pc#454]
**Describe the bug**
When using SDL1, the preferences directory is not specified and is instead considered the CWD. This means whatever directory you execute the executable from will be where the save/config files will be loaded/written to. 

I believe this is due to the usage of SDL_GetPrefPath in https://github.com/alex-free/sm64ex/blob/nightly/src/pc/platform.c when using SDL1,  even though this feature was introduced in SDL 2.0.1 https://wiki.libsdl.org/SDL_GetPrefPath .

I am experiencing this on PPC Mac OS X 10.5 Leopard, however due to the above information I believe this impacts all SDL 1 builds. May be able to test more OSes soon and will report back if so.

I see this in sm64ex/src/pc/platform.c:

`const char *sys_user_path(void) {
    static char path[SYS_MAX_PATH] = { 0 };

    // get the new pref path from SDL
    char *sdlpath = SDL_GetPrefPath("", "sm64ex");
    if (sdlpath) {
        const unsigned int len = strlen(sdlpath);
        strncpy(path, sdlpath, sizeof(path));
        path[sizeof(path)-1] = 0;

        SDL_free(sdlpath);

        if (path[len-1] == '/' || path[len-1] == '\\')
            path[len-1] = 0; // strip the trailing separator

        if (!fs_sys_dir_exists(path) && !fs_sys_mkdir(path))
            path[0] = 0; // somehow failed, we got no user path
        else
            copy_userdata(path); // TEMPORARY: try to copy old saves, if any
    }

    return path;
}`

Specifically:

`        if (!fs_sys_dir_exists(path) && !fs_sys_mkdir(path))
            path[0] = 0; // somehow failed, we got no user path`

**To Reproduce**
1. Compile using SDL 1
2. Run executable

**Expected behavior**
Preferences directory to be the same as when using SDL2. I.e., the save file should not be loaded/written to from the current directory.

A possible workaround IMO is to 'Emulate' SDL_GetPrefPath functionallity when using SDL 1 like is already done for SDL_AudioQueue.

**Comment by fgsfdsfgs** [comment]
The sdl1 backends are really a last ditch measure for old/weird platforms, so I didn't think to add that. I would need to basically copypaste the SDL2 implementation for it to work the same I guess.
In the meantime you can force the userdir with `--savepath /whatever/the/fuck`.

**Comment by alex-free** [comment]
> The sdl1 backends are really a last ditch measure for old/weird platforms, so I didn't think to add that. I would need to basically copypaste the SDL2 implementation for it to work the same I guess.
> In the meantime you can force the userdir with `--savepath /whatever/the/fuck`.

Great to hear, I might look into this as well. Totally understand and appreciate what has been done with SDL1 so far.
