### ISSUE TITLE
Game doesn't compile with mingw-w64 targetting Windows on Linux

### ISSUE THREAD

**Issue by rawr51919** [sm64pc/sm64pc#459]
**Describe the bug**
mingw-w64 fails to compile sm64ex when make is ran using the tools mingw-w64 provides for Ubuntu Linux to cross-compile the game for Windows.

**To Reproduce**
1. Use `make WINDOWS_BUILD=1 CROSS=x86_64-w64-mingw32- CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ SDLCONFIG=sdl2-config TEXTURE_FIX=1 NODRAWINGDISTANCE=1 DISCORDRPC=1` to attempt a compile using mingw-w64
2. Game compiles until the final exe link
3. We hit the linker errors described below.

**Expected behavior**
Game compiles successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/17090935/110352281-209c2900-800c-11eb-9849-143c8ca90d7f.png)
![image](https://user-images.githubusercontent.com/17090935/110352310-2a259100-800c-11eb-87c2-601e555babea.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Pro Education + WSL2 (Ubuntu 20.04.2 LTS)

**Additional context**
Trying to add more options for us folks to compile the PC port easily so I looked further into mingw-w64 cross-compilation and this is as far as I've been able to go with it. I previously have been able to achieve this type of cross-compilation using MXE, both prepackaged and from source, so it's not like it's my first rodeo with this or anything.

**Comment by rawr51919** [comment]
This was also discovered during the testing process of PR #456, which is why you see elements from that here in the screenshots.

**Comment by rawr51919** [comment]
When make clean was ran, a different error ensued
![image](https://user-images.githubusercontent.com/17090935/110355811-03695980-8010-11eb-80b5-05df4770cdab.png)

**Comment by fgsfdsfgs** [comment]
Are you sure it's using the correct `sdl2-config`?

**Comment by rawr51919** [comment]
mingw-w64 doesn't have an sdl2-config, so it has to use an sdl2-config from somewhere else

**Comment by rawr51919** [comment]
It has one on MSYS2 but not here with the mingw-w64 libraries for Ubuntu

**Comment by fgsfdsfgs** [comment]
Well that would point to your local /lib and /include directories and not the the mingw ones, which is why it can't find SDL.h.

**Comment by rawr51919** [comment]
I wonder if this requires it's own set of ifdefs to fix
Or perhaps mingw-w64 needs to be pointed to the local lib/include directories via symlinks to the files?

**Comment by fgsfdsfgs** [comment]
It does not require any code changes to fix. At worst Makefile changes, but I believe this can probably be fixed on your side completely.
Are you sure your SDL2 lib in mingw doesn't come with its own sdl2-config? It normally does in mingw-w64.

**Comment by rawr51919** [comment]
This is using WSL and Ubuntu, whose mingw-w64 doesn't have sdl2-config as a package.

**Comment by rawr51919** [comment]
The closest I have for an sdl2-config would be the mingw-w64 sdl2-config the AUR has

**Comment by fgsfdsfgs** [comment]
`sdl2-config` is not a separate package. It's a script that invokes `pkg-config` and it is part of your SDL2 package:
```
$ pacman -Ql mingw-w64-i686-SDL2
mingw-w64-i686-SDL2 /mingw32/
mingw-w64-i686-SDL2 /mingw32/bin/
mingw-w64-i686-SDL2 /mingw32/bin/sdl2-config
mingw-w64-i686-SDL2 /mingw32/bin/SDL2.dll
mingw-w64-i686-SDL2 /mingw32/include/
mingw-w64-i686-SDL2 /mingw32/include/SDL2/
mingw-w64-i686-SDL2 /mingw32/include/SDL2/begin_code.h
mingw-w64-i686-SDL2 /mingw32/include/SDL2/close_code.h
mingw-w64-i686-SDL2 /mingw32/include/SDL2/SDL.h
...
```
Actually my bad, it doesn't invoke `pkg-config`, but still.
