### ISSUE TITLE
how to invert camera view x-axis for the xbox one controller?

### ISSUE THREAD

**Issue by gabberhead** [sm64pc/sm64pc#460]
how can i invert the the x-axis for the camera view for the xbox one controller before i compile? default is, when i try to look to the left side, i must push the stick to the right side. i know this is the default behavor of the game, but i dont like it. thats why i would like to change it.

**Comment by parkerlreed** [comment]
You can just change the config? It has options for inverting the separate axis's

**Comment by gabberhead** [comment]
i tried it to change it. but i get it only to work with keyboard with the key cleft and cright. but i dont get it to work with the controller. in the options i can change the buttons, but not the sticks.

i also get it to work with the bettercam mod, but only with the bettercam enabled. without it, the option is not working for the default cam.

in this folder are the options for the controlls: /src/pc/controller
there must be an option for invert the xaxis, but i didnt found the right one. tried some changes and always compiled new exe files.

fullscreen false
window_x 0
window_y 23
window_w 1536
window_h 801
vsync true
texture_filtering 1
master_volume 127
music_volume 127
sfx_volume 127
env_volume 127
key_a 0026 1000 1103 
key_b 0033 1002 1101 
key_start 0039 1006 ffff 
key_l 002a 1009 1104 
key_r 0036 100a 101b 
key_z 0025 1007 101a 
key_cup 0148 ffff ffff 
key_cdown 0150 ffff ffff 
**key_cleft 014b ffff ffff 
key_cright 014d ffff ffff** 
key_stickup 0011 ffff ffff 
key_stickdown 001f ffff ffff 
key_stickleft 001e ffff ffff 
key_stickright 0020 ffff ffff 
stick_deadzone 16
rumble_strength 50
precache true
enable_cheats false
moonjump false
invincible false
infintie_lives false
super_speed false
controls false
exit_anywhere false
huge_mario false
tiny_mario false
coin 0
hover_mode false
moon_gravity false
run_speed 0
no_death_barrier false
jumps_higher false
speed_display false
t_pose_float false
cannon_anywhere false
auto_wk false
get_shell false
get_bobomb false
swift_swim false
blj_anywhere 0
play_as 0
flyer false
skip_intro true

**Comment by parkerlreed** [comment]
It appears you need bettercam enabled

```
[parker@stealth sm64ex]$ diff sm64config.txt.orig sm64config.txt
31c31
< bettercam_invertx true
---
> bettercam_invertx false
```

**Comment by gabberhead** [comment]
i know that. with bettercam i can invert it, but i prefer the original cam. on the wii u port u can invert it with a change in the build file controller_wiiu.c under sm64ex/src/pc/controller/ before compilation. then after the compilation the control is always inverted. and normaly there must be also anywhere in a build file in that same folder for the pc somewhere to change it. i tried several changes, but nothing worked.

**Comment by fgsfdsfgs** [comment]
If you don't mind editing code, swap the `L` and `R` around in [these two lines](https://github.com/sm64pc/sm64ex/blob/nightly/src/pc/controller/controller_sdl2.c#L243).

**Comment by gabberhead** [comment]
thanx. it worked ;)
