### ISSUE TITLE
[WEB] image not showing - (bug)

### ISSUE THREAD

**Issue by Virusnest** [sm64pc/sm64pc#463]
Image not showing: sound plays, no image, controls work and full screen does not work

![image](https://user-images.githubusercontent.com/72645466/113078064-20afd300-921e-11eb-8d3a-e6d10272fe1c.png)
![image](https://user-images.githubusercontent.com/72645466/113078167-4a68fa00-921e-11eb-9b7b-6097d8fa8e26.png)

 - OS: ChromeOS(Chromebook)
 - Browser Chrome
 - Version 89.0

**Comment by ghost** [comment]
I´m having the same issue on Firefox Linux x64 and ChromeOS

**Comment by ghost** [comment]
I'm going to try an older repository. (Edit: Same result)
Edit 2: It actually worked (disregard other edit) my adblocker was blocking the wasm.
Edit 3: Still have the same issue on chromeOS but it doesn't happend anywhere else..

**Comment by ghost** [comment]
Use a different loader for the WASM? I tried that and it finally ran on ChromeOS.
