### ISSUE TITLE
Help parameter doesn't work

### ISSUE THREAD

**Issue by impeeza** [sm64pc/sm64pc#464]
**Describe the bug**
The comand line parameter --help doesn't work

**To Reproduce**
1. On a command line go to the executable folder
2.  execute the command: sm64.us.f3dex2e.exe --help
3. Nothing happens

**Expected behavior**
A message like next should be displayed:
```
Super Mario 64 PC Port
	Enables the cheat menu.
		--cheats
	Saves the configuration file as CONFIGNAME.
		--configfile CONFIGNAME
	Overrides the default read-only data path ('!' expands to executable path).
		--datapath DATAPATH
	Overrides the default save/config path ('!' expands to executable path).
		--savepath SAVEPATH
	Starts the game in full screen mode.
		--fullscreen
	Skips the Peach and Castle intro when starting a new game.
		--skip-intro
	Starts the game in windowed mode.
		--windowed

```

and the program exits.

if you follow the steps, the program exits but no message displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/41979604/115121798-3d683c80-9f7a-11eb-8ec4-8ae1c50d54ca.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20h2
 - Version: 10.0.19042.928

**Additional context**
I am running Windows 10, MSYS2 MINGW64 shell for compiling.

**Comment by fgsfdsfgs** [comment]
That's because SDL2 redirects stdout on Windows by default. If you do `sm64.whatever.exe --help > log.txt` or run it in msys2 you'll see that it actually does work.

**Comment by impeeza** [comment]
oh,  nice, its funny how that work,   thanks a lot for your response.  regards from Colombia.
