### ISSUE TITLE
Fullscreen bug

### ISSUE THREAD

**Issue by kefel59** [sm64pc/sm64pc#47]
On Win10 in fullscreen, some pixels are not aligned properly.

![screen](https://user-images.githubusercontent.com/65125358/81504054-1f8b5580-929c-11ea-80bb-fee547392251.png)

**Comment by Hyenadae** [comment]
Looking at it.. it's not that the pixels aren't aligned, it's that the the 1st line of the *top* of the sprite is being redrawn. Hrm..

**Comment by Zero-Shift** [comment]
Issue does not seem to exist when using fullscreen on various DX12 builds. Perhaps something with SDL's implementation?

**Comment by coltongit** [comment]
It's also possible that it's an issue with the Fast3D OpenGL renderer.

**Comment by IvanDSM** [comment]
@kefel59 What branch are you using? Have you tried building the latest version?

**Comment by Zero-Shift** [comment]
@IvanDSM I've tested on latest master, issue is there

**Comment by coltongit** [comment]
PR #179 seems poised to fix this issue once and for all

**Comment by vrmiguel** [comment]
Closing this due to PR #179. Reopen if the problem persist.
