### ISSUE TITLE
How do I reset controls to default?

### ISSUE THREAD

**Issue by ghost** [sm64pc/sm64pc#471]
I accidentally remapped my controls to something weird. Now when I try to jump using A on my Nintendo Switch Pro Controller, the game pauses. As you can see here:

![2021-06-01 (3)](https://user-images.githubusercontent.com/85191372/120372267-cb4e7b80-c2cb-11eb-97a9-94dbfbd48972.png)

I can press the right trigger to open the "Options" menu. Look here:

![2021-06-01 (2)](https://user-images.githubusercontent.com/85191372/120372368-f8029300-c2cb-11eb-988d-c52264d1d0a1.png)

But I can't select any of the options in there. I want to go to controls, but I can't because I can't select. If I press A or the right trigger, it'll just go back to the Pause screen. How do I reset the controls to default?

EDIT: I found out that I can use the Options by moving the left analog stick to the right. But how do I set the controls to normal? The game still pauses every time I try to get Mario to jump by pressing A on my Switch Pro Controller.

EDIT AGAIN: I see three numbers for every input. What do each of these numbers mean?

![2021-06-01 (5)](https://user-images.githubusercontent.com/85191372/120373225-f1285000-c2cc-11eb-927f-70699c8e8e8c.png)

**Comment by fgsfdsfgs** [comment]
Each N64 button can have up to 3 bindings (usually keyboard, mouse and gamepad, but can be any combination). The numbers are internal key names, I just didn't add any human readable ones.
You can reset the controls by nuking sm64config.txt either next to the executable or in `AppData\Roaming\sm64pc`.

**Comment by ghost** [comment]
> Each N64 button can have up to 3 bindings (usually keyboard, mouse and gamepad, but can be any combination). The numbers are internal key names, I just didn't add any human readable ones.
> You can reset the controls by nuking sm64config.txt either next to the executable or in `AppData\Roaming\sm64pc`.

I realize that the second column is for controllers and that the first one is for the keyboard. So the third column is for the mouse?

**Comment by fgsfdsfgs** [comment]
By default, yes. You can bind any gamepad button, keyboard key or mouse button in any of the columns, so it's more like a convention than a real restriction.

**Comment by ZanitySMW** [comment]
Where do I find the AppData\Roaming\sm64pc on cell phone?
