### ISSUE TITLE
(question) how to get the nintendo switch port working

### ISSUE THREAD

**Issue by MacOS-9** [sm64pc/sm64pc#472]
as i said in the title, how exactly? (yes ik there is a wiki page about it but im stack at step 1, also if you have a discord and want to help me i can send my username and tag)

**Comment by fgsfdsfgs** [comment]
This is the wrong repository, the Switch port of sm64ex is [here](https://github.com/fgsfdsfgs/sm64ex). For help please ask in the help channels of the [PC port Discord](https://discord.gg/7bcNTPK).
