### ISSUE TITLE
Non-english message

### ISSUE THREAD

**Issue by superbonaci** [sm64pc/sm64pc#479]
Got this message after moving `sm64.us.f3dex2e` and launching it:

![](https://i.imgur.com/efAhebD.png)

**Comment by fgsfdsfgs** [comment]
Those messageboxes are created using `SDL_ShowSimpleMessageBox` and no extended characters (or non-English text at all) are used in any of the messages. In any case, this probably means you forgot to move the `res` folder with the executable.

**Comment by superbonaci** [comment]
> this probably means you forgot to move the `res` folder with the executable.

Is that mentioned in the wiki, that res in not inside the executable?
https://github.com/sm64pc/sm64ex/wiki

**Comment by fgsfdsfgs** [comment]
It isn't inside the executable if you built it with `EXTERNAL_DATA`. I think that is mentioned in the "Build options" section.
