### ISSUE TITLE
Debug the code

### ISSUE THREAD

**Issue by LuisMerinoP** [sm64pc/sm64pc#484]
This is not an issue but a question.

There seem to be an easy way to debug the code as briefly explained [here](https://sm64pc.info/forum/viewtopic.php?f=7&t=109&sid=f9641246c6aeb77d95b60e20be794a1e) but cannot get it to work.
I am getting the working built .exe file (with the Debug option selected in the sm64pcbuilder2 options), but the excution wont break at the breakpoint in visual studio. 

Seems that the binary is not built with with the debug info, as if I Debug->BreakAll and check the modules in Debug->Windows->Modules, I can see that: "Binary was not built with debug information".

![image](https://user-images.githubusercontent.com/49386405/141296319-d4ddccce-9647-4f71-8987-9a8257be6ea9.png)

Any tip about how to debug the code? Many thanks.

Edit: I also followed the build instructions and built it with the flag DEBUG=1 (If 1, build with debug symbols and default optimization level. Otherwise build with -O2.). Executable works fine but no success debugging the code.

**Comment by fgsfdsfgs** [comment]
Visual Studio will not read DWARF/whatever debug information (at least not by default, to my knowledge). You need GDB. The guide you linked describes how to get debugging in VSCode + GDB, so you should probably follow that.
