### ISSUE TITLE
[Raspberry Pi 3B+] Big perforamnce difference on 32bit vs 64bit

### ISSUE THREAD

**Issue by bkacjios** [sm64pc/sm64pc#487]
I wanted to see how well this ran on my Pi3B+ and found a weird issue. On 32bit (arm7h) the FPS is very bad, like 3-5 FPS. Some areas are better, like inside the castle. Switching over to a 64bit OS (aarch64), with same video drivers, libraries and everything, the FPS is perfect and the game is fully playable. It seems weird that there would be such a drastic performance difference, but the difference is night and day. Is there anyway I can like benchmark and try to find the bottleneck on a 32bit system?

 - Device: Raspberry Pi 3B+ (rev 1.3)
 - OS: ArchLinuxARM (armv7h/aarch64)
 - Video driver: vc4-fkms-v3d (OpenGL ES 2.0)

**Comment by fgsfdsfgs** [comment]
I really don't know. Are you sure the difference isn't in the video driver? It probably has different binaries or versions for arm7 vs aarch64, and there has been no shortage of weird bugs coming from the different Pi GL implementations.
You could run the game through gprof or something, I suppose.

**Comment by bkacjios** [comment]
I'll run it through gprof soon to see if I find anything. It may just be that 64bit can handle 1080p better. I found if I switch the resolution to 640 by 480 on the 32bit install it runs pretty much flawlessly.

**Comment by bkacjios** [comment]
Okay, so.. I made it so the game will exit after 1000 frames are rendered, and made a build for each architecture.

Here are the results.

[analysis_1080p_aarch64.txt](https://github.com/sm64pc/sm64ex/files/7598730/analysis_1080p_aarch64.txt)
[analysis_1080p_armv7h.txt](https://github.com/sm64pc/sm64ex/files/7598731/analysis_1080p_armv7h.txt)

I think this is just an issue where aarch64 GCC can optimize the code more efficiently. I think one of the biggest bottlenecks is with the matrix math functions.

**Comment by fgsfdsfgs** [comment]
Maybe the arm7 version is being built without NEON support or something?

**Comment by bkacjios** [comment]
I think the issue is there isn't actually any NEON optimized code. The neon flag is enable in the Makefile, but from what I can tell sm64ex doesn't actually use `arm_neon.h` for any math related functions it provides. This doesn't really matter for the 64bit aarch64, since neon isn't used and it just relies on the optimization of the compiler.

https://github.com/gonetz/GLideN64/blob/master/src/Neon/3DMathNeon.cpp

This is a good example of using neon instructions. I'm going to try and see if I can update some of the math util functions to use neon.

**Comment by fgsfdsfgs** [comment]
The compiler will try to auto-vectorize stuff on -O3 or higher IIRC if NEON is enabled. Not sure how successful it will be in the general case. Could be worth it to change it to -O2.
In general maybe the CFLAGS for 32-bit Pi models and modes need to be fine-tuned, since they weren't really tested that much and I didn't write them myself. Perhaps hardware floats need to be enabled explicitly.
Additionally make sure you're testing and making changes in the nightly branch, not the master branch.

**Comment by bkacjios** [comment]
Yeah, I'm working with the nightly branch.

I tried with `-mfloat-abi=hard -O2` and it doesn't seem to help. I even changed the `mtxf_mul` function and greatly reduced the call time. Maybe you were initially right about the GPU driver since 480p seems to work great on 32bit.

[analysis_480p_armv7h.txt](https://github.com/sm64pc/sm64ex/files/7599177/analysis_480p_armv7h.txt)
[analysis_1080p_armv7h.txt](https://github.com/sm64pc/sm64ex/files/7599178/analysis_1080p_armv7h.txt)

**Comment by fgsfdsfgs** [comment]
Unfortunately I have zero knowledge of Pi hardware and drivers (other than the graphics drivers being kinda fucky in my experience), so maybe someone else can confirm or deny this idea, though the fact that it depends on the resolution so much does kinda point away from the CPU-side floating point operations being the problem.

**Comment by bkacjios** [comment]
Okay, I'm an idiot. I was on nightly on my aarch64 SD card, but on master on my armv7h card. Turns out something in nightly greatly helped with performance. The game is running like too fast now, like double speed on 32bit. Seems to be the same issue #381

Welp, sorry about that.

**Comment by fgsfdsfgs** [comment]
Probably the broken vblank count detector. Try running with the `--syncframes N` parameter or disable vsync altogether.

**Comment by bkacjios** [comment]
Well, it's worth mentioning that the vblank detection in nightly doesn't function right at all on the raspberrypi. No matter what value I passed to syncframes, the game was always running too fast.

The only way I could get the game functioning normally, normal speed, and no lag was to replace `gfx_sdl_set_vsync` with `SDL_GL_SetSwapInterval` in `gfx_sdl2.c`

**Comment by Hyenadae** [comment]
Hey guys, thanks for keeping this report going and updated. I'm the original PC Port Pi guy and I was surprised to see some more work was going on in the development of this project. Since the merge was done, and more 60fps fixes were implemented I figure both 32bit and 64bit Pis work alright now?

Keep in mind, I only tested Mario 64 in KMSDRM (no X11) patched in Raspbian (Debian 10 afaik) on my 1ghz Pi 1 over HDMI, at "30fps" and native? resolution. No high resolution or enhancements existed for it back then (May 2020), and I kind of jumped off to another big-ish gaming coding project after :)

**Comment by bkacjios** [comment]
Yup, the game is fully playable now. I use the KMS driver too without X and it works great. I tested it on my Pi 2 and Pi 3b+ (both 32 and 64 bit) and they both could run it at full speed at 1080p. I tried the 60fps patch, but it would definitely struggle depending how much was on the screen. The render distance patch seems to work fine though. Not sure how far you could push it modding wise.
