### ISSUE TITLE
Building for WEB

### ISSUE THREAD

**Issue by urherenow** [sm64pc/sm64pc#49]
**Describe the bug**
After a successful Windows build, I installed emsdk and attempted to build for web. This was the result:

$ make TARGET_WEB=1
make: Nothing to be done for 'default'.

**To Reproduce**
1. Follow the building guide for windows, build it, and verify that it runs
2. Install emsdk
3. type make TARGET_WEB=1

**Expected behavior**
It should build for web, or at least throw an error.

**Desktop (please complete the following information):**
 - OS: Msys2 running mingw64 under Windows 10
 - Browser 
N/A

**Comment by IvanDSM** [comment]
Could you please try running `make clean` and then trying `make TARGET_WEB=1` again?

**Comment by urherenow** [comment]
That's one of the first things I tried.

$ make clean
rm -f -r build

<snip>MINGW64 ~/sm64pc
$ make TARGET_WEB=1
make: Nothing to be done for 'default'.

**Comment by urherenow** [comment]
Besides a billion warnings (unused variables, comparing int with u32, etc) it seems to work just fine in Ubuntu. I didn't do anything different, except for maybe installing the java-sdk as well (not sure I have that installed under msys2)

**Comment by urherenow** [comment]
UPDATE: with the latest merge/commits, it is now building under msys2. Will update when my build finishes, to see if it actually runs.

**Comment by urherenow** [comment]
Ok, so now that it builds, I end up with the same issue as before (when I built it with Ubuntu)
![SM64Web](https://user-images.githubusercontent.com/6448336/81534030-3ddb7900-93a2-11ea-8886-b0ed1a267e11.png)

**Comment by bpvarsity** [comment]
Same issue. Compiled on windows with latest testing src and I am stuck with this page 
<img width="1912" alt="Untitled" src="https://user-images.githubusercontent.com/2837098/81585022-29cf5180-9379-11ea-991a-4ee9d47e04a2.png">

**Comment by bpvarsity** [comment]
I got it working.

I ran this
emrun --no_browser --port 9090 build/us_web/sm64.us.f3dex2e.html

Then went to http://localhost:9090/sm64.us.f3dex2e.html

<img width="1414" alt="Untitled" src="https://user-images.githubusercontent.com/2837098/81588647-72d5d480-937e-11ea-8348-f9c4e2b79325.png">

**Comment by bpvarsity** [comment]
It does however show a black screen if I click fullscreen

**Comment by urherenow** [comment]
Lol, I just got it running myself. The issue is Chrome (and I guess all modern browsers now?) can’t properly handle a bunch of file:/// type urls.

What I just did was install XAMPP, created a folder in htdocs called sm64, started apache, then went to 127.0.0.1/sm64 and double-clicked on the html file from there.

I feel stupid now, but also learned a new thing so, time for me to close the issue.

**Comment by urherenow** [comment]
closing because it builds. Needs a new issue, maybe, for screen turning black if you go full-screen. Returning by hitting ESC, you can hear it playing still, but there is no window at all with video.
