### ISSUE TITLE
Mac OS Build: compiling without bettercamera option disables mouse input entirely

### ISSUE THREAD

**Issue by EzioisAwesome56** [sm64pc/sm64pc#496]
**Describe the bug**
If you do not compile the game with the bettercamera option, the mouse will not work at all.

**To Reproduce**
1. clone nightly
2. build with bettercamera set to 0
3. Observe non-functioning mouse buttons
4. ` gmake clean `
5. build with bettercamera set to 1
6. observe working mouse buttons

**Expected behavior**
The game should at least pick up the mouse buttons when clicked. Obviously the mouse look will not work because the bettercamera mod isn't even installed, but the mouse buttons should function.

**Desktop (please complete the following information):**
 - OS: Mac OS Monterey
 - Version: Monterey 12.1
- Architecture: Intel

**Comment by fgsfdsfgs** [comment]
That is not macOS exclusive I think. This ifdef block needs to be changed a bit to not exclude mouse button processing:
https://github.com/sm64pc/sm64ex/blob/nightly/src/pc/controller/controller_sdl2.c#L154
For the time being, if you build with bettercamera enabled you can still disable it in the options and mouse buttons should work.
