### ISSUE TITLE
On Mac OS 10.15.7 I can't install sm64

### ISSUE THREAD

**Issue by zcarp7220** [sm64pc/sm64pc#501]
When I try to install it it gives me this error:
aiff_extract_codebook.c:43:16: error: implicitly declaring library function
      'vsnprintf' with type 'int (char *, unsigned long, const char *, struct
      __va_list_tag *)' [-Werror,-Wimplicit-function-declaration]
    int size = vsnprintf(NULL, 0, fmt, ap);
               ^
aiff_extract_codebook.c:43:16: note: include the header <stdio.h> or explicitly
      provide a declaration for 'vsnprintf'
1 error generated.
make: *** [aiff_extract_codebook] Error 1
Makefile:187: *** Failed to build tools.  Stop.

**Comment by EmeraldLoc** [comment]
in tools/Makefile add in -Wno-error=implicit-function-declaration

Also, make sure you cloned the nightly branch, you can see via git status. If not, then clone it via git clone https://github.com/sm64pc/sm64ex -b nightly

**Comment by zcarp7220** [comment]
How to do that

**Comment by EmeraldLoc** [comment]
You will see a line where `CFLAGS` is being set, where you see `-Wno-unused-paramater` click on the left side of the r, hit space, and type `-Wno-error=implicit-function-declaration`

**Comment by zcarp7220** [comment]
See a line where

**Comment by EmeraldLoc** [comment]
Go to your file explorer and go to your repo, then go tools, then double click the Makefile, then do above ^

**Comment by zcarp7220** [comment]
Now it gives me this error:
cpp-9 -P -DVERSION_US -I . -o build/us_pc/level_rules.mk levels/level_rules.mk
gmake: cpp-9: No such file or directory
Makefile.split:152: build/us_pc/level_rules.mk: No such file or directory
gmake: *** [Makefile.split:151: build/us_pc/level_rules.mk] Error 127

**Comment by fgsfdsfgs** [comment]
It sounds like you're trying to build the `master` branch, which is old and dead. At least 2 of these issues have been fixed in the `nightly` branch. And try building with `OSX_BUILD=1`. Don't forget to clean in between builds.

**Comment by zcarp7220** [comment]
I tried with the nightly build and this is what came out:
gmake[1]: g++-mp-: No such file or directory
gmake[1]: *** [Makefile:7: audiofile.o] Error 127
gmake[1]: Leaving directory '/Users/z/Downloads/sm64ex-nightly/tools/audiofile'
gmake: *** [Makefile:41: audiofile/libaudiofile.a] Error 2
gmake: Leaving directory '/Users/z/Downloads/sm64ex-nightly/tools'
Makefile:271: *** Failed to build tools.  Stop.

**Comment by fgsfdsfgs** [comment]
It looks like it (maybe falsely) detects that you're using MacPorts and not brew and attempts to use the MacPorts gcc, which isn't installed. I can't really help you with that because I got no clue how either environment is set up since I don't use OSX.
You can kill the relevant check in the Makefile to force brew though.

**Comment by zcarp7220** [comment]
ok

**Comment by EmeraldLoc** [comment]
Ah, yes, this dumb error, go inside the Makefile and search for g++-mp and you will see some OSX_GCC_VER stuff on top of it, first remove the mp part, then remove the OSX_GCC_VER part, and change it to 11 for all 3. Also, @fgsfdsfgs, talk to GammaTendomNine, think his dm's are open, he has a solution for this.
