### ISSUE TITLE
Game controllers don't work on the M1 Mac build

### ISSUE THREAD

**Issue by sur4y** [sm64pc/sm64pc#509]
**Describe the bug**
My Logitech F710 gamepad/game controller does not work at all on my M1 build.

**To Reproduce**
1. Launch sm64ex on an M1 Mac
2. Try pressing start on the gamepad

**Expected behavior**
The gamepad should work in the game.

**Desktop (please complete the following information):**
 - OS: [macOS Monterey 12.5]

**Additional context**
I built sm64ex with the following build options: `OSX_BUILD=1 -j4`

Please let me know if some testing is required or if I can be of help somehow!

**Comment by fgsfdsfgs** [comment]
Have you tried using the [SDL2 gamecontroller tool](https://generalarcade.com/gamepadtool/)?

**Comment by sur4y** [comment]
@fgsfdsfgs 

Yes, I have, but I couldn't really get anything to work unfortunately.

**Comment by sur4y** [comment]
Update: My gamepad now works on Ventura 13.3. Everything works well except the start button.
