### ISSUE TITLE
[Suggestion] Option for current star count to be separate

### ISSUE THREAD

**Issue by DManuel010** [sm64pc/sm64pc#515]
Allow for an option to remove shared star count (the total count in upper right) between players.  Each player would have to collect their own stars to progress, allowing for competitive simultaneous runs in the same world, but not allowing one player to "carry" the rest of the players into zones they would not normally be able to access with their own star count.

**Comment by fgsfdsfgs** [comment]
Wrong repo, you're looking for sm64ex-coop.
