### ISSUE TITLE
Problems compiling on linux debian.

### ISSUE THREAD

**Issue by DuhLM** [sm64pc/sm64pc#516]
when i do make VERSION=us MARCH=i686 TARGET_BITS=32   (without the 64-bit libraries, if I have those libraries the error message is extended)

/usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
/usr/bin/ld: skipping incompatible lib/lua/linux/liblua53.a when searching for -l:liblua53.a
/usr/bin/ld: cannot find -l:liblua53.a
/usr/bin/ld: skipping incompatible build/us_pc/libdiscord_game_sdk.so when searching for -ldiscord_game_sdk
/usr/bin/ld: cannot find -ldiscord_game_sdk
/usr/bin/ld: skipping incompatible build/us_pc/libbass.so when searching for -lbass
/usr/bin/ld: cannot find -lbass
/usr/bin/ld: skipping incompatible build/us_pc/libbass_fx.so when searching for -lbass_fx
/usr/bin/ld: cannot find -lbass_fx
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/8/libstdc++.so when searching for -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/8/libstdc++.a when searching for -lstdc++
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/8/libgcc.a when searching for -lgcc
/usr/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
make: *** [Makefile:1602: build/us_pc/sm64.us.f3dex2e] Error 1

and if i do make BETTERCAMERA=1 EXTERNAL_DATA=1 -j4 / make -j4 (without 32 bits libraries) 

==== Build Options ====
Version:        us
Microcode:      f3dex2e
Target:         sm64.us
Compare ROM:    no
Build Matching: no
=======================
Building tools...
make: enters in the directory '/home/estudiante/sm64ex-coop/tools'
make: does nothing for 'default'.
make: goes out of the directory '/home/estudiante/sm64ex-coop/tools'
Building Game...
Linking executable: build/us_pc/sm64.us.f3dex2e 
/usr/bin/ld: i386 architecture of input file `build/us_pc/src/game/characters.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `build/us_pc/sound/sound_data.o' is incompatible with i386:x86-64 output
collect2: error: ld returned 1 exit status
make: *** [Makefile:1602: build/us_pc/sm64.us.f3dex2e] Error 1

**Comment by fgsfdsfgs** [comment]
This is the repository for sm64ex, you're looking for [sm64ex-coop](https://github.com/djoslin0/sm64ex-coop). You need to clean before switching architectures.

**Comment by DuhLM** [comment]
i'm an iditot 💀
