### ISSUE TITLE
macOS arm64 compilation error libaudiofile tabledesign

### ISSUE THREAD

**Issue by Kurtjwest** [sm64pc/sm64pc#517]
**Describe the bug**
Whenever I attempt to build on my M2 Macbook Pro I encounter the same error:

gcc-12 -I../include -I. -Wall -Wextra -Wno-unused-parameter -pedantic -std=c99 -O2 -s -Iaudiofile -Wno-uninitialized sdk-tools/tabledesign/codebook.c sdk-tools/tabledesign/estimate.c sdk-tools/tabledesign/print.c sdk-tools/tabledesign/tabledesign.c -o tabledesign -lm -Laudiofile -laudiofile -lstdc++ -lm
ld: warning: option -s is obsolete and being ignored
ld: warning: ignoring file audiofile/libaudiofile.a, building for macOS-arm64 but attempting to link with file built for macOS-arm64
Undefined symbols for architecture arm64:
  "_afGetChannels", referenced from:
      _main in ccTwJNem.o
  "_afGetFrameCount", referenced from:
      _main in ccTwJNem.o
  "_afGetRate", referenced from:
      _main in ccTwJNem.o
  "_afGetSampleFormat", referenced from:
      _main in ccTwJNem.o
  "_afGetTrackIDs", referenced from:
      _main in ccTwJNem.o
  "_afOpenFile", referenced from:
      _main in ccTwJNem.o
  "_afReadFrames", referenced from:
      _main in ccTwJNem.o
ld: symbol(s) not found for architecture arm64
collect2: error: ld returned 1 exit status
gmake[1]: *** [Makefile:54: tabledesign] Error 1
gmake[1]: Leaving directory '/Users/kjw/sm64ex/tools'
Makefile:270: *** Failed to build tools.  Stop.

I have installed, updated, and reinstalled all of the relevant dependencies.
The full compilation log can be viewed here: https://pastebin.com/PQMbZpna

**To Reproduce**
1. clone repo and add US rom
2. extract assets "./extract_assets.py us"
3. apply 60fps patch "./tools/apply_patch.sh ./enhancements/60fps_ex.patch "
4. build using command "gmake OSX_BUILD=1 BETTERCAMERA=1 NODRAWINGDISTANCE=1 EXT_OPTIONS_MENU=1 EXTERNAL_DATA=1 TEXTUREFIX=1"
5. see error

**Expected behavior**
I expected the program to compile

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1
 - Xcode: 14.1 (14B47b)

**Comment by monomadic** [comment]
Getting the same error, after several hours wrestling my macos install I realise why c development is such a horrible experience, and why people are moving to rust etc.
