### ISSUE TITLE
Crusty Audio on Pi 4

### ISSUE THREAD

**Issue by YoshiFan501** [sm64pc/sm64pc#52]
I compiled for a raspberry pi 4 with make "TARGET_RPI=1 -j4" and when ran the audio sounds horrible and crusty.

[Video example](https://photos.app.goo.gl/yhZ9oEX1ZWBaeJb28)

**Comment by YoshiFan501** [comment]
Found a fix.

sudo nano /etc/pulse/default.pa
Find the line that has the following:
Load-module module-udev-detect

Modify it to:
load-module module-udev-detect tsched=0

**Comment by Hyenadae** [comment]
Got it. Adding this as a note to my in-progress script.

**Comment by Hyenadae** [comment]
Stupid question, but can you post the output of

inxi -Gx  ?
I'm trying to see what RPi 4s output when their accelerated OpenGL is enabled.

**Comment by parkerlreed** [comment]
```
[parker@alarmpi ~]$ DISPLAY=:0 inxi -Gx
Graphics:  Device-1: bcm2711-vc5 driver: vc4_drm v: N/A bus ID: N/A 
           Device-2: bcm2711-hdmi0 driver: N/A bus ID: N/A 
           Device-3: bcm2711-hdmi1 driver: N/A bus ID: N/A 
           Display: server: X.Org 1.20.8 driver: modesetting unloaded: fbdev resolution: 720x480~60Hz 
           OpenGL: renderer: V3D 4.2 v: 2.1 Mesa 20.0.6 direct render: Yes 
```
