### ISSUE TITLE
Problems with using sm64pcbuilder2 and running render96ex

### ISSUE THREAD

**Issue by ghost** [sm64pc/sm64pc#521]
BUGS:
Compiler will crash 1st try.
Game hangs in (Not Responding state, before starting up).
Game runs too fast.

https://www.youtube.com/watch?v=RN8zYJ7dVvM&t=246s

Crashes when I first compile all the data, once the game boots it will hang up if you click the screen windows 10 will say
not responding, game running way to fast once in game. 

Microsoft Windows 10 Pro
10.0.19045 Build 19045
AMD Ryzen 7 3700X 8-Core Processor, 3600 Mhz, 8 Core(s), 16 Logical Processor(s)
MSI NVIDIA GeForce RTX 2070 Ventus 8GB
Corsair Vengeance RGB Pro 32GB (2x16GB) DDR4 3200

[BuilderLog_v1.21.3_Render96ex-tester_Failure_2023-04-09_11.37.53.txt](https://github.com/sm64pc/sm64ex/files/11186339/BuilderLog_v1.21.3_Render96ex-tester_Failure_2023-04-09_11.37.53.txt)

**Comment by fgsfdsfgs** [comment]
I can't help you with sm64builder2, I didn't make it. Try one of the SM64 port Discord servers. This is also not the repository for render96, that would be [here](https://github.com/Render96/Render96ex).

**Comment by Lanzhiyii** [comment]
![v1 21 3 - sm64ex-coop-coop - US -  D__msys64  - SL - 64-bit - Win11                                                   2024_7_8 19_30_29](https://github.com/sm64pc/sm64ex/assets/175034049/1139a91f-5f24-4b11-bea1-d607db8ec9a8)     could someone tell me what's wrong with the builder 2?????
