### ISSUE TITLE
MSYS not cloning the source code

### ISSUE THREAD

**Issue by PeterBeater** [sm64pc/sm64pc#524]
Whenever I try to get the source code to compile, MSYS2 says:
"fatal: Too many arguments."

**Comment by fgsfdsfgs** [comment]
Well what is the command that you're using to clone the source code?

**Comment by PeterBeater** [comment]
The command used was: “git clone https://github.com/sm64pc/sm64ex.git -b nightly cd sm64ex” as shown in the wiki.

**Comment by fgsfdsfgs** [comment]
That is two separate commands, which is shown in the wiki.
![image](https://user-images.githubusercontent.com/2997482/234891728-8f345258-3cb6-42c7-94b8-61d37b44a778.png)

**Comment by PeterBeater** [comment]
Alright. Thank you
