### ISSUE TITLE
Wiki Raspberry Pi Helper Script is outdated

### ISSUE THREAD

**Issue by NexusSfan** [sm64pc/sm64pc#525]
**Describe the bug**
On the wiki where they talk about the Helper script for compiling for Raspberry pi, [the link](https://raw.githubusercontent.com/sm64pc/sm64pc/master/pisetup.sh) is outdated and should use [this link](https://raw.githubusercontent.com/sm64pc/sm64ex/nightly/pisetup.sh) instead, or merge the nightly commit that updates the script to master.

**To Reproduce**
1. Go to the wiki
2. Click on Helper compiling script for Raspberry Pi
3. Click on the link on "The script is included on the master branch but can be downloaded [here](https://raw.githubusercontent.com/sm64pc/sm64pc/master/pisetup.sh)."
4. It is outdated.

**Expected behavior**
It shows an updated script for the latest version and using sm64pc/sm64ex instead of sm64pc/sm64pc

**Additional context**
It's probably because the wiki hasn't updated in a long time.

**Comment by fgsfdsfgs** [comment]
Fixed.
