### ISSUE TITLE
Wiki is outdated again

### ISSUE THREAD

**Issue by NexusSfan** [sm64pc/sm64pc#526]
**Describe the bug**
The home page still says "Welcome to the sm64pc wiki!" instead of "Welcome to the sm64ex wiki!".

**To Reproduce**
1. Go to the repo
2. Click on Wiki
3. See issue

**Expected behavior**
The text should "Welcome to the sm64ex wiki!"

**Comment by fgsfdsfgs** [comment]
Fixed.
