### ISSUE TITLE
Requesting Assistance

### ISSUE THREAD

**Issue by PyxelCoder** [sm64pc/sm64pc#527]
I've seem to hit a snag when building sm64ex on MSYS2.

I got stuck when I entered `$ make` and got the following:

`make[1]: cc: No such file or directory
make[1]: *** [Makefile:54: n64graphics] Error 127
Traceback (most recent call last):
  File "/home/josea/sm64ex/./extract_assets.py", line 286, in <module>
    main()
  File "/home/josea/sm64ex/./extract_assets.py", line 156, in main
    subprocess.check_call(
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-s', '-C', 'tools/', 'n64graphics', 'skyconv', 'mio0', 'aifc_decode']' returned non-zero exit status 2.
Makefile:263: *** Failed to extract assets.  Stop.
`

If anyone can help, let me know.

**Comment by fgsfdsfgs** [comment]
You need to do it on the MINGW64/MINGW32 terminal, not the MSYS terminal. Also you might not have the [prerequisites](https://github.com/sm64pc/sm64ex/wiki/Compiling-on-Windows#install-dependencies) installed.

**Comment by PyxelCoder** [comment]
> You need to do it on the MINGW64/MINGW32 terminal, not the MSYS terminal. Also you might not have the [prerequisites](https://github.com/sm64pc/sm64ex/wiki/Compiling-on-Windows#install-dependencies) installed.

Thanks for correcting my course.

**Comment by resolutezach1** [comment]
> You need to do it on the MINGW64/MINGW32 terminal, not the MSYS terminal. Also you might not have the [prerequisites](https://github.com/sm64pc/sm64ex/wiki/Compiling-on-Windows#install-dependencies) installed.

I was running on MINGW64, with the prerequisites installed, and I got the same error. it didn't give any output, it just gives "Makefile:263: *** Failed to extract assets.  Stop." and nothing else. is there something I'm doing wrong?

**Comment by fgsfdsfgs** [comment]
Either you need to install Python or you do not have the ROM in the game directory. There should be more output either way. If there isn't, try running `make clean`.

**Comment by resolutezach1** [comment]
> Either you need to install Python or you do not have the ROM in the game directory. There should be more output either way. If there isn't, try running `make clean`.

I tried that, Didn't work. but then I thought maybe there was something wrong with my mingw64 installation and reinstalling it turned out to fix the problem.
