### ISSUE TITLE
Save file erased after not opening the game for a while

### ISSUE THREAD

**Issue by springCLrad** [sm64pc/sm64pc#528]
I was playing Spamton 64, and I didnt open the game for a few days, when i reopened the game, my save was erased, i tried getting help from the sm64 pc port server and it couldnt be fixed.

**Comment by fgsfdsfgs** [comment]
EX doesn't automatically erase any files, so this is either something on your end or something in Spamton 64. In any case, you can't get it back. Ensure that it isn't in a temp folder or anything like that.
