### ISSUE TITLE
Build for Windows on WSL

### ISSUE THREAD

**Issue by iCrazyBlaze** [sm64pc/sm64pc#53]
I have followed [these instructions](https://github.com/sm64pc/sm64pc/wiki/Compiling-on-Linux) using WSL. Once it finished building, there were no executable files in the `build` folder. What file types should I expect to be there if not `exe`, and how do I then run the game?
![image](https://user-images.githubusercontent.com/27726289/81509066-fbf9f680-92ff-11ea-8a1e-0952cb5f8fc6.png)

EDIT: In addition, can I build on windows 10 without setting up MYSYS2, for example, using Git for Windows?

**Comment by fgsfdsfgs** [comment]
That sm64.us.f3dex2e is the executable. Just rename it to have the .exe extension. Unless you've actually somehow managed to build an ELF file or something.

**Comment by iCrazyBlaze** [comment]
> That sm64.us.f3dex2e is the executable. Just rename it to have the .exe extension. Unless you've actually somehow managed to build an ELF file or something.

Doing this gives me an error: "this application cannot run on your PC"

**Comment by vrmiguel** [comment]
You used WSL to compile a Linux executable, it'll not work on Windows. Follow the actual [Windows guide](https://github.com/sm64pc/sm64pc/wiki/Compiling-on-Windows) using MSYS2.


Unrelated but @fgsfdsfgs, would you like to join our dev channel on Discord? We'd love to have you on board.

**Comment by fgsfdsfgs** [comment]
@vrmiguel Alright. Just tell me where it is.

**Comment by vrmiguel** [comment]
@fgsfdsfgs  I've sent you a friend request! If you get a request by someone with a... pathetic username, that's me.
