### ISSUE TITLE
Pacman, cannot compile

### ISSUE THREAD

**Issue by JTC1234567** [sm64pc/sm64pc#530]
I am using win 7 64 bit, it's an older msys2 that is compatible. When I compile sm64ex it always fails and says:

Pacman: command not found. Bash_error

I'm completely lost and would like to sort this as my son is in tears we cannot play coop super mario. 

Please help

**Comment by JTC1234567** [comment]
![Uploading PXL_20230716_211109243.jpg…]()

**Comment by JTC1234567** [comment]
![PXL_20230716_211109243](https://github.com/sm64pc/sm64ex/assets/78223621/5f41f99d-1e56-472f-880c-14d526486c57)

**Comment by fgsfdsfgs** [comment]
If you want to play coop you need [sm64ex-coop](https://github.com/djoslin0/sm64ex-coop), not this repository. They have their own automated installer too, called `coop-compiler`. That should be simple enough to use.
I can't really help you with sm64pcbuilder either, that's managed by different people whom you can probably contact in this [Discord server](https://discord.gg/HcRcwMk).
As for the error, that looks like your msys install is severely screwed up.

**Comment by JTC1234567** [comment]
Would I be able to play with someone using the sm64 builder to run the rom if I use this coop compiler?
Will the coop compiler not work if my msys2 is broken? I literally just ran the exe. Uninstalled and tried again. Must be a common issue if it's through an exe?

**Comment by fgsfdsfgs** [comment]
Please ask in the sm64ex-coop repository or their Discord, I don't know much about it.
coop-compiler should download its own msys2, it does not require anything else.
