### ISSUE TITLE
opengl legacy undefined symbol (web build)

### ISSUE THREAD

**Issue by carteeeee** [sm64pc/sm64pc#536]
**Describe the bug**
at the end of recompilation, i get a few errors that say undefined symbol (see attached screenshot)

**To Reproduce**
1. extract game assets
2. apply 60fps patch
3. build with the flags `VERSION=us TARGET_WEB=1 BETTERCAMERA=1 NODRAWINGDISTANCE=0 TEXTURE_FIX=1 EXT_OPTIONS_MENU=1 EXTERNAL_DATA=0 RENDER_API=GL_LEGACY` 

**Expected behavior**
it should finish compiling

**Screenshots**
<img width="804" alt="Screenshot 2023-10-15 at 1 14 06 PM" src="https://github.com/sm64pc/sm64ex/assets/77160595/3348c72d-d484-42b4-b672-49332df79abb">

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - architecture: x86_64
 - latest emsdk ver as of the time i wrote this (oct 15 2023)

**Additional context**
the build runs fine for a regular pc target (although i didn't use opengl legacy).
i'm using opengl legacy because there was a different error building with regular opengl and it seems to get farther through the build process with opengl legacy

**Comment by fgsfdsfgs** [comment]
Legacy GL is for desktop platforms only. Web runs on WebGL, which is essentially GLES2.

**Comment by carteeeee** [comment]
in that case i'll close this issue and create another one with the problem i'm having for regular GL
