### ISSUE TITLE
Problem in tabledesign_CFLAGS, command not found

### ISSUE THREAD

**Issue by vini1264** [sm64pc/sm64pc#54]
when I run tabledesign_CFLAGS := -Wno-uninitialized -laudiofile -lstdc++ I get this:

$ tabledesign_CFLAGS := -Wno-uninitialized -laudiofile -lstdc++

bash: tabledesign_CFLAGS: command not found

Any idea on how to solve this "command not found" problem?

**Comment by WeKnowMadison** [comment]
Hey there!
This is a step where you don't need MSYS but it's not very clear on what you're supposed to do.

Leave MSYS alone and go to the "sm64pc" folder.

Inside that folder is another folder that is titled "tools". Open that and then double click the icon with the name "Makefile". Open it with notepad.

Scroll down to where you see "$ tabledesign_CFLAGS := -Wno-uninitialized -laudiofile" and add -"lstdc++" now click file in the top right and select save.

Now you can move on to the next step!

**Comment by vini1264** [comment]
> Hey there!
> This is a step where you don't need MSYS but it's not very clear on what you're supposed to do.
> 
> Leave MSYS alone and go to the "sm64pc" folder.
> 
> Inside that folder is another folder that is titled "tools". Open that and then double click the icon with the name "Makefile". Open it with notepad.
> 
> Scroll down to where you see "$ tabledesign_CFLAGS := -Wno-uninitialized -laudiofile" and add -"lstdc++" now click file in the top right and select save.
> 
> Now you can move on to the next step!

Thanks, now it worked
