### ISSUE TITLE
Helper compiling script for Raspberry Pi wiki page outdated again.

### ISSUE THREAD

**Issue by NexusSfan** [sm64pc/sm64pc#541]
**Describe the bug**
When you go on the Helper compiling script for Raspberry Pi wiki page it says "Compiles sm64pc." at the bottom bulletin points instead of "Compiles sm64ex."

**To Reproduce**
1. Go to wiki
2. Click on Helper compiling script for Raspberry Pi
3. Scroll down to the last bulletin point
4. Outdated?

**Expected behavior**
It should say
"Compiles sm64ex."

**Additional context**
Other bulletin points also are outdated.

**Comment by fgsfdsfgs** [comment]
Fixed the name.
