### ISSUE TITLE
No Fullscreen on Test Version Windows 10

### ISSUE THREAD

**Issue by WeKnowMadison** [sm64pc/sm64pc#55]
I've been having a fullscreen issue between the regular release and the test release and I'm curious if anyone has a fix.

When I install the non-test release I can enter fullscreen when playing.  However when I install the test version it won't enter fullscreen when pressing alt+enter. I would LOOOOVE to play the better camera version in fullscreen if someone know's a fix.

No errors in setting everything up, I just can't enter fullscreen.

**Comment by IvanDSM** [comment]
Hey there! Not being able to fullscreen in the testing branch is currently a known issue. However, I would like to let you know we've merged the better camera version into the master branch, which has working fullscreen. Give compiling that a try in the meantime!

**Comment by WeKnowMadison** [comment]
> Hey there! Not being able to fullscreen in the testing branch is currently a known issue. However, I would like to let you know we've merged the better camera version into the master branch, which has working fullscreen. Give compiling that a try in the meantime!

Ahh dang! The improved camera is definitely great but I was actually aiming for the analogue controls that were added to the testing ;D
Thank you though!

**Comment by urherenow** [comment]
the merge broke some things though. I was having fun with the camera branch, but now that it's merged, analog camera enabled, is actually DISABLED (using the pause options menu in-game). Also using the "c buttons" is all backwards. Finally, the camera keeps tweaking out and getting locked on top (pointing down) of Mario, and you need to use the mouse feature to fix it.

**Comment by vrmiguel** [comment]
> > Hey there! Not being able to fullscreen in the testing branch is currently a known issue. However, I would like to let you know we've merged the better camera version into the master branch, which has working fullscreen. Give compiling that a try in the meantime!
> 
> Ahh dang! The improved camera is definitely great but I was actually aiming for the analogue controls that were added to the testing ;D
> Thank you though!

What do you mean? master now has analogue camera controls when built with the `make BETTERCAMERA=1` flag.

**Comment by vrmiguel** [comment]
Closed by accident.
