### ISSUE TITLE
trying to compile the game and getting this error: error: 'dispatch_data_t' was not declared in this scope; did you mean 'dispatch_data_s'?

### ISSUE THREAD

**Issue by AwayCoast23465** [sm64pc/sm64pc#552]
trying to build a fork of this, but they dont have an issue page, so the error is trying to compile the game and getting this error: error: 'dispatch_data_t' was not declared in this scope; did you mean 'dispatch_data_s'?

**Comment by fgsfdsfgs** [comment]
I don't think that type is even in this codebase. You will have to ask the authors of the fork. Unless that's something OSX specific that I don't know about or something.
