### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by MainIsHerelol** [sm64pc/sm64pc#557]
idk how to describe the bug.. but here:
name@name-MacBook-Air sm64ex-coop % gmake OSX_BUILD=1
==== Build Options ====
Version:        us
Microcode:      f3dex2e
Target:         sm64.us
Compare ROM:    no
Build Matching: no
=======================
Failed to open baserom.us.z64! [Errno 2] No such file or directory: 'baserom.us.z64'
Makefile:471: *** Failed to extract assets.  Stop.
name@name-MacBook-Air sm64ex-coop % 

**To Reproduce**
just follow the macos build tutorial

**Expected behavior**
I expected it to compile fine

**Comment by fgsfdsfgs** [comment]
Put the rom in the project folder. File should be called `baserom.us.z64`. Also you're compiling coop, this is not the coop repo. [This](https://github.com/djoslin0/sm64ex-coop) is.

**Comment by MainIsHerelol** [comment]
oh, ok! thanks
