### ISSUE TITLE
Windows 10 MYSYS2 Building error

### ISSUE THREAD

**Issue by iCrazyBlaze** [sm64pc/sm64pc#56]
After following the instructions for windows, the last step (running make in the root) fails, with this error: 

collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:749: build/us_pc/sm64.us.f3dex2e.exe] Error 1
rm build/us_pc/bin/bidw_skybox.c build/us_pc/bin/ccm_skybox.c build/us_pc/bin/bbh_skybox.c build/us_pc/bin/                                                                                                                                                                    clouds_skybox.c build/us_pc/bin/wdw_skybox.c build/us_pc/bin/water_skybox.c build/us_pc/bin/bits_skybox.c b                                                                                                                                                                    uild/us_pc/bin/bitfs_skybox.c build/us_pc/bin/ssl_skybox.c build/us_pc/bin/cloud_floor_skybox.c build/us_pc                                                                                                                                                                    /sound/sequences/00_sound_player.o

EDIT: I have tried using `PATH=/mingw32/bin:/mingw64/bin:$PATH make -j6` instead of just `make` and it still fails.

**Comment by IvanDSM** [comment]
We're missing some info in your log. Please use just make, without -j6 and post the full result of that.

**Comment by dgeneratioN** [comment]
I don't know if its related, but i was having this issue due to compiling the linux binaries, and then wrongfully trying to build the windows binaries via WSL before even trying MSYS2.

Redownloading to source to a clean folder and restarting the steps solved the problem for me

**Comment by urherenow** [comment]
@dgeneratioN have you tried to build the web target under MSYS2? I simply get "nothing to be done for 'default'"

So I tried building the web target in UBUNTU, and the result doesn't work. (it builds, but the result is just broken).

**Comment by iCrazyBlaze** [comment]
this is as far as the logs go.
https://hatebin.com/pkpbsgnhgt

**Comment by bpvarsity** [comment]
I am getting this too. I have been able to compile this in the past just fine. See logs
https://hatebin.com/bejrzabtjq

**Comment by bpvarsity** [comment]
Well I started again from a fresh download of the src and it built just fine so not sure what happened but it compiled perfectly.

**Comment by vrmiguel** [comment]
Oh, cool. Good to know it was solved in some way.
