### ISSUE TITLE
Audio now stutters on macOS

### ISSUE THREAD

**Issue by caleb39411** [sm64pc/sm64pc#560]
**Describe the bug**
Audio stutters on arm64 macOS build.

**To Reproduce**
Compile with no flags or options on macOS.

**Expected behaviour**
Before 39cfae6 the audio ran full speed.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS 14.5

**Additional context**

**Comment by fgsfdsfgs** [comment]
@KingOfSpadesJFK Any ideas?

**Comment by AceOfSpades-JFK** [comment]
I suppose we could try decreasing the audio thread's sleep time on macOS... I don't have a mac so that's the best i could come up with.

**Comment by kewlduda** [comment]
I would be happy to test anything you need.

**Comment by fgsfdsfgs** [comment]
I've added two config vars, `audio_runahead` and `audio_sleep`. Try setting `audio_runahead` to `0.5`. If that doesn't work, try setting `audio_sleep` to `0.5` or something, I dunno.

**Comment by kewlduda** [comment]
I've tested it, and `audio_runahead` seems to do nothing, whist `audio_sleep` seems to just be a speed multiplier for audio.

**Comment by AceOfSpades-JFK** [comment]
Maybe we could render more samples?

**Comment by fgsfdsfgs** [comment]
I'd need to know what exactly the problem is and there's no way I can do that without an OSX machine.

**Comment by fgsfdsfgs** [comment]
I've reverted the multithreaded audio for now since I'm unable to diagnose this. Maybe should make it an option or something later. In any case, OSX audio should be back to how it was before.
