### ISSUE TITLE
unlisted dependency for compiling on Linux - hexdump

### ISSUE THREAD

**Issue by devek1** [sm64pc/sm64pc#563]
The instructions for compiling on Linux fail to mention hexdump, potentially leading to failures to compile on minimal installations, such as when using containers to build under host systems with immutable rootfs

Steps to reproduce:
1.) set up any system that doesn't have hexdump by default - in my case it was a podman container using Docker's image of Ubuntu 22.04 (set up using SteamOS 3.5.19's included version of distrobox)
2.) follow the "Compiling on Linux" instructions on the wiki
3.) make will fail, with several errors in the middle of the log stating that hexdump was not found

(compilation was later successful after running `sudo apt install bsdmainutils`)

**Comment by fgsfdsfgs** [comment]
Added to wiki page.
