### ISSUE TITLE
Failed to build tools on Fedora (specifically Nobara)

### ISSUE THREAD

**Issue by NotoriousBigNut** [sm64pc/sm64pc#565]
I have installed all the dependencies and I am getting the following error:

make[1]: Entering directory '/home/banitsingh/sm64ex/tools'
make[2]: Entering directory '/home/banitsingh/sm64ex/tools/audiofile'
g++ -std=gnu++11 -DNDEBUG -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -O2 -I. -c audiofile.cpp
make[2]: g++: No such file or directory
make[2]: *** [Makefile:7: audiofile.o] Error 127
make[2]: Leaving directory '/home/banitsingh/sm64ex/tools/audiofile'
make[1]: *** [Makefile:41: audiofile/libaudiofile.a] Error 2
make[1]: Leaving directory '/home/banitsingh/sm64ex/tools'
Makefile:270: *** Failed to build tools.  Stop.

Everything before this text is just asset extraction.
I am on the latest Nobara build (Fedora linux). Can someone help me out please?

**Comment by fgsfdsfgs** [comment]
Install g++. Think the package is called `gcc-c++`.

**Comment by NotoriousBigNut** [comment]
Thanks, it worked

**Comment by Tiagoquix** [comment]
@fgsfdsfgs Thanks. Please update the wiki section about Fedora requirements with that package.
