### ISSUE TITLE
Crashes when loading Hazy Maze Cave in fullscreen.

### ISSUE THREAD

**Issue by gunvalk** [sm64pc/sm64pc#57]
After the star select screen the game will crash when loading the level, but only in fullscreen. Can be reproduced.

**Comment by Zero-Shift** [comment]
Able to reproduce the issue. To add on, entering Hazy Maze Cave windowed **then** going full screen works fine.

**Comment by urherenow** [comment]
Where does BETTERCAMERA=1 go? I tried adding it to the .ini and nothing happens, and it always gets deleted (from the master branch) and it's the same thing when launching the .exe with BETTERCAMERA=1.

**Comment by Hyenadae** [comment]
We're fixing another issue related to graphics pool size, but I'm going to check into this myself.

**Comment by vrmiguel** [comment]
@gunvalk @Zero-Shift 
Please try to reproduce this issue using master's latest commit.

**Comment by Zero-Shift** [comment]
@vrmiguel Issue seems to be fixed now, thanks!

**Comment by gunvalk** [comment]
@vrmiguel yep its fixed! you guys are the best.

**Comment by Benchamoneh** [comment]
More information just for awareness, I was able to reproduce this bug both windowed and fullscreen, seems the issue was not in the application being fullscreen but rather the aspect ratio. Resizing the window to a non 4:3 ratio (stretching it out wide) caused the game to crash for me even windowed.
