### ISSUE TITLE
D:

### ISSUE THREAD

**Issue by slap1996** [sm64pc/sm64pc#577]
when compiling ...

src/pc/rom_checker.cpp:20:21: error: 'filesystem' is not a namespace-name
   20 | namespace fs = std::filesystem;
      |                     ^~~~~~~~~~
src/pc/rom_checker.cpp: In function 'void rename_tmp_folder()':
src/pc/rom_checker.cpp:43:9: error: 'fs' has not been declared
   43 |     if (fs::exists(oldPath) && !fs::exists(newPath)) {
      |         ^~
src/pc/rom_checker.cpp:43:33: error: 'fs' has not been declared
   43 |     if (fs::exists(oldPath) && !fs::exists(newPath)) {
      |                                 ^~
src/pc/rom_checker.cpp:47:9: error: 'fs' has not been declared
   47 |         fs::rename(oldPath, newPath);
      |         ^~
src/pc/rom_checker.cpp: In function 'bool is_rom_valid(std::string)':
src/pc/rom_checker.cpp:57:32: error: 'setw' is not a member of 'std'
   57 |         ss << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(dataHash[i]);
      |                                ^~~~
src/pc/rom_checker.cpp:57:48: error: 'setfill' is not a member of 'std'; did you mean 'fill'?
   57 |         ss << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(dataHash[i]);
      |                                                ^~~~~~~
      |                                                fill
src/pc/rom_checker.cpp:66:46: error: 'std::filesystem' has not been declared
   66 |             if (romPath != destPath && !std::filesystem::exists(std::filesystem::path(destPath))) {
      |                                              ^~~~~~~~~~
src/pc/rom_checker.cpp:66:70: error: 'std::filesystem' has not been declared
   66 |             if (romPath != destPath && !std::filesystem::exists(std::filesystem::path(destPath))) {
      |                                                                      ^~~~~~~~~~
src/pc/rom_checker.cpp:67:22: error: 'std::filesystem' has not been declared
   67 |                 std::filesystem::copy_file(
      |                      ^~~~~~~~~~
src/pc/rom_checker.cpp:68:26: error: 'std::filesystem' has not been declared
   68 |                     std::filesystem::path(romPath),
      |                          ^~~~~~~~~~
src/pc/rom_checker.cpp:69:26: error: 'std::filesystem' has not been declared
   69 |                     std::filesystem::path(destPath)
      |                          ^~~~~~~~~~
src/pc/rom_checker.cpp: In function 'bool scan_path_for_rom(const char*)':
src/pc/rom_checker.cpp:84:34: error: 'std::filesystem' has not been declared
   84 |     for (const auto &entry: std::filesystem::directory_iterator(dir)) {
      |                                  ^~~~~~~~~~
make: *** [Makefile:1401: build/us_pc/src/pc/rom_checker.o] Error 1
make: *** Waiting for unfinished jobs....

Help! i want to play :3

**Comment by fgsfdsfgs** [comment]
This is the wrong repository, post issues for sm64-coop-deluxe [here](https://github.com/coop-deluxe/sm64coopdx).
