### ISSUE TITLE
Failing to WINDOWS_BUILD=1

### ISSUE THREAD

**Issue by MissLav** [sm64pc/sm64pc#61]
**havving issues with deps**
sage: /usr/bin/sdl2-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs]
/usr/bin/ld: cannot find -lglew32
/usr/bin/ld: cannot find -lglu32
/usr/bin/ld: cannot find -lsetupapi
/usr/bin/ld: cannot find -ldinput8
/usr/bin/ld: cannot find -luser32
/usr/bin/ld: cannot find -lgdi32
/usr/bin/ld: cannot find -limm32
/usr/bin/ld: cannot find -lole32
/usr/bin/ld: cannot find -loleaut32
/usr/bin/ld: cannot find -lshell32
/usr/bin/ld: cannot find -lwinmm
/usr/bin/ld: cannot find -lversion
/usr/bin/ld: cannot find -luuid
/usr/bin/ld: cannot find -lopengl32
collect2: error: ld returned 1 exit status
make: *** [Makefile:735: build/us_pc/sm64.us.f3dex2e.exe] Error 1
[lavender@ar4 sm64pc]$ sudo make WINDOWS_BUILD=1 -j8

i also have all these deps 

seems to be the same issue as this case
 https://unix.stackexchange.com/questions/423821/gcc-usr-bin-ld-cannot-find-lglut32-lopengl32-lglu32-lfreegut-but-these
but ive givin it a shot and cant seem to figure it out

**Expected behavior**
for it to build normally

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro
 - kernel56

**Additional context**
im on a linux machine trying to build the windows exe 
[fail.txt](https://github.com/sm64pc/sm64pc/files/4607224/fail.txt)

heres my discord if someone is up to vc and help MissLavender#5032

**Comment by IvanDSM** [comment]
Please see the first section of https://github.com/sm64pc/sm64pc/wiki/Compiling-on-Linux.

**Comment by MissLav** [comment]
> Please see the first section of https://github.com/sm64pc/sm64pc/wiki/Compiling-on-Linux.

im not trying to compile for linux also i already have every dep like i said in my post

[lavender@ar4 ~]$ sudo pacman -S base-devel python audiofile sdl2 glew
[sudo] password for lavender: 
:: There are 24 members in group base-devel:
:: Repository core
   1) autoconf  2) automake  3) binutils  4) bison  5) fakeroot  6) file  7) findutils  8) flex  9) gawk  10) gcc  11) gettext  12) grep  13) groff  14) gzip  15) libtool  16) m4  17) make  18) pacman  19) patch  20) pkgconf  21) sed  22) sudo
   23) texinfo  24) which

Enter a selection (default=all): 
warning: autoconf-2.69-7 is up to date -- reinstalling
warning: automake-1.16.2-1 is up to date -- reinstalling
warning: binutils-2.34-2.1 is up to date -- reinstalling
warning: bison-3.5.4-1 is up to date -- reinstalling
warning: fakeroot-1.24-2 is up to date -- reinstalling
warning: file-5.38-3 is up to date -- reinstalling
warning: findutils-4.7.0-2 is up to date -- reinstalling
warning: flex-2.6.4-3 is up to date -- reinstalling
warning: gawk-5.1.0-1 is up to date -- reinstalling
warning: gcc-9.3.0-1 is up to date -- reinstalling
warning: gettext-0.20.2-1 is up to date -- reinstalling
warning: grep-3.4-1 is up to date -- reinstalling
warning: groff-1.22.4-3 is up to date -- reinstalling
warning: gzip-1.10-3 is up to date -- reinstalling
warning: libtool-2.4.6+42+gb88cebd5-12 is up to date -- reinstalling
warning: m4-1.4.18-3 is up to date -- reinstalling
warning: make-4.3-3 is up to date -- reinstalling
warning: pacman-5.2.1-4 is up to date -- reinstalling
warning: patch-2.7.6-8 is up to date -- reinstalling
warning: pkgconf-1.6.3-4 is up to date -- reinstalling
warning: sed-4.8-1 is up to date -- reinstalling
warning: sudo-1.8.31.p1-1 is up to date -- reinstalling
warning: texinfo-6.7-3 is up to date -- reinstalling
warning: which-2.21-5 is up to date -- reinstalling
warning: python-3.8.2-2 is up to date -- reinstalling
warning: audiofile-0.3.6-5 is up to date -- reinstalling
warning: sdl2-2.0.12-1 is up to date -- reinstalling
warning: glew-2.2.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (28) audiofile-0.3.6-5  autoconf-2.69-7  automake-1.16.2-1  binutils-2.34-2.1  bison-3.5.4-1  fakeroot-1.24-2  file-5.38-3  findutils-4.7.0-2  flex-2.6.4-3  gawk-5.1.0-1  gcc-9.3.0-1  gettext-0.20.2-1  glew-2.2.0-2  grep-3.4-1  groff-1.22.4-3
              gzip-1.10-3  libtool-2.4.6+42+gb88cebd5-12  m4-1.4.18-3  make-4.3-3  pacman-5.2.1-4  patch-2.7.6-8  pkgconf-1.6.3-4  python-3.8.2-2  sdl2-2.0.12-1  sed-4.8-1  sudo-1.8.31.p1-1  texinfo-6.7-3  which-2.21-5

Total Download Size:     5.79 MiB
Total Installed Size:  313.43 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 m4-1.4.18-3-x86_64                                                                                                         169.4 KiB  1947 KiB/s 00:00 [##############################################################################################] 100%
 autoconf-2.69-7-any                                                                                                        591.2 KiB  3.61 MiB/s 00:00 [##############################################################################################] 100%
 findutils-4.7.0-2-x86_64                                                                                                   454.6 KiB  3.50 MiB/s 00:00 [##############################################################################################] 100%
 sed-4.8-1-x86_64                                                                                                           237.9 KiB  8.94 MiB/s 00:00 [##############################################################################################] 100%
 fakeroot-1.24-2-x86_64                                                                                                      67.0 KiB  1558 KiB/s 00:00 [##############################################################################################] 100%
 file-5.38-3-x86_64                                                                                                         314.2 KiB  2.87 MiB/s 00:00 [##############################################################################################] 100%
 flex-2.6.4-3-x86_64                                                                                                        297.2 KiB  2.48 MiB/s 00:00 [##############################################################################################] 100%
 grep-3.4-1-x86_64                                                                                                          204.2 KiB  2.22 MiB/s 00:00 [##############################################################################################] 100%
 groff-1.22.4-3-x86_64                                                                                                     2044.3 KiB  12.2 MiB/s 00:00 [##############################################################################################] 100%
 gzip-1.10-3-x86_64                                                                                                          77.8 KiB  2.24 MiB/s 00:00 [##############################################################################################] 100%
 pacman-5.2.1-4-x86_64                                                                                                     1363.1 KiB  6.90 MiB/s 00:00 [##############################################################################################] 100%
 patch-2.7.6-8-x86_64                                                                                                        92.5 KiB  3.01 MiB/s 00:00 [##############################################################################################] 100%
 which-2.21-5-x86_64                                                                                                         15.8 KiB  0.00   B/s 00:00 [##############################################################################################] 100%
(28/28) checking keys in keyring                                                                                                                        [##############################################################################################] 100%
(28/28) checking package integrity                                                                                                                      [##############################################################################################] 100%
(28/28) loading package files                                                                                                                           [##############################################################################################] 100%
(28/28) checking for file conflicts                                                                                                                     [##############################################################################################] 100%
(28/28) checking available disk space                                                                                                                   [##############################################################################################] 100%
:: Processing package changes...
( 1/28) reinstalling gawk                                                                                                                               [##############################################################################################] 100%
( 2/28) reinstalling m4                                                                                                                                 [##############################################################################################] 100%
( 3/28) reinstalling autoconf                                                                                                                           [##############################################################################################] 100%
( 4/28) reinstalling automake                                                                                                                           [##############################################################################################] 100%
( 5/28) reinstalling findutils                                                                                                                          [##############################################################################################] 100%
( 6/28) reinstalling binutils                                                                                                                           [##############################################################################################] 100%
( 7/28) reinstalling bison                                                                                                                              [##############################################################################################] 100%
( 8/28) reinstalling sed                                                                                                                                [##############################################################################################] 100%
( 9/28) reinstalling fakeroot                                                                                                                           [##############################################################################################] 100%
(10/28) reinstalling file                                                                                                                               [##############################################################################################] 100%
(11/28) reinstalling flex                                                                                                                               [##############################################################################################] 100%
(12/28) reinstalling gcc                                                                                                                                [##############################################################################################] 100%
(13/28) reinstalling gettext                                                                                                                            [##############################################################################################] 100%
(14/28) reinstalling grep                                                                                                                               [##############################################################################################] 100%
(15/28) reinstalling groff                                                                                                                              [##############################################################################################] 100%
(16/28) reinstalling gzip                                                                                                                               [##############################################################################################] 100%
(17/28) reinstalling libtool                                                                                                                            [##############################################################################################] 100%
(18/28) reinstalling texinfo                                                                                                                            [##############################################################################################] 100%
(19/28) reinstalling make                                                                                                                               [##############################################################################################] 100%
(20/28) reinstalling python                                                                                                                             [##############################################################################################] 100%
(21/28) reinstalling pacman                                                                                                                             [##############################################################################################] 100%
(22/28) reinstalling patch                                                                                                                              [##############################################################################################] 100%
(23/28) reinstalling pkgconf                                                                                                                            [##############################################################################################] 100%
(24/28) reinstalling sudo                                                                                                                               [##############################################################################################] 100%
(25/28) reinstalling which                                                                                                                              [##############################################################################################] 100%
(26/28) reinstalling audiofile                                                                                                                          [##############################################################################################] 100%
(27/28) reinstalling sdl2                                                                                                                               [##############################################################################################] 100%
(28/28) reinstalling glew                                                                                                                               [##############################################################################################] 100%


Again im trying to compile a windows exe please read back over my post

**Comment by Jan200101** [comment]
If you want to compile and exe for Windows you should follow the [Windows Guide](https://github.com/sm64pc/sm64pc/wiki/Compiling-on-Windows).
If you want to compile *for* Windows under Linux you can use the MinGW toolchain but you are on your own on getting that to work
