### ISSUE TITLE
Bettercam sensitivity issues when X and/or Y are inverted

### ISSUE THREAD

**Issue by Zero-Shift** [sm64pc/sm64pc#62]
**Describe the bug**
When either X or Y are inverted on Bettercamera builds, said axis's sensitivity is through the roof causing the camera to be unusable.

**To Reproduce**
1. Invert X or Y axis

**Comment by urherenow** [comment]
unless it's just me, right after the merge with main (haven't checked for new commits yet this morning) DISABLED is actually ENABLED for analog camera. in the pause-Rbutton menu

**Comment by IvanDSM** [comment]
Thanks for the report. I've pushed a couple of commits that fix both the crazy invert axis option and the hardcoded 75 sensitivity. These have been pushed to master and I will update testing in just a bit.

**Comment by IvanDSM** [comment]
I've checked and apparently testing doesn't need any fixes. Both issues are already resolved there.

**Comment by Zero-Shift** [comment]
The camera inversion issue is indeed fixed, however now sensitivity is set to 250 and cannot be modified ingame or in the config file

**Comment by urherenow** [comment]
don't celebrate yet. I just did a fresh pull, make clean, then rebuild, and nor the r-button menu is gone from the pause screen. I can't turn analog camera on now.

**Comment by cblankpixel** [comment]
> 
> 
> The camera inversion issue is indeed fixed, however now sensitivity is set to 250 and cannot be modified ingame or in the config file

I know what the issue is. I'm adding a PR to fix this.
