### ISSUE TITLE
Possible to split this PC port into Server and Client Code?

### ISSUE THREAD

**Issue by snuffysasa** [sm64pc/sm64pc#64]
I started looking through this code this weekend and compiling it and just trying some very small mods to get the hand of it and learn it.  Been having some fun just messing with the physics and or making various cheats or silly things.   I wanted to start a project where I'd work on making some online multiplayer with super mario 64 (probably use the webOpenGL)... anyone know of any similar projects?   I was thinking about it and the first thing I would want to see if I can to is split the code into client and server code and setup some interface... Though, thinking about it and looking at the code, perhaps this may be more challenging than I imagined.  Does anyone have any recommendations on what modules should go where and how this could work out or what it could look like, or if its even possible.... or am I just going to run into a giant world of pain/headache?

**Comment by rainyuu** [comment]
well, you'd have to make server software and mod the feature to connect into it into the game and then also make the game properly interpret data from the server and do things with it

**Comment by HengiFettlich** [comment]
It certainly is possible, you have the source code.
The structure is up to you, just fork it and structure it however you want.

**Comment by snuffysasa** [comment]
Thanks for the advice.   Yea I have some experience making game server code and working with online client server game....

I am wondering if anyone has attempted something like this before with sm64... so I wouldn't be starting from scratch.   There is not much documentation on this code I am  wondering if there exists anything somewhere? any kind of diagrams or tables that describe the different moving pieces / modules?  I figure this is a long shot ha.

**Comment by Nicknakin** [comment]
I believe you can run doxygen to get some documentation, not sure how thorough it is.

**Comment by johnlorentzson** [comment]
I think that a server/client structure would be a bad fit for SM64 without a lot of work.
Then again, I'm not *that* experienced with its codebase yet, but it seems to be built like a typical singleplayer game, so making it into server/client would be rather difficult. If you just want some sort of multiplayer to work, you can try doing something similar to how Doom (1993) handled multiplayer (by sending inputs to all players and having everyone run the game separately).

**Comment by snuffysasa** [comment]
> I think that a server/client structure would be a bad fit for SM64 without a lot of work.
> Then again, I'm not _that_ experienced with its codebase yet, but it seems to be built like a typical singleplayer game, so making it into server/client would be rather difficult.

Yea I was afraid that would be the case. :(   Thanks for your opinion

> If you just want some sort of multiplayer to work, you can try doing something similar to how Doom (1993) handled multiplayer (by sending inputs to all players and having everyone run the game separately).

Yea I am considering trying something like that.. or just abandoning the idea.  As you describe wouldn't there be issues with going out of sync?  I am thinking of something similar... where everyone runs their own copy of the full game... however, they all send their character/Mario location and state to a server.. which forwards to all players... not really sure what info would need to be sent yet.. and what interface would be necessary to receive info about the other players state and do something with that.

**Comment by fgsfdsfgs** [comment]
Lock-step P2P like Doom and other early games with multiplayer does not hold up well when the latency gets high, especially with multiple players, but it only requires sending the input and syncing the RNG seed, so it might be simple enough to implement.

**Comment by snuffysasa** [comment]
> Lock-step P2P like Doom and other early games with multiplayer does not hold up well when the latency gets high, especially with multiple players, but it only requires sending the input and syncing the RNG seed, so it might be simple enough to implement.

I didn't even think about RNG seed... I wonder how much RNG there is in a typical super mario 64 level.

**Comment by natepley** [comment]
You want to make something like Kaze Emanuar's SM64 Online?  That would be cool!  Maybe you could work with him.

**Comment by snuffysasa** [comment]
@natepley 

That is very cool!!! I looked though his youtube playlist and holy smokes he has been busy with tons of mods.. that is amazing!   And yea looks like he made something similar to what I was imagining... except probably well beyond what I had in mind...   I am curious how it works his online... each client must have an n64 emulator running on their computer... and then he must have made an interface from the web to the emulator and then into the sm64 rom code... ? I will try to get in contact with him, very cool.   I am still motivated to do something similar with the PC port / web port, so no emulator is necessary and to open source it for other people to play with.
