### ISSUE TITLE
"make: Nothing to be done for 'default'." Using emsdk after successfully compiling for Ubuntu

### ISSUE THREAD

**Issue by chronic8000** [sm64pc/sm64pc#67]
**Describe the bug**
Using emsdk when I run "make TARGET_WEB=1" all I get is "make: Nothing to be done for 'default'." I ran make clean and it ran but didn't fix the issue. 

**To Reproduce**
make TARGET_WEB=1

**Expected behavior**
load emmc and start compilation.

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04 LTS]

**Comment by chronic8000** [comment]
emsdk is installed and working fine when I call emcc from Terminal I get:

ache:INFO: generating system asset: is_vanilla.txt... (this will be cached in "/home/chronic/.emscripten_cache/is_vanilla.txt" for subsequent builds)
cache:INFO:  - ok
emcc:WARNING: no input files

**Comment by chronic8000** [comment]
Seems to be working fine using msys2 on Windows 10 instead of Ubuntu :)

**Comment by urherenow** [comment]
I had the opposite, yesterday. Msys2 was saying nothing to be done. Ubuntu compiled fine. After pulling the latest source this morning, Msys2 was working.

BUT in both cases, the end result does not work. Are you able to open the html file and play? Please see the issue I opened (Building for web) to see what I’m getting.

**Comment by Jan200101** [comment]
Works fine on Fedora 31, Fedora 32 and Debian 10

**Comment by urherenow** [comment]
I got it working as well after pulling the latest source (after the better camera mode merge). I did find, however, that ./emsdk_env.sh doesn’t seem to properly set the path for emscripten. (See if emcc actually works. If not, add the path, even to ~/.bashrc, if you want it set permanently. Don’t forget to add
 :$PATH  at the end)

**Comment by Jan200101** [comment]
@urherenow you aren't suppose to run it
you are suppose to source it e.g. `source ./emsdk_env.sh`

**Comment by coltongit** [comment]
@chronic8000 this is easily fixable by moving your Ubuntu build output to a different dir (in the case you want to keep the build), running `make clean`, then running `make TARGET_WEB=1`.

**Comment by chronic8000** [comment]
> @chronic8000 this is easily fixable by moving your Ubuntu build output to a different dir (in the case you want to keep the build), running `make clean`, then running `make TARGET_WEB=1`.

I fixed it anyway and it compiled successfully :)

**Comment by coltongit** [comment]
👍

**Comment by Project516** [comment]
> @urherenow you aren't suppose to run it you are suppose to source it e.g. `source ./emsdk_env.sh`
> 
> it doesn't run when opening the html file directly due to a browser related issue. Once you sourced emsdk you can use `emrun` to execute it (you might need to run `emrun --no_browser` because it takes a bit to load)

@Jan200101 @urherenow btw some one make sm64 in a html file hosted locally. right here - https://github.com/SnubbyOWO/Mario64Offline
