### ISSUE TITLE
Feature Request: option to build n64 rom

### ISSUE THREAD

**Issue by ZiroGX2** [sm64pc/sm64pc#8]
Yes I know this is sm64pc, but I feel this would be a whole lot more useful if this could still build an n64 rom as being able to develop a romhack for multiple targets would be useful to many. If this is feasible please consider (and if by any chance this feature is there and I am just too stupid to realize give me a virtual slap.)

**Comment by rainyuu** [comment]
https://github.com/n64decomp/sm64

**Comment by Jan200101** [comment]
Compiling an n64 rom has been completly stripped out and is no longer a goal of this project
