### ISSUE TITLE
How to write to console and view console for the windows build?

### ISSUE THREAD

**Issue by snuffysasa** [sm64pc/sm64pc#84]
I can compile the windows 32bit application and it runs fine.  When I launch it, even from command line, it seems to detach from command line and I don't know how to view any console.

I tried sm64.us.f3dex2e.exe > test.txt  but that doesn't seem to work

I have been mostly working on the emscripten wasm build and I have been able to get console out with that, but also want to do some development and debugging for the windows application but haven't been able to figure out how to view a console for debugging.

Thanks

**Comment by snuffysasa** [comment]
**Update**: These steps worked for me: [StackOverflow - How do I get console output in C++ with a windows program](https://stackoverflow.com/questions/191842/how-do-i-get-console-output-in-c-with-a-windows-program)

However, I am wondering is there a better way? Surely, the team that made this port must have had some debugging / diagnostics tools already created?

**Comment by Jan200101** [comment]
you could simply compile the program to be a console program by adding `-mconsole` to LDFLAGS in the Makefile

**Comment by vrmiguel** [comment]
> you could simply compile the program to be a console program by adding `-mconsole` to LDFLAGS in the Makefile

True. We've also added that onto master's Makefile, add `WINDOWS_CONSOLE=1` when running `make`.

**Comment by snuffysasa** [comment]
Great thank you!!
