### ISSUE TITLE
Save is incompatible with cartridge EEPROM

### ISSUE THREAD

**Issue by DanTheMan827** [sm64pc/sm64pc#95]
**Describe the bug**
Due to the endianness being different, the eeprom is incompatible with that from a genuine cartridge.

**To Reproduce**
1. Try use a dumped save from a cartridge

**Expected behavior**
The save loads properly.

**Actual behavior**
All slots show as empty and the global data is at the defaults, this is due to the checksum and the magic numbers being incorrect due to the swapped bytes.

Another side effect is that save editors cannot be used with the port.

**Comment by fgsfdsfgs** [comment]
Try the testing branch now, the saves should now be stored in big endian since 141f6be.

**Comment by DanTheMan827** [comment]
Wouldn't the `save_file_need_bswap` function fail if run on big endian?

You never know if this will at some point be built for something like a Wii U or PowerPC Mac

**Comment by fgsfdsfgs** [comment]
It will return true if the save is not in the native byte order, so if you feed it a little endian save, the byte order of the magic value will be swapped compared to what is expected, if you feed it a big endian save, the byte order will be the same as the native one and it will return false.

**Comment by DanTheMan827** [comment]
So if the app is built for a big endian architecture, it will incorrectly swap it to little endian for the save then.

**Comment by fgsfdsfgs** [comment]
How so? The saving only swaps stuff if `IS_BIG_ENDIAN` is set to `1`. The reading only swaps stuff if the magic value is swapped.

**Comment by DanTheMan827** [comment]
My bad... I missed that part...

**Comment by coltongit** [comment]
@DanTheMan827 current master and nightly iirc have the ability to read both big and little-endian saves now. Should be able to write cartridge-compatible saves now too. Plz update and check if you can

**Comment by DanTheMan827** [comment]
I created a save with a n64 save editor and it loaded without issue with this commit, I haven't tested it with a n64 emulator, but it does seem to save properly as big endian

**Comment by vrmiguel** [comment]
Support for both endiannesses has been added to both master and nightly branches.
