### ISSUE TITLE
Compilation error for WebGL build

### ISSUE THREAD

**Issue by Tikilou** [sm64pc/sm64pc#96]
Hello, the compiler complain about "src/game/main.h" file on line 76, and want this replacement :

`extern void main(void)`

Should apparently be replaced by

`extern int main(void)`

**Comment by coltongit** [comment]
@Tikilou Can you retry WebGL building using the latest nightly and the changes from PR #151? They should fix your issue.

**Comment by Tikilou** [comment]
Unfortunatly, i still have somes errors. :(

`emcc -c -O2 -g4 --source-map-base http://localhost:8080/ -I include -I build/us_web -I build/us_web/include -I src -I . -DVERSION_US -DNON_MATCHING -DAVOID_UB -DTARGET_WEB -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -s USE_SDL=2 -DBETTERCAMERA -DEXT_OPTIONS_MENU -o build/us_web/src/game/interaction.o src/game/interaction.c
emcc -c -O2 -g4 --source-map-base http://localhost:8080/ -I include -I build/us_web -I build/us_web/include -I src -I . -DVERSION_US -DNON_MATCHING -DAVOID_UB -DTARGET_WEB -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -s USE_SDL=2 -DBETTERCAMERA -DEXT_OPTIONS_MENU -o build/us_web/src/game/level_geo.o src/game/level_geo.c
In file included from src/game/level_update.c:11:
src/game/main.h:76:8: warning: return type of 'main' is not 'int' [-Wmain-return-type]
extern void main(void);
       ^
src/game/main.h:76:8: note: change return type to 'int'
extern void main(void);
       ^~~~
       int
In file included from src/game/level_update.c:31:
src/game/../../include/libc/stdlib.h:8:3: error: typedef redefinition with different types ('struct lldiv_t' vs 'struct lldiv_t' (aka 'lldiv_t'))
} lldiv_t;
  ^
/usr/lib/emscripten/system/include/libc/stdlib.h:64:41: note: previous definition is here
typedef struct { long long quot, rem; } lldiv_t;
                                        ^
In file included from src/game/level_update.c:31:
src/game/../../include/libc/stdlib.h:14:3: error: typedef redefinition with different types ('struct ldiv_t' vs 'struct ldiv_t' (aka 'ldiv_t'))
} ldiv_t;
  ^
/usr/lib/emscripten/system/include/libc/stdlib.h:63:36: note: previous definition is here
typedef struct { long quot, rem; } ldiv_t;
                                   ^
1 warning and 2 errors generated.
make: *** [Makefile:797 : build/us_web/src/game/level_update.o] Erreur 1
`

**Comment by coltongit** [comment]
I've added fixes for at least some of those errors. Try again with the latest version of PR #151.

**Comment by Tikilou** [comment]
Okay, i will try it

**Comment by Tikilou** [comment]
Thanks, your patch have fixed the problem, but there is new errors :

`emcc -c -O2 -g4 --source-map-base http://localhost:8080/ -I include -I build/us_web -I build/us_web/include -I src -I . -DVERSION_US -DNON_MATCHING -DAVOID_UB -DTARGET_WEB -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -s USE_SDL=2 -DEXT_OPTIONS_MENU -o build/us_web/bin/debug_level_select.o bin/debug_level_select.c
src/pc/cliopts.c:14:5: error: implicitly declaring library function 'strncpy' with type 'char *(char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
    strncpy(gCLIOpts.ConfigFile, "sm64config.txt", strlen("sm64config.txt"));
    ^
src/pc/cliopts.c:14:5: note: include the header <string.h> or explicitly provide a declaration for 'strncpy'
src/pc/cliopts.c:14:52: error: implicitly declaring library function 'strlen' with type 'unsigned long (const char *)' [-Werror,-Wimplicit-function-declaration]
    strncpy(gCLIOpts.ConfigFile, "sm64config.txt", strlen("sm64config.txt"));
                                                   ^
src/pc/cliopts.c:14:52: note: include the header <string.h> or explicitly provide a declaration for 'strlen'
src/pc/cliopts.c:22:8: error: implicitly declaring library function 'strcmp' with type 'int (const char *, const char *)' [-Werror,-Wimplicit-function-declaration]
                        if (strcmp(argv[i], "--skip-intro") == 0) // Skip Peach Intro
                            ^
src/pc/cliopts.c:22:8: note: include the header <string.h> or explicitly provide a declaration for 'strcmp'
src/pc/cliopts.c:41:17: error: implicitly declaring library function 'strncmp' with type 'int (const char *, const char *, unsigned long)' [-Werror,-Wimplicit-function-declaration]
            if (strncmp(argv[i], "--configfile", strlen("--configfile")) == 0)
                ^
src/pc/cliopts.c:41:17: note: include the header <string.h> or explicitly provide a declaration for 'strncmp'
src/pc/cliopts.c:48:7: error: implicitly declaring library function 'memset' with type 'void *(void *, int, unsigned long)' [-Werror,-Wimplicit-function-declaration]
                                                memset(gCLIOpts.ConfigFile, 0, 30);
                                                ^
src/pc/cliopts.c:48:7: note: include the header <string.h> or explicitly provide a declaration for 'memset'
5 errors generated.
make: *** [Makefile:797 : build/us_web/src/pc/cliopts.o] Erreur 1
make: *** Attente des tâches non terminées....
emcc -c -O2 -g4 --source-map-base http://localhost:8080/ -I include -I build/us_web -I build/us_web/include -I src -I . -DVERSION_US -DNON_MATCHING -DAVOID_UB -DTARGET_WEB -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -s USE_SDL=2 -DEXT_OPTIONS_MENU -o build/us_web/src/pc/configfile.o src/pc/configfile.c
data/behavior_data.c:3147:29: warning: unused variable 'unused_1' [-Wunused-const-variable]
static const BehaviorScript unused_1[] = {
                            ^
1 warning generated.
emcc -c -O2 -g4 --source-map-base http://localhost:8080/ -I include -I build/us_web -I build/us_web/include -I src -I . -DVERSION_US -DNON_MATCHING -DAVOID_UB -DTARGET_WEB -DF3DEX_GBI_2E -fno-strict-aliasing -fwrapv -s USE_SDL=2 -DEXT_OPTIONS_MENU -o build/us_web/data/behavior_data.o data/behavior_data.c
`

**Comment by coltongit** [comment]
#151 updated. Please update and try again @Tikilou

**Comment by Tikilou** [comment]
Thanks !! It's fixed, i can run the game in web browser ! =)

**Comment by coltongit** [comment]
A better fix has since been pushed to master and nightly. Please recheck using current master, and if the build still works for you afterwards, please close this, @Tikilou.

**Comment by Tikilou** [comment]
In master, there is always somes problems here.

`In file included from src/game/level_update.c:31:
src/game/../../include/libc/stdlib.h:8:3: error: typedef redefinition with different types ('struct lldiv_t' vs 'struct lldiv_t' (aka 'lldiv_t'))
} lldiv_t;
  ^
/usr/lib/emscripten/system/include/libc/stdlib.h:64:41: note: previous definition is here
typedef struct { long long quot, rem; } lldiv_t;
                                        ^
In file included from src/game/level_update.c:31:
src/game/../../include/libc/stdlib.h:14:3: error: typedef redefinition with different types ('struct ldiv_t' vs 'struct ldiv_t' (aka 'ldiv_t'))
} ldiv_t;
  ^
/usr/lib/emscripten/system/include/libc/stdlib.h:63:36: note: previous definition is here
typedef struct { long quot, rem; } ldiv_t;
                                   ^
1 warning and 2 errors generated.
make: *** [Makefile:796 : build/us_web/src/game/level_update.o] Erreur 1
`

**Comment by coltongit** [comment]
try combining current #151 with master and nightly and see if that fixes building again

**Comment by fgsfdsfgs** [comment]
@Tikilou Post a text file or a pastebin of the full log if possible. I'm pretty sure there's no stdlib includes in any important places in master.

**Comment by coltongit** [comment]
I've pushed a fix that should allow anyone and everyone to compile the game without error into #151.
@Tikilou @RulerOf @lolxnn please update to the latest version of the PR and see if it fixes compilation for all of you.

**Comment by coltongit** [comment]
The relevant PR has been merged, so this can be closed @Tikilou
